apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/invoker-iam-disabled: 'true'
    run.googleapis.com/maxScale: '3'
    run.googleapis.com/minScale: '0'
  labels:
    cloud.googleapis.com/location: europe-west1
  name: portaltesisvm
  namespace: '1004187222399'
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '3'
        autoscaling.knative.dev/minScale: '0'
    spec:
      containerConcurrency: 80
      containers:
      - image: europe-west1-docker.pkg.dev/portal-tesis-ecuador-508108/cloud-run-source-deploy/vm199524-portal-tesis-ecuador/portaltesisvm:e7f5208c9318c87c572d28ab33537d7f60064179
        name: portaltesisvm
        ports:
        - containerPort: 8080
          name: http1
        resources:
          limits:
            cpu: '1'
            memory: 1Gi
        env:
        - name: NODE_ENV
          value: production
        - name: APP_URL
          value: https://portaltesis.web.app
        - name: AUTH_SECRET
          value: "PT/hZKI9HXULeUlS1FSeKN8YhZqD+o/ruxyipoQ2CJIod+ikBA9vRTA3If4lmp55"
      serviceAccountName: 1004187222399-compute@developer.gserviceaccount.com
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
