/**
 * Los cinco capítulos de la tesis, traducidos.
 *
 * Claves `chapter.<número>.<campo>`, y para las listas
 * `chapter.<número>.deliverable.<i>` / `chapter.<número>.check.<i>`, con el
 * mismo orden que `CHAPTERS_DATA` en `src/data/thesisData.ts`.
 */

import type { ContentDict } from './types';

export const CHAPTER_TRANSLATIONS: ContentDict = {
  // ------------------------------------------------------------- rótulos comunes
  'chapter.roman.1': { es: 'Capítulo I', en: 'Chapter I', pt: 'Capítulo I', fr: 'Chapitre I', it: 'Capitolo I' },
  'chapter.roman.2': { es: 'Capítulo II', en: 'Chapter II', pt: 'Capítulo II', fr: 'Chapitre II', it: 'Capitolo II' },
  'chapter.roman.3': { es: 'Capítulo III', en: 'Chapter III', pt: 'Capítulo III', fr: 'Chapitre III', it: 'Capitolo III' },
  'chapter.roman.4': { es: 'Capítulo IV', en: 'Chapter IV', pt: 'Capítulo IV', fr: 'Chapitre IV', it: 'Capitolo IV' },
  'chapter.roman.5': { es: 'Capítulo V', en: 'Chapter V', pt: 'Capítulo V', fr: 'Chapitre V', it: 'Capitolo V' },

  // ----------------------------------------------------------------- Capítulo I
  'chapter.1.title': { es: 'El Problema de Investigación', en: 'The Research Problem', pt: 'O Problema de Pesquisa', fr: 'Le Problème de Recherche', it: 'Il Problema di Ricerca' },
  'chapter.1.question': { es: '¿Cuál es la problemática identificada, su justificación científica y los objetivos planteados?', en: 'What is the problem identified, its scientific rationale and the objectives set out?', pt: 'Qual é a problemática identificada, a sua justificativa científica e os objetivos propostos?', fr: 'Quelle est la problématique identifiée, sa justification scientifique et les objectifs posés ?', it: 'Qual è la problematica individuata, la sua giustificazione scientifica e gli obiettivi posti?' },
  'chapter.1.purpose': { es: 'Establece el fundamento ontológico y práctico de la investigación, delimitando con precisión el perímetro del objeto de estudio.', en: 'Establishes the ontological and practical grounding of the research, drawing a precise boundary around the object of study.', pt: 'Estabelece o fundamento ontológico e prático da pesquisa, delimitando com precisão o perímetro do objeto de estudo.', fr: 'Établit le fondement ontologique et pratique de la recherche, en délimitant précisément le périmètre de l\'objet d\'étude.', it: 'Stabilisce il fondamento ontologico e pratico della ricerca, delimitando con precisione il perimetro dell\'oggetto di studio.' },
  'chapter.1.keyMistake': { es: 'Formulación de objetivos centrados en actividades operativas (e.g., "revisar bibliografía" o "aplicar cuestionarios"). Los objetivos de investigación deben expresar logros cognitivos: Determinar, Analizar, Evaluar, Establecer.', en: 'Writing objectives around operational activities ("review the literature", "hand out questionnaires"). Research objectives must express cognitive achievements: determine, analyse, evaluate, establish.', pt: 'Formular objetivos centrados em atividades operacionais ("revisar bibliografia", "aplicar questionários"). Os objetivos devem expressar realizações cognitivas: determinar, analisar, avaliar, estabelecer.', fr: 'Formuler des objectifs centrés sur des activités opérationnelles (« consulter la bibliographie », « administrer des questionnaires »). Les objectifs doivent exprimer des acquis cognitifs : déterminer, analyser, évaluer, établir.', it: 'Formulare obiettivi centrati su attività operative ("consultare la bibliografia", "somministrare questionari"). Gli obiettivi devono esprimere traguardi cognitivi: determinare, analizzare, valutare, stabilire.' },
  'chapter.1.formulaOrTemplate': { es: 'Objetivo General = [Verbo en infinitivo] + [Variable Independiente] + [Conector metodológico] + [Variable Dependiente] + en [Población / Unidad de estudio], [Contexto geográfico y temporal].', en: 'General objective = [infinitive verb] + [independent variable] + [methodological connector] + [dependent variable] + in [population / unit of study], [geographic and temporal context].', pt: 'Objetivo geral = [verbo no infinitivo] + [variável independente] + [conector metodológico] + [variável dependente] + em [população / unidade de estudo], [contexto geográfico e temporal].', fr: 'Objectif général = [verbe à l\'infinitif] + [variable indépendante] + [connecteur méthodologique] + [variable dépendante] + dans [population / unité d\'étude], [contexte géographique et temporel].', it: 'Obiettivo generale = [verbo all\'infinito] + [variabile indipendente] + [connettore metodologico] + [variabile dipendente] + in [popolazione / unità di studio], [contesto geografico e temporale].' },
  'chapter.1.deliverable.0': { es: 'Planteamiento del problema contextualizado (método deductivo del embudo: internacional → regional → local)', en: 'Contextualised problem statement (deductive funnel: international → regional → local)', pt: 'Formulação do problema contextualizada (funil dedutivo: internacional → regional → local)', fr: 'Énoncé du problème contextualisé (entonnoir déductif : international → régional → local)', it: 'Formulazione del problema contestualizzata (imbuto deduttivo: internazionale → regionale → locale)' },
  'chapter.1.deliverable.1': { es: 'Formulación precisa de la pregunta general y preguntas específicas de investigación', en: 'Precise wording of the general research question and the specific questions', pt: 'Formulação precisa da pergunta geral e das perguntas específicas de pesquisa', fr: 'Formulation précise de la question générale et des questions spécifiques', it: 'Formulazione precisa della domanda generale e delle domande specifiche' },
  'chapter.1.deliverable.2': { es: 'Objetivo general y objetivos específicos estructurados según la Taxonomía de Bloom', en: 'General and specific objectives structured with Bloom\'s taxonomy', pt: 'Objetivo geral e objetivos específicos estruturados pela taxonomia de Bloom', fr: 'Objectif général et objectifs spécifiques structurés selon la taxonomie de Bloom', it: 'Obiettivo generale e obiettivi specifici strutturati secondo la tassonomia di Bloom' },
  'chapter.1.deliverable.3': { es: 'Justificación tripartita: Teórica (vacío en el conocimiento), Práctica (utilidad tangible), Metodológica (innovación instrumental)', en: 'Three-part rationale: theoretical (knowledge gap), practical (tangible use), methodological (instrumental innovation)', pt: 'Justificativa tripartite: teórica (lacuna de conhecimento), prática (utilidade tangível), metodológica (inovação instrumental)', fr: 'Justification en trois volets : théorique (lacune), pratique (utilité tangible), méthodologique (innovation instrumentale)', it: 'Giustificazione tripartita: teorica (vuoto di conoscenza), pratica (utilità tangibile), metodologica (innovazione strumentale)' },
  'chapter.1.deliverable.4': { es: 'Delimitación espacial, temporal y conceptual de la investigación', en: 'Spatial, temporal and conceptual scope of the research', pt: 'Delimitação espacial, temporal e conceitual da pesquisa', fr: 'Délimitation spatiale, temporelle et conceptuelle de la recherche', it: 'Delimitazione spaziale, temporale e concettuale della ricerca' },
  'chapter.1.check.0': { es: '¿La pregunta general incorpora explícitamente las variables de estudio y la unidad de análisis?', en: 'Does the general question explicitly name the study variables and the unit of analysis?', pt: 'A pergunta geral menciona explicitamente as variáveis de estudo e a unidade de análise?', fr: 'La question générale nomme-t-elle explicitement les variables et l\'unité d\'analyse ?', it: 'La domanda generale nomina esplicitamente le variabili e l\'unità di analisi?' },
  'chapter.1.check.1': { es: '¿Los objetivos específicos se articulan de forma lógica y secuencial para dar cumplimiento al objetivo general?', en: 'Do the specific objectives follow a logical sequence that adds up to the general objective?', pt: 'Os objetivos específicos seguem uma sequência lógica que cumpre o objetivo geral?', fr: 'Les objectifs spécifiques s\'enchaînent-ils logiquement pour réaliser l\'objectif général ?', it: 'Gli obiettivi specifici seguono una sequenza logica che realizza l\'obiettivo generale?' },
  'chapter.1.check.2': { es: '¿La justificación sustenta el impacto tangible en una organización, comunidad o disciplina científica?', en: 'Does the rationale show tangible impact on an organisation, a community or a scientific field?', pt: 'A justificativa sustenta um impacto tangível numa organização, comunidade ou disciplina científica?', fr: 'La justification établit-elle un impact tangible sur une organisation, une communauté ou une discipline ?', it: 'La giustificazione dimostra un impatto tangibile su un\'organizzazione, una comunità o una disciplina?' },
  'chapter.1.check.3': { es: '¿El planteamiento del problema se encuentra fundamentado en indicadores estadísticos o fuentes bibliográficas de respaldo?', en: 'Is the problem statement backed by statistical indicators or supporting literature?', pt: 'A formulação do problema está fundamentada em indicadores estatísticos ou fontes bibliográficas?', fr: 'L\'énoncé du problème s\'appuie-t-il sur des indicateurs statistiques ou des sources bibliographiques ?', it: 'La formulazione del problema è sostenuta da indicatori statistici o fonti bibliografiche?' },

  // ---------------------------------------------------------------- Capítulo II
  'chapter.2.title': { es: 'Marco Teórico & Estado del Arte', en: 'Theoretical Framework & State of the Art', pt: 'Marco Teórico & Estado da Arte', fr: 'Cadre Théorique & État de l\'Art', it: 'Quadro Teorico & Stato dell\'Arte' },
  'chapter.2.question': { es: '¿Qué literatura científica previa fundamenta las variables y cuáles son las bases conceptuales?', en: 'What prior scientific literature grounds the variables, and what are the conceptual foundations?', pt: 'Que literatura científica anterior fundamenta as variáveis e quais são as bases conceituais?', fr: 'Quelle littérature scientifique antérieure fonde les variables et quelles en sont les bases conceptuelles ?', it: 'Quale letteratura scientifica precedente fonda le variabili e quali sono le basi concettuali?' },
  'chapter.2.purpose': { es: 'Acredita el dominio del estado contemporáneo del conocimiento y sitúa la investigación en la frontera del desarrollo disciplinar.', en: 'Demonstrates command of the current state of knowledge and places the research at the disciplinary frontier.', pt: 'Comprova o domínio do estado atual do conhecimento e situa a pesquisa na fronteira do desenvolvimento disciplinar.', fr: 'Atteste la maîtrise de l\'état actuel des connaissances et situe la recherche à la frontière de la discipline.', it: 'Attesta la padronanza dello stato attuale delle conoscenze e colloca la ricerca alla frontiera disciplinare.' },
  'chapter.2.keyMistake': { es: 'Yuxtaposición inconexa de resúmenes bibliográficos. Cada antecedente debe articularse mediante la fórmula: Autor (año) + Objetivo + Metodología y Muestra + Hallazgo principal + Contribución concreta a la presente investigación.', en: 'Stacking disconnected summaries. Each prior study should follow: author (year) + objective + method and sample + main finding + concrete contribution to this research.', pt: 'Justapor resumos desconexos. Cada antecedente deve seguir: autor (ano) + objetivo + método e amostra + achado principal + contribuição concreta para esta pesquisa.', fr: 'Juxtaposer des résumés déconnectés. Chaque antécédent doit suivre : auteur (année) + objectif + méthode et échantillon + résultat principal + apport concret à la présente recherche.', it: 'Giustapporre riassunti scollegati. Ogni antecedente deve seguire: autore (anno) + obiettivo + metodo e campione + risultato principale + contributo concreto a questa ricerca.' },
  'chapter.2.formulaOrTemplate': { es: 'Estructura por Antecedente: "[Autor] ([Año]), en su investigación titulada [Título], analizó [Objetivo]. Empleando una muestra de [N participantes] y un diseño [Diseño], determinó que [Resultado principal]. Este estudio fundamenta la presente investigación al aportar [Contribución metodológica o teórica]."', en: 'Template per prior study: "[Author] ([year]), in the study titled [title], examined [objective]. Using a sample of [N participants] and a [design] design, found that [main result]. This study underpins the present research by contributing [methodological or theoretical contribution]."', pt: 'Modelo por antecedente: "[Autor] ([ano]), na pesquisa intitulada [título], analisou [objetivo]. Com uma amostra de [N participantes] e um desenho [desenho], determinou que [resultado principal]. Este estudo fundamenta a presente pesquisa ao aportar [contribuição]."', fr: 'Modèle par antécédent : « [Auteur] ([année]), dans l\'étude intitulée [titre], a analysé [objectif]. Avec un échantillon de [N participants] et un design [design], a déterminé que [résultat principal]. Cette étude fonde la présente recherche en apportant [contribution]. »', it: 'Modello per antecedente: "[Autore] ([anno]), nello studio intitolato [titolo], ha analizzato [obiettivo]. Con un campione di [N partecipanti] e un disegno [disegno], ha determinato che [risultato principale]. Questo studio fonda la presente ricerca apportando [contributo]."' },
  'chapter.2.deliverable.0': { es: 'Antecedentes internacionales (3 a 5 artículos indexados en Scopus/WoS correspondientes al último quinquenio)', en: 'International prior work (3–5 Scopus/WoS indexed articles from the last five years)', pt: 'Antecedentes internacionais (3 a 5 artigos indexados em Scopus/WoS dos últimos cinco anos)', fr: 'Antécédents internationaux (3 à 5 articles indexés Scopus/WoS des cinq dernières années)', it: 'Antecedenti internazionali (3-5 articoli indicizzati Scopus/WoS degli ultimi cinque anni)' },
  'chapter.2.deliverable.1': { es: 'Antecedentes nacionales o regionales (3 a 5 investigaciones o publicaciones arbitradas)', en: 'National or regional prior work (3–5 peer-reviewed studies or publications)', pt: 'Antecedentes nacionais ou regionais (3 a 5 pesquisas ou publicações arbitradas)', fr: 'Antécédents nationaux ou régionaux (3 à 5 recherches ou publications évaluées)', it: 'Antecedenti nazionali o regionali (3-5 ricerche o pubblicazioni con revisione)' },
  'chapter.2.deliverable.2': { es: 'Bases teóricas que fundamentan conceptualmente cada variable y dimensión del estudio', en: 'Theoretical foundations grounding each variable and dimension of the study', pt: 'Bases teóricas que fundamentam conceitualmente cada variável e dimensão do estudo', fr: 'Bases théoriques fondant chaque variable et dimension de l\'étude', it: 'Basi teoriche che fondano ogni variabile e dimensione dello studio' },
  'chapter.2.deliverable.3': { es: 'Definición de términos básicos y glosario operativo', en: 'Definition of key terms and a working glossary', pt: 'Definição de termos básicos e glossário operacional', fr: 'Définition des termes de base et glossaire opérationnel', it: 'Definizione dei termini di base e glossario operativo' },
  'chapter.2.deliverable.4': { es: 'Hipótesis general e hipótesis específicas (según el alcance correlacional o explicativo del estudio)', en: 'General and specific hypotheses (where the study is correlational or explanatory)', pt: 'Hipótese geral e hipóteses específicas (conforme o alcance correlacional ou explicativo)', fr: 'Hypothèse générale et hypothèses spécifiques (selon la portée corrélationnelle ou explicative)', it: 'Ipotesi generale e ipotesi specifiche (secondo la portata correlazionale o esplicativa)' },
  'chapter.2.check.0': { es: '¿Al menos el 70% de las fuentes referenciadas provienen de revistas científicas indexadas en bases reconocidas?', en: 'Do at least 70% of the sources come from journals indexed in recognised databases?', pt: 'Ao menos 70% das fontes vêm de revistas indexadas em bases reconhecidas?', fr: 'Au moins 70 % des sources proviennent-elles de revues indexées dans des bases reconnues ?', it: 'Almeno il 70% delle fonti proviene da riviste indicizzate in banche dati riconosciute?' },
  'chapter.2.check.1': { es: '¿Las fuentes bibliográficas corresponden al último quinquenio (salvo autores seminales o canónicos)?', en: 'Are the sources from the last five years (apart from seminal or canonical authors)?', pt: 'As fontes são dos últimos cinco anos (salvo autores seminais ou canônicos)?', fr: 'Les sources datent-elles des cinq dernières années (hors auteurs fondateurs) ?', it: 'Le fonti sono degli ultimi cinque anni (salvo autori seminali o canonici)?' },
  'chapter.2.check.2': { es: '¿Se evidencia un análisis dialógico y crítico entre las teorías revisadas en lugar de un glosario lineal?', en: 'Is there a critical dialogue between the theories reviewed, rather than a linear glossary?', pt: 'Há um diálogo crítico entre as teorias revisadas, em vez de um glossário linear?', fr: 'Y a-t-il un dialogue critique entre les théories, plutôt qu\'un glossaire linéaire ?', it: 'C\'è un dialogo critico fra le teorie riviste, invece di un glossario lineare?' },
  'chapter.2.check.3': { es: '¿Cada dimensión de las variables se encuentra respaldada por autores de referencia reconocidos?', en: 'Is every dimension of the variables backed by recognised reference authors?', pt: 'Cada dimensão das variáveis está respaldada por autores de referência reconhecidos?', fr: 'Chaque dimension des variables est-elle appuyée par des auteurs de référence reconnus ?', it: 'Ogni dimensione delle variabili è sostenuta da autori di riferimento riconosciuti?' },

  // --------------------------------------------------------------- Capítulo III
  'chapter.3.title': { es: 'Metodología & Diseño de la Investigación', en: 'Methodology & Research Design', pt: 'Metodologia & Desenho da Pesquisa', fr: 'Méthodologie & Design de la Recherche', it: 'Metodologia & Disegno della Ricerca' },
  'chapter.3.question': { es: '¿Mediante qué procedimientos científicos se recolecta y procesa la evidencia de forma reproducible y válida?', en: 'By what scientific procedures is the evidence collected and processed reproducibly and validly?', pt: 'Mediante quais procedimentos científicos a evidência é coletada e processada de forma reprodutível e válida?', fr: 'Par quelles procédures scientifiques les données sont-elles recueillies et traitées de façon reproductible et valide ?', it: 'Con quali procedure scientifiche si raccolgono ed elaborano le evidenze in modo riproducibile e valido?' },
  'chapter.3.purpose': { es: 'Detalla el diseño metodológico estandarizado para permitir la reproducibilidad de las mediciones por parte de la comunidad científica.', en: 'Sets out the standardised design so the scientific community can reproduce the measurements.', pt: 'Detalha o desenho metodológico padronizado para permitir a reprodutibilidade das medições pela comunidade científica.', fr: 'Détaille le design standardisé pour que la communauté scientifique puisse reproduire les mesures.', it: 'Dettaglia il disegno standardizzato perché la comunità scientifica possa riprodurre le misurazioni.' },
  'chapter.3.keyMistake': { es: 'Omitir la justificación del tamaño de la muestra o no reportar los resultados de la prueba piloto de confiabilidad con carácter previo a la aplicación definitiva del instrumento.', en: 'Leaving the sample size unjustified, or not reporting the pilot reliability test before the instrument is finally applied.', pt: 'Omitir a justificativa do tamanho da amostra ou não reportar o teste-piloto de confiabilidade antes da aplicação definitiva do instrumento.', fr: 'Omettre la justification de la taille de l\'échantillon ou ne pas rapporter le test pilote de fiabilité avant l\'application définitive.', it: 'Omettere la giustificazione della dimensione del campione o non riportare il test pilota di affidabilità prima dell\'applicazione definitiva.' },
  'chapter.3.formulaOrTemplate': { es: 'Criterio Psicométrico de Confiabilidad: Si el coeficiente Alfa de Cronbach u Omega de McDonald es inferior a 0.70, el instrumento carece de consistencia interna y exige reformulación o depuración de reactivos.', en: 'Reliability criterion: if Cronbach\'s alpha or McDonald\'s omega falls below 0.70, the instrument lacks internal consistency and items must be reworked or dropped.', pt: 'Critério de confiabilidade: se o alfa de Cronbach ou o ômega de McDonald for inferior a 0,70, o instrumento carece de consistência interna e exige reformulação ou depuração de itens.', fr: 'Critère de fiabilité : si l\'alpha de Cronbach ou l\'oméga de McDonald est inférieur à 0,70, l\'instrument manque de cohérence interne et les items doivent être revus ou supprimés.', it: 'Criterio di affidabilità: se l\'alfa di Cronbach o l\'omega di McDonald è inferiore a 0,70, lo strumento manca di coerenza interna e gli item vanno rivisti o eliminati.' },
  'chapter.3.deliverable.0': { es: 'Enfoque de investigación (Cuantitativo, Cualitativo o Mixto)', en: 'Research approach (quantitative, qualitative or mixed)', pt: 'Abordagem de pesquisa (quantitativa, qualitativa ou mista)', fr: 'Approche de recherche (quantitative, qualitative ou mixte)', it: 'Approccio di ricerca (quantitativo, qualitativo o misto)' },
  'chapter.3.deliverable.1': { es: 'Alcance o nivel del estudio (Exploratorio, Descriptivo, Correlacional, Explicativo)', en: 'Scope or level of the study (exploratory, descriptive, correlational, explanatory)', pt: 'Alcance ou nível do estudo (exploratório, descritivo, correlacional, explicativo)', fr: 'Portée ou niveau de l\'étude (exploratoire, descriptive, corrélationnelle, explicative)', it: 'Portata o livello dello studio (esplorativo, descrittivo, correlazionale, esplicativo)' },
  'chapter.3.deliverable.2': { es: 'Diseño de investigación (No experimental transeccional o experimental)', en: 'Research design (non-experimental cross-sectional, or experimental)', pt: 'Desenho de pesquisa (não experimental transversal ou experimental)', fr: 'Design de recherche (non expérimental transversal ou expérimental)', it: 'Disegno di ricerca (non sperimentale trasversale o sperimentale)' },
  'chapter.3.deliverable.3': { es: 'Delimitación de la población censal o cálculo probabilístico de la muestra (nivel de confianza 95%, margen de error 5%)', en: 'Census population definition or probabilistic sample calculation (95% confidence, 5% margin of error)', pt: 'Delimitação da população censitária ou cálculo probabilístico da amostra (95% de confiança, 5% de erro)', fr: 'Délimitation de la population ou calcul probabiliste de l\'échantillon (confiance 95 %, marge d\'erreur 5 %)', it: 'Delimitazione della popolazione o calcolo probabilistico del campione (confidenza 95%, errore 5%)' },
  'chapter.3.deliverable.4': { es: 'Matriz de operacionalización de variables (Variable → Definición conceptual → Dimensiones → Indicadores → Escala)', en: 'Variable operationalisation matrix (variable → conceptual definition → dimensions → indicators → scale)', pt: 'Matriz de operacionalização de variáveis (variável → definição conceitual → dimensões → indicadores → escala)', fr: 'Matrice d\'opérationnalisation (variable → définition conceptuelle → dimensions → indicateurs → échelle)', it: 'Matrice di operazionalizzazione (variabile → definizione concettuale → dimensioni → indicatori → scala)' },
  'chapter.3.deliverable.5': { es: 'Instrumento de recolección de datos (Cuestionario estructurado, guía de entrevista, matriz observacional)', en: 'Data-collection instrument (structured questionnaire, interview guide, observation matrix)', pt: 'Instrumento de coleta de dados (questionário estruturado, roteiro de entrevista, matriz de observação)', fr: 'Instrument de collecte (questionnaire structuré, guide d\'entretien, grille d\'observation)', it: 'Strumento di raccolta dati (questionario strutturato, guida di intervista, griglia di osservazione)' },
  'chapter.3.deliverable.6': { es: 'Validez de contenido (Juicio de 3 a 5 expertos) y Confiabilidad psicométrica (Alfa de Cronbach / Omega de McDonald > 0.80)', en: 'Content validity (panel of 3–5 experts) and reliability (Cronbach\'s alpha / McDonald\'s omega > 0.80)', pt: 'Validade de conteúdo (juízo de 3 a 5 especialistas) e confiabilidade (alfa de Cronbach / ômega de McDonald > 0,80)', fr: 'Validité de contenu (jugement de 3 à 5 experts) et fiabilité (alpha de Cronbach / oméga de McDonald > 0,80)', it: 'Validità di contenuto (giudizio di 3-5 esperti) e affidabilità (alfa di Cronbach / omega di McDonald > 0,80)' },
  'chapter.3.check.0': { es: '¿La matriz de operacionalización vincula cada ítem del instrumento con su indicador correspondiente?', en: 'Does the operationalisation matrix tie every instrument item to its indicator?', pt: 'A matriz de operacionalização vincula cada item do instrumento ao seu indicador?', fr: 'La matrice d\'opérationnalisation relie-t-elle chaque item à son indicateur ?', it: 'La matrice di operazionalizzazione lega ogni item al suo indicatore?' },
  'chapter.3.check.1': { es: '¿Se explicita la fórmula de muestreo probabilístico o los criterios formales de selección no probabilística?', en: 'Is the probabilistic sampling formula stated, or the formal criteria for non-probabilistic selection?', pt: 'A fórmula de amostragem probabilística ou os critérios de seleção não probabilística estão explícitos?', fr: 'La formule d\'échantillonnage probabiliste ou les critères de sélection non probabiliste sont-ils explicités ?', it: 'È esplicitata la formula di campionamento probabilistico o i criteri di selezione non probabilistica?' },
  'chapter.3.check.2': { es: '¿Se describen los protocolos de consentimiento informado y consideraciones éticas?', en: 'Are informed-consent protocols and ethical considerations described?', pt: 'Os protocolos de consentimento informado e as considerações éticas estão descritos?', fr: 'Les protocoles de consentement éclairé et les considérations éthiques sont-ils décrits ?', it: 'Sono descritti i protocolli di consenso informato e le considerazioni etiche?' },
  'chapter.3.check.3': { es: '¿Se especifica el software estadístico o analítico a emplear (SPSS, R, Jamovi, SmartPLS)?', en: 'Is the statistical or analytical software specified (SPSS, R, Jamovi, SmartPLS)?', pt: 'O software estatístico ou analítico está especificado (SPSS, R, Jamovi, SmartPLS)?', fr: 'Le logiciel statistique ou analytique est-il précisé (SPSS, R, Jamovi, SmartPLS) ?', it: 'È specificato il software statistico o analitico (SPSS, R, Jamovi, SmartPLS)?' },

  // ---------------------------------------------------------------- Capítulo IV
  'chapter.4.title': { es: 'Resultados & Análisis Estadístico', en: 'Results & Statistical Analysis', pt: 'Resultados & Análise Estatística', fr: 'Résultats & Analyse Statistique', it: 'Risultati & Analisi Statistica' },
  'chapter.4.question': { es: '¿Qué evidencia empírica arrojan los datos procesados y cuál es el dictamen sobre las hipótesis?', en: 'What empirical evidence do the processed data yield, and what is the verdict on the hypotheses?', pt: 'Que evidência empírica os dados processados fornecem e qual é o veredicto sobre as hipóteses?', fr: 'Quelles preuves empiriques les données traitées livrent-elles, et quel est le verdict sur les hypothèses ?', it: 'Quali evidenze empiriche forniscono i dati elaborati e qual è il verdetto sulle ipotesi?' },
  'chapter.4.purpose': { es: 'Expone la evidencia empírica procesada con estricto rigor metodológico, prescindiendo de apreciaciones subjetivas no sustentadas.', en: 'Presents the processed empirical evidence with strict methodological rigour, without unsupported subjective judgements.', pt: 'Expõe a evidência empírica processada com rigor metodológico estrito, sem apreciações subjetivas sem sustentação.', fr: 'Expose les preuves empiriques traitées avec une rigueur méthodologique stricte, sans appréciations subjectives non étayées.', it: 'Espone le evidenze empiriche elaborate con rigore metodologico, senza valutazioni soggettive non sostenute.' },
  'chapter.4.keyMistake': { es: 'Reiterar en el texto descriptivo la totalidad de los guarismos consignados en las tablas. La redacción debe focalizarse en los hallazgos críticos: valores extremos, coeficientes y nivel de significancia estadística (p < 0.05).', en: 'Repeating in prose every figure already in the tables. The text should focus on the critical findings: extreme values, coefficients and statistical significance (p < 0.05).', pt: 'Repetir no texto todos os números já presentes nas tabelas. A redação deve focar nos achados críticos: valores extremos, coeficientes e significância estatística (p < 0,05).', fr: 'Répéter en prose tous les chiffres déjà présents dans les tableaux. Le texte doit se concentrer sur les résultats critiques : valeurs extrêmes, coefficients et significativité (p < 0,05).', it: 'Ripetere nel testo tutti i numeri già presenti nelle tabelle. La stesura deve concentrarsi sui risultati critici: valori estremi, coefficienti e significatività (p < 0,05).' },
  'chapter.4.formulaOrTemplate': { es: 'Regla de Decisión Estadística: Si el p-valor (Significancia asintótica bilateral) es inferior a 0.05, se rechaza la hipótesis nula (H0) y se acepta la hipótesis alterna (H1) con un nivel de confianza del 95%.', en: 'Decision rule: if the p-value (two-tailed asymptotic significance) is below 0.05, reject the null hypothesis (H0) and accept the alternative (H1) at 95% confidence.', pt: 'Regra de decisão: se o valor-p (significância assintótica bilateral) for inferior a 0,05, rejeita-se a hipótese nula (H0) e aceita-se a alternativa (H1) com 95% de confiança.', fr: 'Règle de décision : si la valeur p (significativité asymptotique bilatérale) est inférieure à 0,05, on rejette l\'hypothèse nulle (H0) et on accepte l\'alternative (H1) à 95 % de confiance.', it: 'Regola di decisione: se il valore p (significatività asintotica bilaterale) è inferiore a 0,05, si rifiuta l\'ipotesi nulla (H0) e si accetta l\'alternativa (H1) al 95% di confidenza.' },
  'chapter.4.deliverable.0': { es: 'Análisis descriptivo sociodemográfico de la muestra (distribución de frecuencias y porcentajes)', en: 'Sociodemographic description of the sample (frequency and percentage distribution)', pt: 'Análise descritiva sociodemográfica da amostra (distribuição de frequências e percentuais)', fr: 'Analyse descriptive sociodémographique de l\'échantillon (fréquences et pourcentages)', it: 'Analisi descrittiva sociodemografica del campione (frequenze e percentuali)' },
  'chapter.4.deliverable.1': { es: 'Análisis descriptivo por variables y dimensiones (medidas de tendencia central, dispersión y niveles)', en: 'Descriptive analysis by variable and dimension (central tendency, dispersion and levels)', pt: 'Análise descritiva por variáveis e dimensões (tendência central, dispersão e níveis)', fr: 'Analyse descriptive par variable et dimension (tendance centrale, dispersion et niveaux)', it: 'Analisi descrittiva per variabili e dimensioni (tendenza centrale, dispersione e livelli)' },
  'chapter.4.deliverable.2': { es: 'Prueba de bondad de ajuste y normalidad (Kolmogorov-Smirnov para N > 50, Shapiro-Wilk para N ≤ 50)', en: 'Goodness-of-fit and normality tests (Kolmogorov–Smirnov for N > 50, Shapiro–Wilk for N ≤ 50)', pt: 'Teste de aderência e normalidade (Kolmogorov-Smirnov para N > 50, Shapiro-Wilk para N ≤ 50)', fr: 'Tests d\'adéquation et de normalité (Kolmogorov-Smirnov si N > 50, Shapiro-Wilk si N ≤ 50)', it: 'Test di bontà di adattamento e normalità (Kolmogorov-Smirnov per N > 50, Shapiro-Wilk per N ≤ 50)' },
  'chapter.4.deliverable.3': { es: 'Prueba de hipótesis paramétrica (Pearson, t de Student, ANOVA) o no paramétrica (Spearman, Wilcoxon, Chi-cuadrado)', en: 'Parametric hypothesis tests (Pearson, Student\'s t, ANOVA) or non-parametric (Spearman, Wilcoxon, chi-square)', pt: 'Teste de hipóteses paramétrico (Pearson, t de Student, ANOVA) ou não paramétrico (Spearman, Wilcoxon, qui-quadrado)', fr: 'Tests d\'hypothèses paramétriques (Pearson, t de Student, ANOVA) ou non paramétriques (Spearman, Wilcoxon, khi-deux)', it: 'Test di ipotesi parametrici (Pearson, t di Student, ANOVA) o non parametrici (Spearman, Wilcoxon, chi-quadrato)' },
  'chapter.4.deliverable.4': { es: 'Tablas y figuras elaboradas bajo las directrices estrictas de formato APA 7', en: 'Tables and figures built to strict APA 7 formatting rules', pt: 'Tabelas e figuras elaboradas segundo as diretrizes estritas do formato APA 7', fr: 'Tableaux et figures conformes aux règles strictes du format APA 7', it: 'Tabelle e figure realizzate secondo le regole rigorose del formato APA 7' },
  'chapter.4.check.0': { es: '¿Todas las tablas y figuras cuentan con numeración correlativa, título en cursiva y nota explicativa en formato APA 7?', en: 'Do all tables and figures have sequential numbering, an italic title and an APA 7 note?', pt: 'Todas as tabelas e figuras têm numeração sequencial, título em itálico e nota em APA 7?', fr: 'Tous les tableaux et figures ont-ils une numérotation suivie, un titre en italique et une note APA 7 ?', it: 'Tutte le tabelle e figure hanno numerazione progressiva, titolo in corsivo e nota in APA 7?' },
  'chapter.4.check.1': { es: '¿Se reporta la prueba de normalidad antes de la selección de las pruebas de correlación o comparación?', en: 'Is the normality test reported before choosing the correlation or comparison tests?', pt: 'O teste de normalidade é reportado antes da escolha dos testes de correlação ou comparação?', fr: 'Le test de normalité est-il rapporté avant le choix des tests de corrélation ou de comparaison ?', it: 'Il test di normalità è riportato prima della scelta dei test di correlazione o confronto?' },
  'chapter.4.check.2': { es: '¿Se explicitan los coeficientes estadísticos y sus respectivos niveles de significancia (p-valor)?', en: 'Are the statistical coefficients and their significance levels (p-values) stated?', pt: 'Os coeficientes estatísticos e os respectivos níveis de significância (valor-p) estão explícitos?', fr: 'Les coefficients statistiques et leurs seuils de significativité (valeur p) sont-ils explicités ?', it: 'Sono esplicitati i coefficienti statistici e i relativi livelli di significatività (valore p)?' },
  'chapter.4.check.3': { es: '¿Los resultados responden de manera directa y ordenada a cada uno de los objetivos específicos formulados?', en: 'Do the results answer each specific objective directly and in order?', pt: 'Os resultados respondem de forma direta e ordenada a cada objetivo específico?', fr: 'Les résultats répondent-ils directement et dans l\'ordre à chaque objectif spécifique ?', it: 'I risultati rispondono in modo diretto e ordinato a ciascun obiettivo specifico?' },

  // ----------------------------------------------------------------- Capítulo V
  'chapter.5.title': { es: 'Discusión, Conclusiones & Recomendaciones', en: 'Discussion, Conclusions & Recommendations', pt: 'Discussão, Conclusões & Recomendações', fr: 'Discussion, Conclusions & Recommandations', it: 'Discussione, Conclusioni & Raccomandazioni' },
  'chapter.5.question': { es: '¿Cuál es la interpretación científica de los hallazgos frente a la literatura y qué deducciones se derivan?', en: 'How do the findings read against the literature, and what conclusions follow?', pt: 'Qual é a interpretação científica dos achados frente à literatura e que deduções decorrem?', fr: 'Quelle lecture scientifique des résultats face à la littérature, et quelles déductions en découlent ?', it: 'Qual è la lettura scientifica dei risultati rispetto alla letteratura e quali deduzioni ne derivano?' },
  'chapter.5.purpose': { es: 'Constituye la síntesis analítica de la tesis, en la cual se contrastan los hallazgos empíricos frente al estado del arte documentado en el Capítulo II.', en: 'The analytical synthesis of the thesis, where empirical findings are set against the state of the art documented in Chapter II.', pt: 'É a síntese analítica da tese, na qual os achados empíricos são contrastados com o estado da arte do Capítulo II.', fr: 'La synthèse analytique du mémoire, où les résultats empiriques sont confrontés à l\'état de l\'art du chapitre II.', it: 'È la sintesi analitica della tesi, in cui i risultati empirici sono confrontati con lo stato dell\'arte del Capitolo II.' },
  'chapter.5.keyMistake': { es: 'Redactar las conclusiones como un resumen del marco teórico o una reiteración de cifras estadísticas. Las conclusiones deben formularse como deducciones conceptuales definitivas emanadas de los resultados.', en: 'Writing conclusions as a summary of the theoretical framework or a restatement of figures. Conclusions must be definitive conceptual deductions drawn from the results.', pt: 'Redigir as conclusões como resumo do marco teórico ou repetição de números. As conclusões devem ser deduções conceituais definitivas derivadas dos resultados.', fr: 'Rédiger les conclusions comme un résumé du cadre théorique ou une redite de chiffres. Les conclusions doivent être des déductions conceptuelles définitives issues des résultats.', it: 'Scrivere le conclusioni come riassunto del quadro teorico o ripetizione di cifre. Le conclusioni devono essere deduzioni concettuali definitive tratte dai risultati.' },
  'chapter.5.formulaOrTemplate': { es: 'Estructura del Párrafo de Discusión: El hallazgo empírico [Resultado] concuerda con lo reportado por [Autor (Año)], quien determinó que [Hallazgo antecedente]. Esta coincidencia se fundamenta en [Explicación teórica de la relación].', en: 'Discussion paragraph template: the empirical finding [result] agrees with [author (year)], who found that [prior finding]. This convergence rests on [theoretical explanation of the relationship].', pt: 'Modelo de parágrafo de discussão: o achado empírico [resultado] concorda com [autor (ano)], que determinou que [achado anterior]. Essa convergência fundamenta-se em [explicação teórica].', fr: 'Modèle de paragraphe de discussion : le résultat [résultat] concorde avec [auteur (année)], qui a déterminé que [résultat antérieur]. Cette convergence repose sur [explication théorique].', it: 'Modello di paragrafo di discussione: il risultato [risultato] concorda con [autore (anno)], che ha determinato che [risultato precedente]. Questa convergenza si fonda su [spiegazione teorica].' },
  'chapter.5.deliverable.0': { es: 'Discusión crítica: Contrastación de cada resultado empírico frente a los antecedentes del Capítulo II (convergencias y divergencias)', en: 'Critical discussion: each empirical result set against the prior work of Chapter II (convergences and divergences)', pt: 'Discussão crítica: contraste de cada resultado empírico com os antecedentes do Capítulo II (convergências e divergências)', fr: 'Discussion critique : confrontation de chaque résultat aux antécédents du chapitre II (convergences et divergences)', it: 'Discussione critica: confronto di ogni risultato con gli antecedenti del Capitolo II (convergenze e divergenze)' },
  'chapter.5.deliverable.1': { es: 'Conclusión general vinculada de forma estricta al objetivo general', en: 'A general conclusion tied strictly to the general objective', pt: 'Conclusão geral estritamente vinculada ao objetivo geral', fr: 'Conclusion générale strictement liée à l\'objectif général', it: 'Conclusione generale strettamente legata all\'obiettivo generale' },
  'chapter.5.deliverable.2': { es: 'Conclusiones específicas en correspondencia biunívoca con cada objetivo específico', en: 'Specific conclusions in one-to-one correspondence with each specific objective', pt: 'Conclusões específicas em correspondência unívoca com cada objetivo específico', fr: 'Conclusions spécifiques en correspondance biunivoque avec chaque objectif spécifique', it: 'Conclusioni specifiche in corrispondenza biunivoca con ogni obiettivo specifico' },
  'chapter.5.deliverable.3': { es: 'Aportes teóricos, metodológicos y prácticos consolidados por la investigación', en: 'Theoretical, methodological and practical contributions consolidated by the research', pt: 'Aportes teóricos, metodológicos e práticos consolidados pela pesquisa', fr: 'Apports théoriques, méthodologiques et pratiques consolidés par la recherche', it: 'Contributi teorici, metodologici e pratici consolidati dalla ricerca' },
  'chapter.5.deliverable.4': { es: 'Limitaciones metodológicas identificadas durante la ejecución del estudio', en: 'Methodological limitations identified while carrying out the study', pt: 'Limitações metodológicas identificadas durante a execução do estudo', fr: 'Limites méthodologiques relevées pendant la réalisation de l\'étude', it: 'Limiti metodologici individuati durante l\'esecuzione dello studio' },
  'chapter.5.deliverable.5': { es: 'Recomendaciones fundamentadas dirigidas a actores institucionales o a futuras líneas de investigación', en: 'Grounded recommendations aimed at institutional actors or future lines of research', pt: 'Recomendações fundamentadas dirigidas a atores institucionais ou a futuras linhas de pesquisa', fr: 'Recommandations fondées à l\'intention des acteurs institutionnels ou de futures recherches', it: 'Raccomandazioni fondate rivolte agli attori istituzionali o a future linee di ricerca' },
  'chapter.5.check.0': { es: '¿Cada conclusión responde de manera precisa a un objetivo específico formulado en el Capítulo I?', en: 'Does each conclusion answer precisely one specific objective from Chapter I?', pt: 'Cada conclusão responde com precisão a um objetivo específico do Capítulo I?', fr: 'Chaque conclusion répond-elle précisément à un objectif spécifique du chapitre I ?', it: 'Ogni conclusione risponde con precisione a un obiettivo specifico del Capitolo I?' },
  'chapter.5.check.1': { es: '¿La discusión dialoga explícitamente con los autores citados en el estado del arte del Capítulo II?', en: 'Does the discussion explicitly engage the authors cited in Chapter II?', pt: 'A discussão dialoga explicitamente com os autores citados no Capítulo II?', fr: 'La discussion dialogue-t-elle explicitement avec les auteurs cités au chapitre II ?', it: 'La discussione dialoga esplicitamente con gli autori citati nel Capitolo II?' },
  'chapter.5.check.2': { es: '¿Se explican las divergencias teóricas o metodológicas con base en argumentos científicos sólidos?', en: 'Are theoretical or methodological divergences explained with solid scientific arguments?', pt: 'As divergências teóricas ou metodológicas são explicadas com argumentos científicos sólidos?', fr: 'Les divergences théoriques ou méthodologiques sont-elles expliquées par des arguments scientifiques solides ?', it: 'Le divergenze teoriche o metodologiche sono spiegate con argomenti scientifici solidi?' },
  'chapter.5.check.3': { es: '¿Las recomendaciones se presentan como directrices accionables, viables y delimitadas?', en: 'Are the recommendations presented as actionable, feasible and bounded guidance?', pt: 'As recomendações são apresentadas como diretrizes acionáveis, viáveis e delimitadas?', fr: 'Les recommandations sont-elles présentées comme des directives actionnables, réalisables et délimitées ?', it: 'Le raccomandazioni sono presentate come indicazioni attuabili, fattibili e delimitate?' },
};
