/**
 * Diagnóstico y revisión de avances: textos del módulo DraftReviewWorkbench.
 *
 * Perfiles de diagnóstico, mensajes de validación, guía de entregables,
 * etapas de titulación y retroalimentación automática.
 */

import type { ContentDict } from './types';

export const DRAFT_REVIEW_TRANSLATIONS: ContentDict = {
  // -------------------------------- Vocabulario de severidad (SEVERITY_UI)
  'draft.severity.critica': { es: 'Te lo van a devolver', en: 'They will send it back', pt: 'Vão devolver para você', fr: 'On vous le renverra', it: 'Te lo respingeranno' },
  'draft.severity.alta': { es: 'Importante', en: 'Important', pt: 'Importante', fr: 'Important', it: 'Importante' },
  'draft.severity.media': { es: 'Recomendado', en: 'Recommended', pt: 'Recomendado', fr: 'Recommandé', it: 'Consigliato' },
  'draft.severity.baja': { es: 'Detalle final', en: 'Final detail', pt: 'Detalhe final', fr: 'Détail final', it: 'Dettaglio finale' },

  // -------------------------------- Criterios por área (AREA_CRITERIA, panel de transparencia)
  'draft.areaCriteria.estructura': { es: 'Que existan como encabezado las secciones que el formato pide en esta etapa.', en: 'That the sections this stage\'s format requires exist as headings.', pt: 'Que existam como cabeçalho as seções que o formato exige nesta etapa.', fr: 'Que les sections exigées par le format à ce stade existent comme titres.', it: 'Che esistano come intestazione le sezioni richieste dal formato in questa fase.' },
  'draft.areaCriteria.resumen': { es: 'Extensión de 150 a 250 palabras, palabras clave y su equivalente en inglés.', en: 'Length of 150 to 250 words, keywords and their English equivalent.', pt: 'Extensão de 150 a 250 palavras, palavras-chave e seu equivalente em inglês.', fr: 'Longueur de 150 à 250 mots, mots-clés et leur équivalent en anglais.', it: 'Lunghezza da 150 a 250 parole, parole chiave e il loro equivalente in inglese.' },
  'draft.areaCriteria.objetivos': { es: 'Un objetivo general con verbo en infinitivo y objeto claro, tres específicos sin repetir verbo, y el alcance declarado.', en: 'One general objective with an infinitive verb and a clear object, three specific ones without repeating the verb, and a declared scope.', pt: 'Um objetivo geral com verbo no infinitivo e objeto claro, três específicos sem repetir o verbo, e o alcance declarado.', fr: 'Un objectif général avec un verbe à l\'infinitif et un objet clair, trois objectifs spécifiques sans répéter le verbe, et la portée déclarée.', it: 'Un obiettivo generale con verbo all\'infinito e oggetto chiaro, tre specifici senza ripetere il verbo, e la portata dichiarata.' },
  'draft.areaCriteria.requerimientos': { es: 'Matriz de requerimientos funcionales y no funcionales codificados, con prioridad y métrica verificable.', en: 'Matrix of coded functional and non-functional requirements, with priority and a verifiable metric.', pt: 'Matriz de requisitos funcionais e não funcionais codificados, com prioridade e métrica verificável.', fr: 'Matrice des exigences fonctionnelles et non fonctionnelles codifiées, avec priorité et métrique vérifiable.', it: 'Matrice dei requisiti funzionali e non funzionali codificati, con priorità e metrica verificabile.' },
  'draft.areaCriteria.metodologia': { es: 'Una sola metodología nombrada, justificada, con sus fases, cronograma y riesgos.', en: 'A single named and justified methodology, with its phases, schedule and risks.', pt: 'Uma única metodologia nomeada, justificada, com suas fases, cronograma e riscos.', fr: 'Une seule méthodologie nommée, justifiée, avec ses phases, son calendrier et ses risques.', it: 'Un\'unica metodologia nominata, giustificata, con le sue fasi, cronoprogramma e rischi.' },
  'draft.areaCriteria.diseno': { es: 'Diagramas UML, arquitectura, diccionario de datos, casos de prueba y versiones de las tecnologías.', en: 'UML diagrams, architecture, data dictionary, test cases and technology versions.', pt: 'Diagramas UML, arquitetura, dicionário de dados, casos de teste e versões das tecnologias.', fr: 'Diagrammes UML, architecture, dictionnaire de données, cas de test et versions des technologies.', it: 'Diagrammi UML, architettura, dizionario dei dati, casi di test e versioni delle tecnologie.' },
  'draft.areaCriteria.citas': { es: 'Citas en el texto, referencias en APA 7, correspondencia entre ambas, vigencia y DOI.', en: 'In-text citations, APA 7 references, correspondence between the two, currency and DOI.', pt: 'Citações no texto, referências em APA 7, correspondência entre ambas, atualidade e DOI.', fr: 'Citations dans le texte, références en APA 7, correspondance entre les deux, actualité et DOI.', it: 'Citazioni nel testo, riferimenti in APA 7, corrispondenza tra i due, attualità e DOI.' },
  'draft.areaCriteria.redaccion': { es: 'Tercera persona impersonal, tiempo verbal consistente, conectores y oraciones de largo manejable.', en: 'Impersonal third person, consistent verb tense, connectors and sentences of manageable length.', pt: 'Terceira pessoa impessoal, tempo verbal consistente, conectores e frases de tamanho gerenciável.', fr: 'Troisième personne impersonnelle, temps verbal cohérent, connecteurs et phrases de longueur maîtrisable.', it: 'Terza persona impersonale, tempo verbale coerente, connettori e frasi di lunghezza gestibile.' },
  'draft.areaCriteria.formato': { es: 'Tablas y figuras numeradas con fuente, espaciado limpio e informe de originalidad.', en: 'Numbered tables and figures with their source, clean spacing and an originality report.', pt: 'Tabelas e figuras numeradas com fonte, espaçamento limpo e relatório de originalidade.', fr: 'Tableaux et figures numérotés avec leur source, espacement propre et rapport d\'originalité.', it: 'Tabelle e figure numerate con fonte, spaziatura pulita e rapporto di originalità.' },

  // -------------------------------- Perfiles de diagnóstico (etapas)
  'draft.stage.embryonic': { es: 'Embrionario', en: 'Embryonic', pt: 'Embrionário', fr: 'Embryonnaire', it: 'Embrionale' },
  'draft.stage.formative': { es: 'Formativo', en: 'Formative', pt: 'Formativo', fr: 'Formatif', it: 'Formativo' },
  'draft.stage.maturing': { es: 'En maduración', en: 'Maturing', pt: 'Em maturação', fr: 'En maturation', it: 'In maturazione' },
  'draft.stage.solidified': { es: 'Consolidado', en: 'Solidified', pt: 'Consolidado', fr: 'Consolidé', it: 'Consolidato' },
  'draft.stage.polished': { es: 'Pulido', en: 'Polished', pt: 'Polido', fr: 'Affiné', it: 'Rifinito' },

  // -------------------------------- Tarjetas de etapa (STAGE_PROFILES)
  'draft.stage.avance1.label': { es: 'Avance 1 — Introducción y planteamiento', en: 'Advance 1 — Introduction and problem statement', pt: 'Avanço 1 — Introdução e formulação do problema', fr: 'Jalon 1 — Introduction et énoncé du problème', it: 'Avanzamento 1 — Introduzione e formulazione del problema' },
  'draft.stage.avance1.shortLabel': { es: 'Avance 1', en: 'Advance 1', pt: 'Avanço 1', fr: 'Jalon 1', it: 'Avanzamento 1' },
  'draft.stage.avance1.scope': { es: 'Capítulo 1 completo: descripción del caso, propósito, objetivos, alcance y base conceptual con sus fuentes.', en: 'The full Chapter 1: case description, purpose, objectives, scope and conceptual basis with its sources.', pt: 'Capítulo 1 completo: descrição do caso, propósito, objetivos, alcance e base conceitual com suas fontes.', fr: 'Le chapitre 1 complet : description du cas, objet, objectifs, portée et base conceptuelle avec ses sources.', it: 'Il capitolo 1 completo: descrizione del caso, scopo, obiettivi, portata e base concettuale con le relative fonti.' },
  'draft.stage.avance2.label': { es: 'Avance 2 — Análisis, metodología y diseño', en: 'Advance 2 — Analysis, methodology and design', pt: 'Avanço 2 — Análise, metodologia e desenho', fr: 'Jalon 2 — Analyse, méthodologie et conception', it: 'Avanzamento 2 — Analisi, metodologia e disegno' },
  'draft.stage.avance2.shortLabel': { es: 'Avance 2', en: 'Advance 2', pt: 'Avanço 2', fr: 'Jalon 2', it: 'Avanzamento 2' },
  'draft.stage.avance2.scope': { es: 'Todo lo del Avance 1 más el análisis del caso, la matriz de requerimientos, la metodología elegida y el diseño de la solución.', en: 'Everything from Advance 1 plus the case analysis, the requirements matrix, the chosen methodology and the solution design.', pt: 'Tudo do Avanço 1 mais a análise do caso, a matriz de requisitos, a metodologia escolhida e o desenho da solução.', fr: 'Tout ce qui figure dans le jalon 1, plus l\'analyse du cas, la matrice des exigences, la méthodologie choisie et la conception de la solution.', it: 'Tutto ciò che è nell\'avanzamento 1, più l\'analisi del caso, la matrice dei requisiti, la metodologia scelta e il disegno della soluzione.' },
  'draft.stage.final.label': { es: 'Documento completo — Versión de entrega', en: 'Complete document — Submission version', pt: 'Documento completo — Versão de entrega', fr: 'Document complet — Version de remise', it: 'Documento completo — Versione di consegna' },
  'draft.stage.final.shortLabel': { es: 'Documento completo', en: 'Complete document', pt: 'Documento completo', fr: 'Document complet', it: 'Documento completo' },
  'draft.stage.final.scope': { es: 'El documento íntegro, incluidos resumen, abstract, desarrollo, pruebas, conclusiones, anexos y el informe de originalidad.', en: 'The full document, including summary, abstract, development, tests, conclusions, appendices and the originality report.', pt: 'O documento íntegro, incluindo resumo, abstract, desenvolvimento, testes, conclusões, anexos e o relatório de originalidade.', fr: 'Le document intégral, incluant résumé, abstract, développement, tests, conclusions, annexes et le rapport d\'originalité.', it: 'Il documento integrale, compresi riassunto, abstract, sviluppo, test, conclusioni, allegati e il report di originalità.' },

  // -------------------------------- Guía de entregables por sección
  'draft.guide.title': { es: 'Guía de Entregables por Sección', en: 'Deliverable guide by section', pt: 'Guia de entregáveis por seção', fr: 'Guide des livrables par section', it: 'Guida dei deliverable per sezione' },
  'draft.guide.summary': { es: 'Resumen y abstract', en: 'Summary and abstract', pt: 'Resumo e abstract', fr: 'Résumé et abstract', it: 'Riassunto e abstract' },
  'draft.guide.summary.detail': { es: 'Extensión de 150 a 250 palabras, palabras clave y su equivalente en inglés.', en: 'Length 150–250 words, keywords and their English equivalents.', pt: 'Extensão de 150 a 250 palavras, palavras-chave e equivalentes em inglês.', fr: 'Longueur 150–250 mots, mots-clés et équivalents anglais.', it: 'Lunghezza 150–250 parole, parole chiave e equivalenti inglesi.' },
  'draft.guide.objectives': { es: 'Objetivos', en: 'Objectives', pt: 'Objetivos', fr: 'Objectifs', it: 'Obiettivi' },
  'draft.guide.objectives.detail': { es: 'Un objetivo general con verbo en infinitivo y objeto claro, tres específicos sin repetir verbo, y el alcance declarado.', en: 'One general objective with infinitive verb and clear object, three specific objectives without verb repetition, and declared scope.', pt: 'Um objetivo geral com verbo no infinitivo e objeto claro, três específicos sem repetição de verbo e escopo declarado.', fr: 'Un objectif général avec verbe à l\'infinitif et objet clair, trois objectifs spécifiques sans répétition verbale et périmètre déclaré.', it: 'Un obiettivo generale con verbo all\'infinito e oggetto chiaro, tre specifici senza ripetizione verbale e perimetro dichiarato.' },
  'draft.guide.requirements': { es: 'Requisitos y Matriz', en: 'Requirements and matrix', pt: 'Requisitos e matriz', fr: 'Exigences et matrice', it: 'Requisiti e matrice' },
  'draft.guide.requirements.detail': { es: 'Matriz de requerimientos funcionales y no funcionales codificados, con prioridad y métrica verificable.', en: 'Matrix of functional and non-functional requirements, coded with priority and verifiable metrics.', pt: 'Matriz de requisitos funcionais e não funcionais codificados, com prioridade e métricas verificáveis.', fr: 'Matrice des exigences fonctionnelles et non fonctionnelles codifiées, avec priorité et métriques vérifiables.', it: 'Matrice di requisiti funzionali e non funzionali codificati, con priorità e metriche verificabili.' },
  'draft.guide.methodology': { es: 'Metodología', en: 'Methodology', pt: 'Metodologia', fr: 'Méthodologie', it: 'Metodologia' },
  'draft.guide.methodology.detail': { es: 'Una sola metodología nombrada, justificada, con sus fases, cronograma y riesgos.', en: 'One methodology named and justified, with its phases, schedule and risks.', pt: 'Uma única metodologia nomeada e justificada, com suas fases, cronograma e riscos.', fr: 'Une seule méthodologie nommée et justifiée, avec phases, calendrier et risques.', it: 'Una sola metodologia nominata e giustificata, con fasi, calendario e rischi.' },
  'draft.guide.design': { es: 'Diseño y desarrollo', en: 'Design and development', pt: 'Desenho e desenvolvimento', fr: 'Conception et développement', it: 'Disegno e sviluppo' },
  'draft.guide.design.detail': { es: 'Diagramas UML, arquitectura, diccionario de datos, casos de prueba y versiones de las tecnologías.', en: 'UML diagrams, architecture, data dictionary, test cases and technology versions.', pt: 'Diagramas UML, arquitetura, dicionário de dados, casos de teste e versões de tecnologias.', fr: 'Diagrammes UML, architecture, dictionnaire de données, cas de test et versions technologiques.', it: 'Diagrammi UML, architettura, dizionario dei dati, casi di prova e versioni tecnologiche.' },
  'draft.guide.writing': { es: 'Redacción académica', en: 'Academic writing', pt: 'Escrita acadêmica', fr: 'Rédaction académique', it: 'Scrittura accademica' },

  // -------------------------------- Mensajes de validación
  'draft.error.fileRead': { es: 'No se pudo leer el archivo. Copia el texto y pégalo en el cuadro.', en: 'Could not read the file. Copy the text and paste it in the box.', pt: 'Não foi possível ler o arquivo. Copie o texto e cole na caixa.', fr: 'Impossible de lire le fichier. Copiez le texte et collez-le dans la case.', it: 'Impossibile leggere il file. Copia il testo e incollalo nella casella.' },
  'draft.error.minLength': { es: 'Necesito al menos {count} caracteres para dar un diagnóstico útil. Pega el capítulo completo, no un párrafo suelto.', en: 'I need at least {count} characters to give useful feedback. Paste the whole chapter, not just one paragraph.', pt: 'Preciso de pelo menos {count} caracteres para dar um diagnóstico útil. Cole o capítulo completo, não apenas um parágrafo.', fr: 'J\'ai besoin d\'au moins {count} caractères pour donner un diagnostic utile. Collez le chapitre complet, pas seulement un paragraphe.', it: 'Ho bisogno di almeno {count} caratteri per dare un diagnóstico utile. Incolla il capitolo completo, non solo un paragrafo.' },

  // -------------------------------- Etiquetas de diagnóstico
  'draft.label.formDiagnosis': { es: 'Diagnóstico de forma', en: 'Form diagnosis', pt: 'Diagnóstico de forma', fr: 'Diagnostic de forme', it: 'Diagnosi di forma' },
  'draft.label.readinessLevel': { es: 'Nivel de preparación', en: 'Readiness level', pt: 'Nível de preparação', fr: 'Niveau de préparation', it: 'Livello di preparazione' },
  'draft.label.areasEvaluated': { es: 'Áreas evaluadas:', en: 'Assessed areas:', pt: 'Áreas avaliadas:', fr: 'Domaines évalués :', it: 'Aree valutate:' },
  'draft.label.disclaimer': { es: 'Este diagnóstico revisa forma y estructura, no el fondo científico. La decisión de aprobación es del docente o tutor.', en: 'This diagnosis checks form and structure, not scientific substance. The approval decision is the teacher\'s or advisor\'s.', pt: 'Este diagnóstico verifica forma e estrutura, não o conteúdo científico. A decisão de aprovação é do professor ou orientador.', fr: 'Ce diagnostic examine la forme et la structure, pas le contenu scientifique. La décision d\'approbation revient au professeur ou au directeur.', it: 'Questo diagnóstico esamina forma e struttura, non il contenuto scientifico. La decisione di approvazione è del docente o relatore.' },

  // -------------------------------- Interfaz del módulo
  'draft.module.title': { es: 'Diagnóstico de tu avance 🔎', en: 'Your progress diagnosis 🔎', pt: 'Diagnóstico do seu avanço 🔎', fr: 'Diagnostic de votre progression 🔎', it: 'Diagnosi del tuo progresso 🔎' },
  'draft.module.subtitle': { es: 'Análisis automático de forma y estructura de tu avance de titulación, antes de que lo lea tu docente.', en: 'Automated analysis of your thesis submission\'s form and structure, before your advisor reads it.', pt: 'Análise automática de forma e estrutura do seu avanço, antes que seu orientador o leia.', fr: 'Analyse automatisée de la forme et de la structure de votre jalon avant que votre directeur le lise.', it: 'Analisi automatizzata della forma e struttura del tuo avanço, prima che il relatore lo legga.' },
  'draft.prompt.what': { es: '¿Qué estás entregando?', en: 'What are you submitting?', pt: 'O que você está entregando?', fr: 'Qu\'est-ce que vous soumettez ?', it: 'Cosa stai consegnando?' },
  'draft.prompt.dropFile': { es: 'Arrastra tu archivo aquí o selecciónalo', en: 'Drag your file here or select it', pt: 'Arraste seu arquivo aqui ou selecione-o', fr: 'Faites glisser votre fichier ici ou sélectionnez-le', it: 'Trascina il tuo file qui o selezionalo' },
  'draft.prompt.pasteText': { es: 'copia el texto y pégalo abajo.', en: 'copy the text and paste it below.', pt: 'copie o texto e cole abaixo.', fr: 'copiez le texte et collez-le ci-dessous.', it: 'copia il testo e incollalo sotto.' },
  'draft.prompt.placeholder': { es: 'Pega aquí el texto de tu avance…', en: 'Paste your submission text here…', pt: 'Cole aqui o texto do seu avanço…', fr: 'Collez votre texte ici…', it: 'Incolla qui il testo del tuo avanço…' },
  'draft.source.loaded': { es: 'Recuperado de tu sesión anterior', en: 'Loaded from your last session', pt: 'Recuperado de sua sessão anterior', fr: 'Chargé de votre dernière session', it: 'Caricato dalla sessione precedente' },
  'draft.info.sessionNote': { es: '. Este texto quedó guardado en tu navegador de una sesión previa; si no es el que querías, cámbialo arriba.', en: '. This text was saved from a prior session in your browser; if it\'s not what you want, change it above.', pt: '. Este texto foi salvo em seu navegador de uma sessão anterior; se não é o que você quer, mude-o acima.', fr: '. Ce texte a été sauvegardé de votre navigateur lors d\'une session précédente ; si ce n\'est pas ce que vous voulez, modifiez-le ci-dessus.', it: '. Questo testo è stato salvato dal tuo browser da una sessione precedente; se non è quello che vuoi, cambialo sopra.' },

  // -------------------------------- Resultados y retroalimentación
  'draft.result.notQualified': { es: 'Esto <strong>no es tu calificación</strong>. Es un chequeo automático de forma y estructura sobre lo que el formato exige en esta etapa. El fondo científico de tu trabajo y la decisión de aprobar la tiene tu docente o tutor.', en: 'This is <strong>not your grade</strong>. It\'s an automated check of the form and structure that this stage requires. Scientific substance and approval decisions belong to your teacher or advisor.', pt: 'Isto <strong>não é sua nota</strong>. É uma verificação automática da forma e estrutura exigida nesta etapa. O conteúdo científico e a aprovação são responsabilidade de seu professor ou orientador.', fr: 'Ce n\'est <strong>pas votre note</strong>. C\'est une vérification automatisée de la forme et de la structure requises à cette étape. La substance scientifique et la décision d\'approbation relèvent de votre enseignant ou directeur.', it: 'Questo <strong>non è il tuo voto</strong>. È un controllo automatizzato della forma e struttura richiesta in questa fase. Il contenuto scientifico e la decisione di approvazione spettano al tuo docente o relatore.' },
  'draft.section.strengths': { es: 'Esto ya lo tienes resuelto', en: 'You\'ve already nailed this', pt: 'Isto você já resolveu', fr: 'C\'est déjà réglé', it: 'Questo lo hai già risolto' },
  'draft.section.nextSteps': { es: 'Próximos pasos priorizados por impacto', en: 'Next steps ranked by impact', pt: 'Próximos passos priorizados por impacto', fr: 'Prochaines étapes classées par impact', it: 'Prossimi passi ordinati per impatto' },

  // -------------------------------- Encabezado del módulo (interfaz)
  'draft.module.badge': { es: 'Revisor de borrador', en: 'Draft reviewer', pt: 'Revisor de rascunho', fr: 'Réviseur de brouillon', it: 'Revisore di bozza' },
  'draft.module.tagline': { es: 'Revisa la forma y la estructura de tu documento contra el formato de titulación, antes de que lo lea tu docente.', en: 'Checks your document\'s form and structure against the thesis format, before your advisor reads it.', pt: 'Verifica a forma e a estrutura do seu documento contra o formato de titulação, antes que seu orientador o leia.', fr: 'Vérifie la forme et la structure de votre document par rapport au format du mémoire, avant que votre directeur ne le lise.', it: 'Verifica la forma e la struttura del tuo documento rispetto al formato di tesi, prima che il relatore lo legga.' },
  'draft.badge.local': { es: 'Se procesa en tu navegador', en: 'Processed in your browser', pt: 'Processado no seu navegador', fr: 'Traité dans votre navigateur', it: 'Elaborato nel tuo browser' },
  'draft.prompt.whatHint': { es: 'Esto cambia por completo el resultado. A un Avance 1 no se le exige desarrollo, pruebas ni conclusiones, y evaluarlo como documento terminado da un puntaje bajo que no describe nada real.', en: 'This completely changes the result. Advance 1 is not expected to have development, tests or conclusions, and grading it as a finished document gives a low score that describes nothing real.', pt: 'Isso muda completamente o resultado. Um primeiro avanço não exige desenvolvimento, testes nem conclusões, e avaliá-lo como documento terminado dá uma pontuação baixa que não descreve nada real.', fr: 'Cela change complètement le résultat. Un premier jalon n\'exige ni développement, ni tests, ni conclusions, et l\'évaluer comme un document terminé donne un score bas qui ne décrit rien de réel.', it: 'Questo cambia completamente il risultato. A un primo avanzamento non si richiede sviluppo, test né conclusioni, e valutarlo come documento finito dà un punteggio basso che non descrive nulla di reale.' },
  'draft.step2.title': { es: 'Tu documento', en: 'Your document', pt: 'Seu documento', fr: 'Votre document', it: 'Il tuo documento' },
  'draft.status.reading': { es: 'Leyendo el documento…', en: 'Reading the document…', pt: 'Lendo o documento…', fr: 'Lecture du document…', it: 'Lettura del documento…' },
  'draft.dropzone.prefix': { es: 'Arrastra tu archivo aquí o', en: 'Drag your file here or', pt: 'Arraste seu arquivo aqui ou', fr: 'Faites glisser votre fichier ici ou', it: 'Trascina qui il tuo file oppure' },
  'draft.dropzone.action': { es: 'selecciónalo', en: 'select it', pt: 'selecione-o', fr: 'sélectionnez-le', it: 'selezionalo' },
  'draft.dropzone.formats': { es: 'Formatos aceptados: .docx, .txt. Si tienes PDF, copia el texto y pégalo abajo.', en: 'Accepted formats: .docx, .txt. If you have a PDF, copy the text and paste it below.', pt: 'Formatos aceitos: .docx, .txt. Se tiver PDF, copie o texto e cole abaixo.', fr: 'Formats acceptés : .docx, .txt. Si vous avez un PDF, copiez le texte et collez-le ci-dessous.', it: 'Formati accettati: .docx, .txt. Se hai un PDF, copia il testo e incollalo sotto.' },
  'draft.status.label': { es: 'Texto del borrador', en: 'Draft text', pt: 'Texto do rascunho', fr: 'Texte du brouillon', it: 'Testo della bozza' },
  'draft.status.words': { es: 'palabras', en: 'words', pt: 'palavras', fr: 'mots', it: 'parole' },
  'draft.action.clear': { es: 'Limpiar', en: 'Clear', pt: 'Limpar', fr: 'Effacer', it: 'Cancella' },
  'draft.action.clearTitle': { es: 'Borrar el texto y empezar de nuevo', en: 'Clear the text and start over', pt: 'Apagar o texto e começar de novo', fr: 'Effacer le texte et recommencer', it: 'Cancella il testo e ricomincia' },
  'draft.source.file': { es: 'Archivo:', en: 'File:', pt: 'Arquivo:', fr: 'Fichier :', it: 'File:' },
  'draft.source.pasted': { es: 'Texto pegado', en: 'Pasted text', pt: 'Texto colado', fr: 'Texte collé', it: 'Testo incollato' },
  'draft.source.restoredNote': { es: '. Este texto quedó guardado en tu navegador de una sesión previa; si no es el documento que quieres revisar, pulsa', en: '. This text was saved in your browser from a previous session; if it\'s not the document you want to review, press', pt: '. Este texto foi salvo em seu navegador de uma sessão anterior; se não é o documento que você quer revisar, pressione', fr: '. Ce texte a été enregistré dans votre navigateur lors d\'une session précédente ; si ce n\'est pas le document que vous voulez examiner, appuyez sur', it: '. Questo testo è stato salvato nel tuo browser da una sessione precedente; se non è il documento che vuoi rivedere, premi' },
  'draft.action.analyze': { es: 'Analizar mi', en: 'Analyze my', pt: 'Analisar meu', fr: 'Analyser mon', it: 'Analizza il mio' },
  'draft.action.localNote': { es: 'Tu documento no sale de este navegador.', en: 'Your document never leaves this browser.', pt: 'Seu documento não sai deste navegador.', fr: 'Votre document ne quitte jamais ce navigateur.', it: 'Il tuo documento non lascia mai questo browser.' },
  'draft.score.outOf100': { es: 'de 100', en: 'out of 100', pt: 'de 100', fr: 'sur 100', it: 'su 100' },
  'draft.progress.sectionsRequired': { es: 'Secciones exigidas en esta etapa', en: 'Sections required at this stage', pt: 'Seções exigidas nesta etapa', fr: 'Sections exigées à cette étape', it: 'Sezioni richieste in questa fase' },
  'draft.section.nextStepsHint': { es: 'No intentes arreglar todo a la vez. Estos son los que más mueven tu resultado en esta etapa.', en: 'Don\'t try to fix everything at once. These are the ones that move your result the most at this stage.', pt: 'Não tente consertar tudo de uma vez. Estes são os que mais movem seu resultado nesta etapa.', fr: 'N\'essayez pas de tout corriger à la fois. Voici ceux qui font le plus bouger votre résultat à cette étape.', it: 'Non provare a sistemare tutto insieme. Questi sono quelli che spostano di più il tuo risultato in questa fase.' },
  'draft.section.nextStepsCount': { es: 'Tus próximos {n} pasos', en: 'Your next {n} steps', pt: 'Seus próximos {n} passos', fr: 'Vos {n} prochaines étapes', it: 'I tuoi prossimi {n} passi' },
  'draft.section.orderedByImpact': { es: 'Ordenados por impacto', en: 'Ranked by impact', pt: 'Ordenados por impacto', fr: 'Classés par impact', it: 'Ordinati per impatto' },
  'draft.guidance.loading': { es: 'Cargando la corrección…', en: 'Loading the fix…', pt: 'Carregando a correção…', fr: 'Chargement de la correction…', it: 'Caricamento della correzione…' },
  'draft.guidance.howToFix': { es: 'Cómo corregirlo:', en: 'How to fix it:', pt: 'Como corrigir:', fr: 'Comment le corriger :', it: 'Come correggerlo:' },
  'draft.guidance.error': { es: 'No se pudo cargar la corrección. Recarga la página o escríbeme y te la explico.', en: 'Could not load the fix. Reload the page or message me and I\'ll explain it.', pt: 'Não foi possível carregar a correção. Recarregue a página ou me escreva e eu explico.', fr: 'Impossible de charger la correction. Rechargez la page ou écrivez-moi et je vous l\'explique.', it: 'Impossibile caricare la correzione. Ricarica la pagina o scrivimi e te la spiego.' },
  'draft.section.otherFindings': { es: 'Las otras {n} observaciones', en: 'The other {n} observations', pt: 'As outras {n} observações', fr: 'Les {n} autres observations', it: 'Le altre {n} osservazioni' },
  'draft.section.deferred': { es: 'Todavía no aplica ({n})', en: 'Not applicable yet ({n})', pt: 'Ainda não se aplica ({n})', fr: 'Pas encore applicable ({n})', it: 'Non ancora applicabile ({n})' },
  'draft.action.explainFix': { es: 'Cómo corregirlo — te lo explico', en: 'How to fix it — I\'ll explain', pt: 'Como corrigir — eu explico', fr: 'Comment corriger — je vous explique', it: 'Come correggerlo — te lo spiego' },
  'draft.section.deferredHint': { es: 'Detecté estos puntos, pero corresponden a etapas posteriores. <strong>No restan nada</strong> a tu resultado: los verás aquí cuando cambies la etapa arriba.', en: 'These points were detected, but they belong to later stages. <strong>They don\'t subtract anything</strong> from your result: you\'ll see them here once you change the stage above.', pt: 'Detectei esses pontos, mas correspondem a etapas posteriores. <strong>Não descontam nada</strong> do seu resultado: você os verá aqui quando mudar a etapa acima.', fr: 'Ces points ont été détectés, mais ils correspondent à des étapes ultérieures. <strong>Ils ne retirent rien</strong> à votre résultat : vous les verrez ici en changeant l\'étape ci-dessus.', it: 'Ho rilevato questi punti, ma corrispondono a fasi successive. <strong>Non tolgono nulla</strong> al tuo risultato: li vedrai qui quando cambierai la fase sopra.' },
  'draft.section.scoreBreakdown': { es: 'Cómo se reparte tu puntaje', en: 'How your score breaks down', pt: 'Como sua pontuação se divide', fr: 'Comment votre score se répartit', it: 'Come si ripartisce il tuo punteggio' },
  'draft.section.formatSections': { es: 'Secciones del formato', en: 'Format sections', pt: 'Seções do formato', fr: 'Sections du format', it: 'Sezioni del formato' },
  'draft.label.later': { es: 'Después', en: 'Later', pt: 'Depois', fr: 'Plus tard', it: 'Dopo' },
  'draft.section.scoreOrigin': { es: '¿De dónde sale este puntaje?', en: 'Where does this score come from?', pt: 'De onde vem essa pontuação?', fr: 'D\'où vient ce score ?', it: 'Da dove viene questo punteggio?' },
  'draft.rubric.basis': { es: 'La base es el <strong>formato institucional de titulación</strong> y la estructura que comparten los trabajos ya aprobados de la carrera. Las reglas son deterministas y revisan <strong>solo forma</strong>: si una sección existe, si los objetivos están en infinitivo, si hay correspondencia entre citas y referencias, etcétera. Ninguna regla juzga si tu idea es buena.', en: 'The basis is the <strong>institutional thesis format</strong> and the structure shared by already-approved theses in the program. The rules are deterministic and check <strong>form only</strong>: whether a section exists, whether objectives use the infinitive, whether citations match references, and so on. No rule judges whether your idea is good.', pt: 'A base é o <strong>formato institucional de titulação</strong> e a estrutura compartilhada pelos trabalhos já aprovados do curso. As regras são determinísticas e verificam <strong>apenas forma</strong>: se uma seção existe, se os objetivos estão no infinitivo, se há correspondência entre citações e referências, etc. Nenhuma regra julga se sua ideia é boa.', fr: 'La base est le <strong>format institutionnel du mémoire</strong> et la structure partagée par les travaux déjà approuvés de la filière. Les règles sont déterministes et vérifient <strong>uniquement la forme</strong> : si une section existe, si les objectifs sont à l\'infinitif, si les citations correspondent aux références, etc. Aucune règle ne juge si votre idée est bonne.', it: 'La base è il <strong>formato istituzionale di tesi</strong> e la struttura condivisa dai lavori già approvati del corso. Le regole sono deterministiche e verificano <strong>solo la forma</strong>: se una sezione esiste, se gli obiettivi sono all\'infinito, se c\'è corrispondenza tra citazioni e riferimenti, ecc. Nessuna regola giudica se la tua idea è buona.' },
  'draft.rubric.weightsFor': { es: 'Pesos para', en: 'Weights for', pt: 'Pesos para', fr: 'Poids pour', it: 'Pesi per' },
  'draft.rubric.sumTo100': { es: '(suman 100)', en: '(add up to 100)', pt: '(somam 100)', fr: '(totalisent 100)', it: '(sommano a 100)' },
  'draft.rubric.worth': { es: 'vale', en: 'worth', pt: 'vale', fr: 'vaut', it: 'vale' },
  'draft.rubric.pts': { es: 'pts', en: 'pts', pt: 'pts', fr: 'pts', it: 'pt' },
  'draft.rubric.discountTitle': { es: 'Cuánto descuenta cada observación', en: 'How much each finding discounts', pt: 'Quanto cada observação desconta', fr: 'Combien chaque observation déduit', it: 'Quanto sottrae ogni osservazione' },
  'draft.rubric.discountNote': { es: 'Cada área parte de su puntaje completo y baja según el peso de las observaciones que acumule, con un tope: ningún área cae por debajo de cero ni arrastra a las demás.', en: 'Each area starts at its full score and drops according to the weight of the findings it accumulates, with a floor: no area falls below zero or drags the others down.', pt: 'Cada área parte de sua pontuação completa e diminui conforme o peso das observações acumuladas, com um limite: nenhuma área cai abaixo de zero nem arrasta as demais.', fr: 'Chaque domaine part de son score complet et baisse selon le poids des observations accumulées, avec un plancher : aucun domaine ne descend sous zéro ni n\'entraîne les autres.', it: 'Ogni area parte dal punteggio completo e scende in base al peso delle osservazioni accumulate, con un limite: nessuna area scende sotto zero né trascina le altre.' },
  'draft.rubric.notReviewed': { es: 'Lo que este diagnóstico <strong>no</strong> revisa: la calidad de tu propuesta, la validez de tus resultados, el porcentaje de similitud y los criterios propios de tu docente. Un 100 aquí no significa aprobación.', en: 'What this diagnosis does <strong>not</strong> check: the quality of your proposal, the validity of your results, the similarity percentage, and your advisor\'s own criteria. A 100 here does not mean approval.', pt: 'O que este diagnóstico <strong>não</strong> verifica: a qualidade da sua proposta, a validade dos seus resultados, o percentual de similaridade e os critérios próprios do seu orientador. Um 100 aqui não significa aprovação.', fr: 'Ce que ce diagnostic <strong>ne</strong> vérifie <strong>pas</strong> : la qualité de votre proposition, la validité de vos résultats, le pourcentage de similarité et les critères propres à votre directeur. Un 100 ici ne signifie pas l\'approbation.', it: 'Cosa questo diagnóstico <strong>non</strong> verifica: la qualità della tua proposta, la validità dei tuoi risultati, la percentuale di similarità e i criteri propri del tuo relatore. Un 100 qui non significa approvazione.' },
  'draft.closing.text': { es: 'Este diagnóstico revisa forma y estructura. <strong>La decisión sobre tu trabajo la toma tu docente o tutor.</strong> Si quieres que revisemos juntos algún punto en específico, escríbeme.', en: 'This diagnosis checks form and structure. <strong>The decision about your work belongs to your teacher or advisor.</strong> If you\'d like to review a specific point together, message me.', pt: 'Este diagnóstico verifica forma e estrutura. <strong>A decisão sobre seu trabalho é do seu professor ou orientador.</strong> Se quiser revisarmos juntos algum ponto específico, me escreva.', fr: 'Ce diagnostic vérifie la forme et la structure. <strong>La décision concernant votre travail revient à votre enseignant ou directeur.</strong> Si vous voulez qu\'on revoie un point précis ensemble, écrivez-moi.', it: 'Questo diagnóstico verifica forma e struttura. <strong>La decisione sul tuo lavoro spetta al tuo docente o relatore.</strong> Se vuoi che rivediamo insieme un punto specifico, scrivimi.' },
  'draft.action.copyDiagnosis': { es: 'Copiar diagnóstico', en: 'Copy diagnosis', pt: 'Copiar diagnóstico', fr: 'Copier le diagnostic', it: 'Copia diagnosi' },
  'draft.action.copied': { es: 'Copiado', en: 'Copied', pt: 'Copiado', fr: 'Copié', it: 'Copiato' },
  'draft.action.writeMe': { es: 'Escríbeme', en: 'Message me', pt: 'Me escreva', fr: 'Écrivez-moi', it: 'Scrivimi' },

  // -------------------------------- Resumen copiado al portapapeles
  'draft.summary.headerPrefix': { es: 'Diagnóstico de forma —', en: 'Form diagnosis —', pt: 'Diagnóstico de forma —', fr: 'Diagnostic de forme —', it: 'Diagnosi di forma —' },
  'draft.summary.sectionsPresent': { es: 'Secciones presentes:', en: 'Sections present:', pt: 'Seções presentes:', fr: 'Sections présentes :', it: 'Sezioni presenti:' },
  'draft.summary.sectionsRequiredAt': { es: 'exigidas en esta etapa.', en: 'required at this stage.', pt: 'exigidas nesta etapa.', fr: 'exigées à cette étape.', it: 'richieste in questa fase.' },
  'draft.summary.observationsCount': { es: 'Observaciones que cuentan en esta etapa', en: 'Observations that count at this stage', pt: 'Observações que contam nesta etapa', fr: 'Observations qui comptent à cette étape', it: 'Osservazioni che contano in questa fase' },
};
