/**
 * Interfaz del módulo TopicFeasibilityCalculator ("Viabilidad").
 *
 * Cubre el texto de navegación, encabezados, etiquetas, botones y las 9
 * opciones de los 3 criterios de viabilidad (CRITERION_1/2/3_OPTIONS: tag,
 * label, description, advisorTip — claves `feasibility.criterion<N>.<id>.<campo>`,
 * con `<id>` tomado de `StepOption.id` en el componente). Las plantillas
 * generadoras de título/pregunta/objetivo/hipótesis de `ThesisProject.ts`
 * quedan deliberadamente sin traducir: el título de titulación en sí se
 * redacta en español sin importar el idioma de la interfaz, porque así se
 * presenta ante cualquier universidad del Ecuador.
 *
 * Claves `feasibility.<sección>.<campo>`.
 */

import type { ContentDict } from './types';

export const FEASIBILITY_TRANSLATIONS: ContentDict = {
  // -------------------------------- Encabezado
  'feasibility.header.badge': { es: 'Metodología de Investigación para Estudiantes Universitarios del Ecuador', en: 'Research methodology for Ecuadorian university students', pt: 'Metodologia de pesquisa para estudantes universitários do Equador', fr: 'Méthodologie de recherche pour les étudiants universitaires équatoriens', it: 'Metodologia di ricerca per studenti universitari ecuadoriani' },
  'feasibility.header.title': { es: 'Simulador de Viabilidad & Matriz de Consistencia 🎓', en: 'Feasibility Simulator & Consistency Matrix 🎓', pt: 'Simulador de Viabilidade & Matriz de Consistência 🎓', fr: 'Simulateur de faisabilité & Matrice de cohérence 🎓', it: 'Simulatore di fattibilità & Matrice di coerenza 🎓' },
  'feasibility.header.subtitle': { es: 'Evaluación diagnóstica basada en los criterios de titulación comunes a las universidades del Ecuador. Contrasta siempre el resultado con el formato de titulación de tu universidad.', en: 'Diagnostic assessment based on the graduation criteria common to Ecuadorian universities. Always check the result against your own university\'s thesis format.', pt: 'Avaliação diagnóstica baseada nos critérios de titulação comuns às universidades do Equador. Sempre compare o resultado com o formato de titulação da sua universidade.', fr: 'Évaluation diagnostique basée sur les critères de fin d\'études communs aux universités équatoriennes. Comparez toujours le résultat avec le format de votre université.', it: 'Valutazione diagnostica basata sui criteri di laurea comuni alle università ecuadoriane. Confronta sempre il risultato con il formato di laurea della tua università.' },
  'feasibility.mode.stepByStep': { es: 'Paso a Paso', en: 'Step by step', pt: 'Passo a passo', fr: 'Étape par étape', it: 'Passo dopo passo' },
  'feasibility.mode.fullView': { es: 'Vista Completa', en: 'Full view', pt: 'Visão completa', fr: 'Vue complète', it: 'Vista completa' },

  // -------------------------------- Navegación de pasos
  'feasibility.step.1.title': { es: 'Acceso a Datos', en: 'Data access', pt: 'Acesso a dados', fr: 'Accès aux données', it: 'Accesso ai dati' },
  'feasibility.step.1.short': { es: 'Acceso', en: 'Access', pt: 'Acesso', fr: 'Accès', it: 'Accesso' },
  'feasibility.step.2.title': { es: 'Literatura Scopus', en: 'Scopus literature', pt: 'Literatura Scopus', fr: 'Littérature Scopus', it: 'Letteratura Scopus' },
  'feasibility.step.2.short': { es: 'Scopus', en: 'Scopus', pt: 'Scopus', fr: 'Scopus', it: 'Scopus' },
  'feasibility.step.3.title': { es: 'Relevancia Práctica', en: 'Practical relevance', pt: 'Relevância prática', fr: 'Pertinence pratique', it: 'Rilevanza pratica' },
  'feasibility.step.3.short': { es: 'Aporte', en: 'Contribution', pt: 'Contribuição', fr: 'Apport', it: 'Contributo' },
  'feasibility.step.4.title': { es: 'Matriz de Variables', en: 'Variable matrix', pt: 'Matriz de variáveis', fr: 'Matrice de variables', it: 'Matrice delle variabili' },
  'feasibility.step.4.short': { es: 'Variables', en: 'Variables', pt: 'Variáveis', fr: 'Variables', it: 'Variabili' },
  'feasibility.step.5.title': { es: 'Dictamen Metodológico', en: 'Methodological verdict', pt: 'Parecer metodológico', fr: 'Avis méthodologique', it: 'Parere metodologico' },
  'feasibility.step.5.short': { es: 'Dictamen', en: 'Verdict', pt: 'Parecer', fr: 'Avis', it: 'Parere' },
  'feasibility.progress.step': { es: 'Paso', en: 'Step', pt: 'Passo', fr: 'Étape', it: 'Passo' },
  'feasibility.progress.of5': { es: 'de 5', en: 'of 5', pt: 'de 5', fr: 'sur 5', it: 'di 5' },
  'feasibility.progress.score': { es: 'Puntaje acumulado:', en: 'Accumulated score:', pt: 'Pontuação acumulada:', fr: 'Score cumulé :', it: 'Punteggio accumulato:' },
  'feasibility.nav.previous': { es: 'Anterior', en: 'Previous', pt: 'Anterior', fr: 'Précédent', it: 'Precedente' },
  'feasibility.recommendation.label': { es: 'Recomendación metodológica:', en: 'Methodological recommendation:', pt: 'Recomendação metodológica:', fr: 'Recommandation méthodologique :', it: 'Raccomandazione metodologica:' },

  // -------------------------------- Paso 1
  'feasibility.step1.badge': { es: 'Criterio 1 de 3 (Máx. 35 puntos)', en: 'Criterion 1 of 3 (Max. 35 points)', pt: 'Critério 1 de 3 (Máx. 35 pontos)', fr: 'Critère 1 sur 3 (Max. 35 points)', it: 'Criterio 1 di 3 (Max. 35 punti)' },
  'feasibility.step1.title': { es: 'Acceso a Datos y Unidad de Análisis', en: 'Data access and unit of analysis', pt: 'Acesso a dados e unidade de análise', fr: 'Accès aux données et unité d\'analyse', it: 'Accesso ai dati e unità di analisi' },
  'feasibility.step1.question': { es: '¿El investigador cuenta con autorización formal demostrable para encuestar, entrevistar o acceder a los registros empíricos?', en: 'Does the researcher have demonstrable formal authorization to survey, interview, or access the empirical records?', pt: 'O pesquisador possui autorização formal comprovável para aplicar questionários, entrevistas ou acessar os registros empíricos?', fr: 'Le chercheur dispose-t-il d\'une autorisation formelle démontrable pour interroger, interviewer ou accéder aux données empiriques ?', it: 'Il ricercatore dispone di un\'autorizzazione formale dimostrabile per somministrare questionari, interviste o accedere ai dati empirici?' },
  'feasibility.step1.helper': { es: 'Selecciona el nivel de acceso para proceder al Criterio 2', en: 'Select the access level to proceed to Criterion 2', pt: 'Selecione o nível de acesso para prosseguir ao Critério 2', fr: 'Sélectionnez le niveau d\'accès pour passer au critère 2', it: 'Seleziona il livello di accesso per procedere al Criterio 2' },
  'feasibility.nav.next1': { es: 'Siguiente: Literatura Indexada', en: 'Next: Indexed literature', pt: 'Próximo: Literatura indexada', fr: 'Suivant : Littérature indexée', it: 'Successivo: Letteratura indicizzata' },

  // -------------------------------- Paso 2
  'feasibility.step2.badge': { es: 'Criterio 2 de 3 (Máx. 35 puntos)', en: 'Criterion 2 of 3 (Max. 35 points)', pt: 'Critério 2 de 3 (Máx. 35 pontos)', fr: 'Critère 2 sur 3 (Max. 35 points)', it: 'Criterio 2 di 3 (Max. 35 punti)' },
  'feasibility.step2.title': { es: 'Literatura Científica Indexada Contemporánea (< 5 años)', en: 'Contemporary indexed scientific literature (< 5 years)', pt: 'Literatura científica indexada contemporânea (< 5 anos)', fr: 'Littérature scientifique indexée contemporaine (< 5 ans)', it: 'Letteratura scientifica indicizzata contemporanea (< 5 anni)' },
  'feasibility.step2.question': { es: '¿Se identifican artículos en bases de datos indexadas (Scopus, Web of Science, Latindex) sobre las variables en estudio?', en: 'Are there articles in indexed databases (Scopus, Web of Science, Latindex) about the variables under study?', pt: 'Identificam-se artigos em bases de dados indexadas (Scopus, Web of Science, Latindex) sobre as variáveis em estudo?', fr: 'Trouve-t-on des articles dans des bases de données indexées (Scopus, Web of Science, Latindex) sur les variables étudiées ?', it: 'Si individuano articoli in banche dati indicizzate (Scopus, Web of Science, Latindex) sulle variabili in studio?' },
  'feasibility.nav.next2': { es: 'Siguiente: Relevancia Práctica', en: 'Next: Practical relevance', pt: 'Próximo: Relevância prática', fr: 'Suivant : Pertinence pratique', it: 'Successivo: Rilevanza pratica' },

  // -------------------------------- Paso 3
  'feasibility.step3.badge': { es: 'Criterio 3 de 3 (Máx. 30 puntos)', en: 'Criterion 3 of 3 (Max. 30 points)', pt: 'Critério 3 de 3 (Máx. 30 pontos)', fr: 'Critère 3 sur 3 (Max. 30 points)', it: 'Criterio 3 di 3 (Max. 30 punti)' },
  'feasibility.step3.title': { es: 'Relevancia Práctica y Aporte a la Toma de Decisiones', en: 'Practical relevance and contribution to decision-making', pt: 'Relevância prática e contribuição para a tomada de decisão', fr: 'Pertinence pratique et apport à la prise de décision', it: 'Rilevanza pratica e contributo al processo decisionale' },
  'feasibility.step3.question': { es: '¿Los resultados aportarán a resolver una problemática tangible del entorno y respaldar la toma de decisiones organizacionales?', en: 'Will the results help solve a tangible problem in the environment and support organizational decision-making?', pt: 'Os resultados contribuirão para resolver um problema tangível do entorno e apoiar a tomada de decisão organizacional?', fr: 'Les résultats contribueront-ils à résoudre un problème tangible et à appuyer la prise de décision organisationnelle ?', it: 'I risultati contribuiranno a risolvere un problema tangibile del contesto e a supportare le decisioni organizzative?' },
  'feasibility.nav.next3': { es: 'Siguiente: Matriz de Variables', en: 'Next: Variable matrix', pt: 'Próximo: Matriz de variáveis', fr: 'Suivant : Matrice de variables', it: 'Successivo: Matrice delle variabili' },

  // -------------------------------- Paso 4 (Matriz)
  'feasibility.step4.badge': { es: 'Paso 4: Formulación Metodológica', en: 'Step 4: Methodological formulation', pt: 'Passo 4: Formulação metodológica', fr: 'Étape 4 : Formulation méthodologique', it: 'Passo 4: Formulazione metodologica' },
  'feasibility.step4.title': { es: 'Matriz de Consistencia & Formulación de Variables', en: 'Consistency matrix & variable formulation', pt: 'Matriz de consistência & formulação de variáveis', fr: 'Matrice de cohérence & formulation des variables', it: 'Matrice di coerenza & formulazione delle variabili' },
  'feasibility.step4.subtitle': { es: 'Ingresa los componentes clave. El modelo orientado a objetos genera el Título Institucional, la Pregunta de Investigación, el Objetivo SMART y la Hipótesis en cascada.', en: 'Enter the key components. The object-oriented model generates the institutional title, research question, SMART objective and cascading hypothesis.', pt: 'Insira os componentes-chave. O modelo orientado a objetos gera o título institucional, a pergunta de pesquisa, o objetivo SMART e a hipótese em cascata.', fr: 'Saisissez les éléments clés. Le modèle orienté objet génère le titre institutionnel, la question de recherche, l\'objectif SMART et l\'hypothèse en cascade.', it: 'Inserisci le componenti chiave. Il modello orientato agli oggetti genera il titolo istituzionale, la domanda di ricerca, l\'obiettivo SMART e l\'ipotesi a cascata.' },
  'feasibility.step4.approachLabel': { es: 'Enfoque de tu proyecto (según tu carrera)', en: 'Your project\'s approach (based on your major)', pt: 'Enfoque do seu projeto (conforme seu curso)', fr: 'Approche de votre projet (selon votre filière)', it: 'Approccio del tuo progetto (in base al tuo corso)' },
  'feasibility.step4.structurePrefix': { es: 'Estructura del título:', en: 'Title structure:', pt: 'Estrutura do título:', fr: 'Structure du titre :', it: 'Struttura del titolo:' },
  'feasibility.step4.contextLabel': { es: 'Lugar y año', en: 'Place and year', pt: 'Local e ano', fr: 'Lieu et année', it: 'Luogo e anno' },
  'feasibility.step4.contextOptional': { es: '(el año es opcional)', en: '(the year is optional)', pt: '(o ano é opcional)', fr: '(l\'année est facultative)', it: '(l\'anno è facoltativo)' },
  'feasibility.step4.contextHint': { es: 'No todos los formatos de titulación exigen el año. Si tu carrera no lo pide, escribe solo el lugar (ej: "de la provincia del Guayas") y bórralo del ejemplo.', en: 'Not every thesis format requires the year. If your program doesn\'t ask for it, write only the place (e.g. "from Guayas province") and delete it from the example.', pt: 'Nem todo formato de titulação exige o ano. Se o seu curso não pedir, escreva apenas o local (ex: "da província de Guayas") e apague-o do exemplo.', fr: 'Tous les formats de mémoire n\'exigent pas l\'année. Si votre filière ne l\'exige pas, indiquez seulement le lieu (ex : « de la province de Guayas ») et supprimez-la de l\'exemple.', it: 'Non tutti i formati di tesi richiedono l\'anno. Se il tuo corso non lo richiede, scrivi solo il luogo (es. "della provincia di Guayas") ed eliminalo dall\'esempio.' },
  'feasibility.outputs.title': { es: 'Generación en Cascada', en: 'Cascading generation', pt: 'Geração em cascata', fr: 'Génération en cascade', it: 'Generazione a cascata' },
  'feasibility.outputs.copyTitle': { es: 'Copiar Título', en: 'Copy title', pt: 'Copiar título', fr: 'Copier le titre', it: 'Copia titolo' },
  'feasibility.outputs.copied': { es: '¡Copiado!', en: 'Copied!', pt: 'Copiado!', fr: 'Copié !', it: 'Copiato!' },
  'feasibility.outputs.formalTitleLabel': { es: 'Título Formal de Titulación:', en: 'Formal thesis title:', pt: 'Título formal de titulação:', fr: 'Titre formel du mémoire :', it: 'Titolo formale della tesi:' },
  'feasibility.outputs.questionLabel': { es: 'Pregunta General del Problema (Cap. 1)', en: 'General problem question (Ch. 1)', pt: 'Pergunta geral do problema (Cap. 1)', fr: 'Question générale du problème (Chap. 1)', it: 'Domanda generale del problema (Cap. 1)' },
  'feasibility.outputs.objectiveLabel': { es: 'Objetivo General (SMART)', en: 'General objective (SMART)', pt: 'Objetivo geral (SMART)', fr: 'Objectif général (SMART)', it: 'Obiettivo generale (SMART)' },
  'feasibility.outputs.specificsLabel': { es: 'Objetivos Específicos', en: 'Specific objectives', pt: 'Objetivos específicos', fr: 'Objectifs spécifiques', it: 'Obiettivi specifici' },
  'feasibility.outputs.auditLabel': { es: 'Auditoría de Redacción', en: 'Writing audit', pt: 'Auditoria de redação', fr: 'Audit de rédaction', it: 'Audit di scrittura' },
  'feasibility.nav.next4': { es: 'Generar Dictamen Metodológico', en: 'Generate methodological verdict', pt: 'Gerar parecer metodológico', fr: 'Générer l\'avis méthodologique', it: 'Genera il parere metodologico' },

  // -------------------------------- Paso 5 (Dictamen)
  'feasibility.step5.badge': { es: 'DICTAMEN TÉCNICO METODOLÓGICO', en: 'TECHNICAL METHODOLOGICAL VERDICT', pt: 'PARECER TÉCNICO METODOLÓGICO', fr: 'AVIS TECHNIQUE MÉTHODOLOGIQUE', it: 'PARERE TECNICO METODOLOGICO' },
  'feasibility.step5.finalScore': { es: 'Puntaje Final', en: 'Final score', pt: 'Pontuação final', fr: 'Score final', it: 'Punteggio finale' },
  'feasibility.step5.breakdown1': { es: '1. Acceso a Datos', en: '1. Data access', pt: '1. Acesso a dados', fr: '1. Accès aux données', it: '1. Accesso ai dati' },
  'feasibility.step5.breakdown2': { es: '2. Literatura Scopus', en: '2. Scopus literature', pt: '2. Literatura Scopus', fr: '2. Littérature Scopus', it: '2. Letteratura Scopus' },
  'feasibility.step5.breakdown3': { es: '3. Relevancia Práctica', en: '3. Practical relevance', pt: '3. Relevância prática', fr: '3. Pertinence pratique', it: '3. Rilevanza pratica' },
  'feasibility.step5.adviceTitle': { es: 'Dictamen & Recomendaciones para el Investigador:', en: 'Verdict & recommendations for the researcher:', pt: 'Parecer & recomendações para o pesquisador:', fr: 'Avis et recommandations pour le chercheur :', it: 'Parere e raccomandazioni per il ricercatore:' },
  'feasibility.step5.summaryTitle': { es: 'Resumen de la Matriz de Consistencia para el Plan:', en: 'Consistency matrix summary for the plan:', pt: 'Resumo da matriz de consistência para o plano:', fr: 'Résumé de la matrice de cohérence pour le plan :', it: 'Riepilogo della matrice di coerenza per il piano:' },
  'feasibility.step5.titleLabel': { es: 'Título:', en: 'Title:', pt: 'Título:', fr: 'Titre :', it: 'Titolo:' },
  'feasibility.step5.questionLabel': { es: 'Pregunta:', en: 'Question:', pt: 'Pergunta:', fr: 'Question :', it: 'Domanda:' },
  'feasibility.step5.objectiveLabel': { es: 'Objetivo General:', en: 'General objective:', pt: 'Objetivo geral:', fr: 'Objectif général :', it: 'Obiettivo generale:' },
  'feasibility.step5.copyMatrix': { es: 'Copiar Matriz Completa', en: 'Copy full matrix', pt: 'Copiar matriz completa', fr: 'Copier la matrice complète', it: 'Copia matrice completa' },
  'feasibility.step5.copiedMatrix': { es: '¡Matriz Copiada!', en: 'Matrix copied!', pt: 'Matriz copiada!', fr: 'Matrice copiée !', it: 'Matrice copiata!' },
  'feasibility.step5.reevaluate': { es: 'Reevaluar Criterios', en: 'Re-evaluate criteria', pt: 'Reavaliar critérios', fr: 'Réévaluer les critères', it: 'Rivaluta i criteri' },
  'feasibility.step5.helpTitle': { es: '¿Te ayudo a revisar este resultado?', en: 'Want help reviewing this result?', pt: 'Quer ajuda para revisar este resultado?', fr: 'Besoin d\'aide pour examiner ce résultat ?', it: 'Vuoi aiuto per rivedere questo risultato?' },
  'feasibility.step5.helpBody': { es: 'Si quieres que te ayude con el planteamiento antes de presentarlo, escríbeme y lo vemos.', en: 'If you\'d like help with your proposal before submitting it, message me and we\'ll go over it.', pt: 'Se quiser ajuda com a proposta antes de apresentá-la, me escreva e vemos juntos.', fr: 'Si vous voulez de l\'aide sur votre proposition avant de la soumettre, écrivez-moi et on la revoit ensemble.', it: 'Se vuoi aiuto con la proposta prima di presentarla, scrivimi e la rivediamo insieme.' },
  'feasibility.step5.whatsapp': { es: 'Consultar en WhatsApp', en: 'Ask on WhatsApp', pt: 'Consultar no WhatsApp', fr: 'Contacter sur WhatsApp', it: 'Contatta su WhatsApp' },
  'feasibility.whatsapp.message': { es: '¡Hola! Realicé la evaluación de viabilidad en el portal Tesis Ecuador. Mi tema es: "{title}" con puntaje {score}/100 ({level}). Quisiera que me ayudes con el desarrollo de mi proyecto de titulación.', en: 'Hi! I completed the feasibility assessment on the Tesis Ecuador portal. My topic is: "{title}" with a score of {score}/100 ({level}). I\'d like your help developing my thesis project.', pt: 'Olá! Fiz a avaliação de viabilidade no portal Tesis Ecuador. Meu tema é: "{title}" com pontuação {score}/100 ({level}). Gostaria da sua ajuda para desenvolver meu projeto de titulação.', fr: 'Bonjour ! J\'ai réalisé l\'évaluation de faisabilité sur le portail Tesis Ecuador. Mon sujet est : « {title} » avec un score de {score}/100 ({level}). J\'aimerais votre aide pour développer mon projet de mémoire.', it: 'Ciao! Ho completato la valutazione di fattibilità sul portale Tesis Ecuador. Il mio argomento è: "{title}" con punteggio {score}/100 ({level}). Vorrei il tuo aiuto per sviluppare il mio progetto di tesi.' },

  // -------------------------------- Vista completa
  'feasibility.full.section1Title': { es: '1. Criterios de Viabilidad Institucional', en: '1. Institutional feasibility criteria', pt: '1. Critérios de viabilidade institucional', fr: '1. Critères de faisabilité institutionnelle', it: '1. Criteri di fattibilità istituzionale' },
  'feasibility.full.totalLabel': { es: 'Total:', en: 'Total:', pt: 'Total:', fr: 'Total :', it: 'Totale:' },
  'feasibility.full.q1Label': { es: '1. Acceso a Datos y Unidad de Análisis:', en: '1. Data access and unit of analysis:', pt: '1. Acesso a dados e unidade de análise:', fr: '1. Accès aux données et unité d\'analyse :', it: '1. Accesso ai dati e unità di analisi:' },
  'feasibility.full.q2Label': { es: '2. Literatura Científica Indexada (< 5 años):', en: '2. Indexed scientific literature (< 5 years):', pt: '2. Literatura científica indexada (< 5 anos):', fr: '2. Littérature scientifique indexée (< 5 ans) :', it: '2. Letteratura scientifica indicizzata (< 5 anni):' },
  'feasibility.full.q3Label': { es: '3. Relevancia Práctica & Aporte:', en: '3. Practical relevance & contribution:', pt: '3. Relevância prática & contribuição:', fr: '3. Pertinence pratique et apport :', it: '3. Rilevanza pratica e contributo:' },
  'feasibility.full.section2Title': { es: '2. Sintetizador de Matriz en Cascada', en: '2. Cascading matrix synthesizer', pt: '2. Sintetizador de matriz em cascata', fr: '2. Synthétiseur de matrice en cascade', it: '2. Sintetizzatore di matrice a cascata' },
  'feasibility.full.backToStep': { es: 'Volver a Modo Paso a Paso', en: 'Back to step-by-step mode', pt: 'Voltar ao modo passo a passo', fr: 'Retour au mode étape par étape', it: 'Torna alla modalità passo dopo passo' },
  'feasibility.full.projectTypeLabel': { es: 'Tipo de proyecto:', en: 'Project type:', pt: 'Tipo de projeto:', fr: 'Type de projet :', it: 'Tipo di progetto:' },
  'feasibility.full.titleOutputLabel': { es: 'Título Académico Formal', en: 'Formal academic title', pt: 'Título acadêmico formal', fr: 'Titre académique formel', it: 'Titolo accademico formale' },
  'feasibility.full.copy': { es: 'Copiar', en: 'Copy', pt: 'Copiar', fr: 'Copier', it: 'Copia' },
  'feasibility.full.copied': { es: '¡Copiado!', en: 'Copied!', pt: 'Copiado!', fr: 'Copié !', it: 'Copiato!' },
  'feasibility.full.questionLabel': { es: 'Pregunta General:', en: 'General question:', pt: 'Pergunta geral:', fr: 'Question générale :', it: 'Domanda generale:' },
  'feasibility.full.objectiveLabel': { es: 'Objetivo General:', en: 'General objective:', pt: 'Objetivo geral:', fr: 'Objectif général :', it: 'Obiettivo generale:' },
  'feasibility.full.copyMatrixFull': { es: 'Copiar Matriz de Consistencia Completa', en: 'Copy full consistency matrix', pt: 'Copiar matriz de consistência completa', fr: 'Copier la matrice de cohérence complète', it: 'Copia la matrice di coerenza completa' },
  'feasibility.full.copiedMatrixFull': { es: '¡Matriz Copiada al Portapapeles!', en: 'Matrix copied to clipboard!', pt: 'Matriz copiada para a área de transferência!', fr: 'Matrice copiée dans le presse-papiers !', it: 'Matrice copiata negli appunti!' },

  // -------------------------------- Criterio 1: Acceso a Datos (CRITERION_1_OPTIONS)
  'feasibility.criterion1.c1-optimal.tag': { es: 'Óptimo (+35 pts)', en: 'Optimal (+35 pts)', pt: 'Ótimo (+35 pts)', fr: 'Optimal (+35 pts)', it: 'Ottimale (+35 pt)' },
  'feasibility.criterion1.c1-optimal.label': { es: 'Acceso Directo y Autorización Formal Garantizada', en: 'Direct access with guaranteed formal authorization', pt: 'Acesso direto e autorização formal garantida', fr: 'Accès direct et autorisation formelle garantie', it: 'Accesso diretto e autorizzazione formale garantita' },
  'feasibility.criterion1.c1-optimal.description': { es: 'El investigador cuenta con permiso formal escrito, vinculación laboral en la entidad o convenios institucionales para aplicar cuestionarios y entrevistas sin restricciones de acceso.', en: 'The researcher holds written formal permission, an employment link with the entity, or institutional agreements to apply questionnaires and interviews without access restrictions.', pt: 'O pesquisador possui permissão formal por escrito, vínculo empregatício com a entidade ou convênios institucionais para aplicar questionários e entrevistas sem restrições de acesso.', fr: 'Le chercheur dispose d\'une autorisation formelle écrite, d\'un lien d\'emploi avec l\'entité ou d\'accords institutionnels permettant d\'appliquer questionnaires et entretiens sans restriction d\'accès.', it: 'Il ricercatore dispone di un permesso formale scritto, di un rapporto di lavoro con l\'ente o di convenzioni istituzionali per applicare questionari e interviste senza restrizioni di accesso.' },
  'feasibility.criterion1.c1-optimal.advisorTip': { es: 'Ideal para titulación directa. Permite levantar la muestra en el Capítulo 3 con solvencia.', en: 'Ideal for a direct thesis path. Lets you gather the sample for Chapter 3 with confidence.', pt: 'Ideal para titulação direta. Permite levantar a amostra do Capítulo 3 com solidez.', fr: 'Idéal pour une soutenance directe. Permet de constituer l\'échantillon du chapitre 3 en toute confiance.', it: 'Ideale per una laurea diretta. Consente di raccogliere il campione del Capitolo 3 con solidità.' },

  'feasibility.criterion1.c1-moderate.tag': { es: 'Moderado (+20 pts)', en: 'Moderate (+20 pts)', pt: 'Moderado (+20 pts)', fr: 'Modéré (+20 pts)', it: 'Moderato (+20 pt)' },
  'feasibility.criterion1.c1-moderate.label': { es: 'Factible pero Requiere Trámite Administrativo u Oficio', en: 'Feasible, but requires an administrative process or official letter', pt: 'Viável, mas requer trâmite administrativo ou ofício', fr: 'Faisable mais nécessite une démarche administrative ou une lettre officielle', it: 'Fattibile ma richiede una pratica amministrativa o una lettera ufficiale' },
  'feasibility.criterion1.c1-moderate.description': { es: 'El acceso a la muestra es factible, pero depende de la emisión y aceptación de oficios formales tramitados por la facultad o decanato hacia la entidad receptora.', en: 'Access to the sample is feasible, but depends on formal letters issued and accepted by the faculty or dean\'s office toward the receiving entity.', pt: 'O acesso à amostra é viável, mas depende da emissão e aceitação de ofícios formais tramitados pela faculdade ou decanato junto à entidade receptora.', fr: 'L\'accès à l\'échantillon est possible, mais dépend de l\'émission et de l\'acceptation de lettres officielles traitées par la faculté ou le décanat auprès de l\'entité d\'accueil.', it: 'L\'accesso al campione è fattibile, ma dipende dall\'emissione e dall\'accettazione di lettere formali gestite dalla facoltà o dal decanato presso l\'ente ricevente.' },
  'feasibility.criterion1.c1-moderate.advisorTip': { es: 'Se aconseja gestionar la carta de auspicio académico desde las primeras semanas del Avance 1.', en: 'It is advisable to request the academic sponsorship letter from the first weeks of Advance 1.', pt: 'Recomenda-se solicitar a carta de auspício acadêmico já nas primeiras semanas do Avanço 1.', fr: 'Il est conseillé de demander la lettre de parrainage académique dès les premières semaines du jalon 1.', it: 'Si consiglia di richiedere la lettera di patrocinio accademico fin dalle prime settimane dell\'Avanzamento 1.' },

  'feasibility.criterion1.c1-critical.tag': { es: 'Crítico (0 pts)', en: 'Critical (0 pts)', pt: 'Crítico (0 pts)', fr: 'Critique (0 pt)', it: 'Critico (0 pt)' },
  'feasibility.criterion1.c1-critical.label': { es: 'Sin Acceso Confirmado o Muestra con Alta Incertidumbre', en: 'No confirmed access, or a sample with high uncertainty', pt: 'Sem acesso confirmado ou amostra com alta incerteza', fr: 'Aucun accès confirmé ou échantillon très incertain', it: 'Nessun accesso confermato o campione ad alta incertezza' },
  'feasibility.criterion1.c1-critical.description': { es: 'No se dispone de vinculación directa con la unidad de análisis o los datos requeridos tienen carácter reservado. Existe alto riesgo de paralización del proyecto.', en: 'There is no direct link with the unit of analysis, or the required data is restricted. There is a high risk the project will stall.', pt: 'Não há vínculo direto com a unidade de análise ou os dados requeridos têm caráter reservado. Há alto risco de paralisação do projeto.', fr: 'Il n\'y a pas de lien direct avec l\'unité d\'analyse ou les données requises sont confidentielles. Le risque d\'arrêt du projet est élevé.', it: 'Non esiste un legame diretto con l\'unità di analisi o i dati richiesti sono riservati. Esiste un rischio elevato che il progetto si blocchi.' },
  'feasibility.criterion1.c1-critical.advisorTip': { es: 'Si no es factible medir a los sujetos de estudio, el perfil no se sostiene por más sólido que sea el tema.', en: 'If it is not feasible to measure the study subjects, the proposal does not hold up, no matter how solid the topic is.', pt: 'Se não for viável medir os sujeitos de estudo, o perfil não se sustenta por mais sólido que seja o tema.', fr: 'Si mesurer les sujets d\'étude n\'est pas faisable, le projet ne tient pas, aussi solide que soit le sujet.', it: 'Se non è fattibile misurare i soggetti di studio, il profilo non regge, per quanto solido sia il tema.' },

  // -------------------------------- Criterio 2: Literatura Científica (CRITERION_2_OPTIONS)
  'feasibility.criterion2.c2-optimal.tag': { es: 'Óptimo (+35 pts)', en: 'Optimal (+35 pts)', pt: 'Ótimo (+35 pts)', fr: 'Optimal (+35 pts)', it: 'Ottimale (+35 pt)' },
  'feasibility.criterion2.c2-optimal.label': { es: 'Abundante Literatura Indexada Contemporánea (Scopus / WoS / Latindex)', en: 'Abundant contemporary indexed literature (Scopus / WoS / Latindex)', pt: 'Literatura indexada contemporânea abundante (Scopus / WoS / Latindex)', fr: 'Littérature indexée contemporaine abondante (Scopus / WoS / Latindex)', it: 'Abbondante letteratura indicizzata contemporanea (Scopus / WoS / Latindex)' },
  'feasibility.criterion2.c2-optimal.description': { es: 'Se identifican antecedentes científicos arbitrados publicados en los últimos 5 años (2021-2026) que abordan las variables y sus dimensiones empíricas.', en: 'Peer-reviewed scientific background published in the last 5 years (2021-2026) is identified, addressing the variables and their empirical dimensions.', pt: 'Identificam-se antecedentes científicos arbitrados publicados nos últimos 5 anos (2021-2026) que abordam as variáveis e suas dimensões empíricas.', fr: 'Des antécédents scientifiques évalués par les pairs, publiés au cours des 5 dernières années (2021-2026), sont identifiés et abordent les variables et leurs dimensions empiriques.', it: 'Si individuano precedenti scientifici sottoposti a revisione paritaria, pubblicati negli ultimi 5 anni (2021-2026), che trattano le variabili e le loro dimensioni empiriche.' },
  'feasibility.criterion2.c2-optimal.advisorTip': { es: 'El Capítulo 2 (Marco Teórico y Estado del Arte) se cimentará con máxima solidez científica.', en: 'Chapter 2 (Theoretical framework and state of the art) will be built on maximum scientific solidity.', pt: 'O Capítulo 2 (Marco Teórico e Estado da Arte) se sustentará com a máxima solidez científica.', fr: 'Le chapitre 2 (cadre théorique et état de l\'art) reposera sur une solidité scientifique maximale.', it: 'Il Capitolo 2 (Quadro teorico e stato dell\'arte) si baserà sulla massima solidità scientifica.' },

  'feasibility.criterion2.c2-moderate.tag': { es: 'Moderado (+15 pts)', en: 'Moderate (+15 pts)', pt: 'Moderado (+15 pts)', fr: 'Modéré (+15 pts)', it: 'Moderato (+15 pt)' },
  'feasibility.criterion2.c2-moderate.label': { es: 'Literatura Científica Limitada o Predominio de Repositorios Locales', en: 'Limited scientific literature, or a predominance of local repositories', pt: 'Literatura científica limitada ou predomínio de repositórios locais', fr: 'Littérature scientifique limitée ou prédominance de dépôts locaux', it: 'Letteratura scientifica limitata o predominanza di repository locali' },
  'feasibility.criterion2.c2-moderate.description': { es: 'Se hallan menos de 8 artículos de impacto o la mayor parte de referencias corresponde a tesis no publicadas en revistas indexadas.', en: 'Fewer than 8 high-impact articles are found, or most references are theses not published in indexed journals.', pt: 'Encontram-se menos de 8 artigos de impacto ou a maior parte das referências corresponde a teses não publicadas em revistas indexadas.', fr: 'Moins de 8 articles à fort impact sont trouvés, ou la plupart des références proviennent de thèses non publiées dans des revues indexées.', it: 'Si trovano meno di 8 articoli di impatto o la maggior parte dei riferimenti proviene da tesi non pubblicate su riviste indicizzate.' },
  'feasibility.criterion2.c2-moderate.advisorTip': { es: 'Ampliar los términos booleanos al inglés en Scopus para captar la literatura internacional.', en: 'Extend the Boolean search terms into English in Scopus to capture international literature.', pt: 'Ampliar os termos booleanos para o inglês no Scopus para captar a literatura internacional.', fr: 'Élargissez les termes booléens à l\'anglais dans Scopus pour capter la littérature internationale.', it: 'Amplia i termini booleani in inglese su Scopus per intercettare la letteratura internazionale.' },

  'feasibility.criterion2.c2-critical.tag': { es: 'Crítico (0 pts)', en: 'Critical (0 pts)', pt: 'Crítico (0 pts)', fr: 'Critique (0 pt)', it: 'Critico (0 pt)' },
  'feasibility.criterion2.c2-critical.label': { es: 'Escasa o Nula Producción Científica Indexada', en: 'Scarce or nonexistent indexed scientific output', pt: 'Escassa ou nula produção científica indexada', fr: 'Production scientifique indexée rare ou inexistante', it: 'Produzione scientifica indicizzata scarsa o inesistente' },
  'feasibility.criterion2.c2-critical.description': { es: 'El constructo no se encuentra tipificado internacionalmente o se carece de instrumentos psicométricos validados para operacionalizar las variables.', en: 'The construct is not internationally recognized, or there are no validated psychometric instruments to operationalize the variables.', pt: 'O construto não está tipificado internacionalmente ou faltam instrumentos psicométricos validados para operacionalizar as variáveis.', fr: 'Le construit n\'est pas reconnu internationalement, ou il manque d\'instruments psychométriques validés pour opérationnaliser les variables.', it: 'Il costrutto non è riconosciuto a livello internazionale o mancano strumenti psicometrici validati per operazionalizzare le variabili.' },
  'feasibility.criterion2.c2-critical.advisorTip': { es: 'Se recomienda redefinir las variables hacia conceptos consolidados en la literatura científica.', en: 'It is recommended to redefine the variables toward concepts already established in the scientific literature.', pt: 'Recomenda-se redefinir as variáveis para conceitos já consolidados na literatura científica.', fr: 'Il est recommandé de redéfinir les variables vers des concepts déjà établis dans la littérature scientifique.', it: 'Si raccomanda di ridefinire le variabili verso concetti già consolidati nella letteratura scientifica.' },

  // -------------------------------- Criterio 3: Relevancia Práctica (CRITERION_3_OPTIONS)
  'feasibility.criterion3.c3-optimal.tag': { es: 'Óptimo (+30 pts)', en: 'Optimal (+30 pts)', pt: 'Ótimo (+30 pts)', fr: 'Optimal (+30 pts)', it: 'Ottimale (+30 pt)' },
  'feasibility.criterion3.c3-optimal.label': { es: 'Alta Relevancia Social, Empresarial o Académica en el Entorno', en: 'High social, business, or academic relevance in the setting', pt: 'Alta relevância social, empresarial ou acadêmica no ambiente', fr: 'Grande pertinence sociale, entrepreneuriale ou académique dans le contexte', it: 'Alta rilevanza sociale, aziendale o accademica nel contesto' },
  'feasibility.criterion3.c3-optimal.description': { es: 'Los resultados permitirán resolver un nudo crítico de gestión, aportar a las líneas de investigación de tu universidad y beneficiar al tejido productivo o comunitario.', en: 'The results will help resolve a critical management issue, contribute to your university\'s research lines, and benefit the productive or community fabric.', pt: 'Os resultados permitirão resolver um nó crítico de gestão, contribuir com as linhas de pesquisa da sua universidade e beneficiar o tecido produtivo ou comunitário.', fr: 'Les résultats permettront de résoudre un nœud critique de gestion, de contribuer aux axes de recherche de votre université et de bénéficier au tissu productif ou communautaire.', it: 'I risultati permetteranno di risolvere un nodo critico di gestione, di contribuire alle linee di ricerca della tua università e di beneficiare il tessuto produttivo o comunitario.' },
  'feasibility.criterion3.c3-optimal.advisorTip': { es: 'Garantiza una justificación robusta en el Capítulo 1, con impacto en la toma de decisiones.', en: 'Guarantees a robust justification in Chapter 1, with an impact on decision-making.', pt: 'Garante uma justificativa robusta no Capítulo 1, com impacto na tomada de decisões.', fr: 'Garantit une justification solide au chapitre 1, avec un impact sur la prise de décision.', it: 'Garantisce una giustificazione solida nel Capitolo 1, con impatto sul processo decisionale.' },

  'feasibility.criterion3.c3-moderate.tag': { es: 'Moderado (+15 pts)', en: 'Moderate (+15 pts)', pt: 'Moderado (+15 pts)', fr: 'Modéré (+15 pts)', it: 'Moderato (+15 pt)' },
  'feasibility.criterion3.c3-moderate.label': { es: 'Relevancia Local Acotada o Aporte Principalmente Teórico', en: 'Narrow local relevance, or a mostly theoretical contribution', pt: 'Relevância local restrita ou contribuição principalmente teórica', fr: 'Pertinence locale restreinte ou apport principalement théorique', it: 'Rilevanza locale limitata o contributo principalmente teorico' },
  'feasibility.criterion3.c3-moderate.description': { es: 'El impacto se circunscribe a un ámbito muy restringido y los beneficiarios directos no se encuentran definidos con claridad empírica.', en: 'The impact is confined to a very narrow scope, and the direct beneficiaries are not clearly defined empirically.', pt: 'O impacto se restringe a um âmbito muito limitado e os beneficiários diretos não estão definidos com clareza empírica.', fr: 'L\'impact se limite à un cadre très restreint et les bénéficiaires directs ne sont pas clairement définis empiriquement.', it: 'L\'impatto è circoscritto a un ambito molto ristretto e i beneficiari diretti non sono definiti con chiarezza empirica.' },
  'feasibility.criterion3.c3-moderate.advisorTip': { es: 'Conectar la investigación con los Objetivos de Desarrollo Sostenible y con las líneas de investigación de tu universidad.', en: 'Connect the research with the Sustainable Development Goals and with your university\'s research lines.', pt: 'Conectar a pesquisa com os Objetivos de Desenvolvimento Sustentável e com as linhas de pesquisa da sua universidade.', fr: 'Reliez la recherche aux objectifs de développement durable et aux axes de recherche de votre université.', it: 'Collega la ricerca agli Obiettivi di Sviluppo Sostenibile e alle linee di ricerca della tua università.' },

  'feasibility.criterion3.c3-critical.tag': { es: 'Crítico (0 pts)', en: 'Critical (0 pts)', pt: 'Crítico (0 pts)', fr: 'Critique (0 pt)', it: 'Critico (0 pt)' },
  'feasibility.criterion3.c3-critical.label': { es: 'Baja Trascendencia Práctica o Tema Saturado sin Enfoque Novedoso', en: 'Low practical significance, or a saturated topic without a novel angle', pt: 'Baixa transcendência prática ou tema saturado sem enfoque inovador', fr: 'Faible portée pratique ou sujet saturé sans angle novateur', it: 'Bassa rilevanza pratica o tema saturo senza un approccio innovativo' },
  'feasibility.criterion3.c3-critical.description': { es: 'La temática ha sido abordada de forma recurrente sin aportar una perspectiva metodológica o contextual innovadora.', en: 'The topic has been addressed repeatedly without contributing an innovative methodological or contextual perspective.', pt: 'A temática foi abordada de forma recorrente sem trazer uma perspectiva metodológica ou contextual inovadora.', fr: 'Le sujet a été traité de façon récurrente sans apporter de perspective méthodologique ou contextuelle innovante.', it: 'Il tema è stato affrontato ripetutamente senza offrire una prospettiva metodologica o contestuale innovativa.' },
  'feasibility.criterion3.c3-critical.advisorTip': { es: 'Incorporar una variable emergente o focalizarse en un nicho productivo específico de la región.', en: 'Incorporate an emerging variable or focus on a specific productive niche in the region.', pt: 'Incorporar uma variável emergente ou focar em um nicho produtivo específico da região.', fr: 'Intégrez une variable émergente ou concentrez-vous sur un créneau productif spécifique de la région.', it: 'Incorpora una variabile emergente o concentrati su una nicchia produttiva specifica della regione.' },
};
