/**
 * Interfaz de los módulos de trabajo.
 *
 * Encabezados, etiquetas y botones de Software & Toolbox, Videoteca, Los 5
 * Capítulos, APA 7 y Scopus & Booleanos, más los avisos de confirmación de
 * cuenta. Es texto de interfaz, no catálogo: vive aquí por volumen, para no
 * hacer inmanejable `translations.ts`.
 */

import type { ContentDict } from './types';

export const MODULE_UI_TRANSLATIONS: ContentDict = {
  // ---------------------------------------------- confirmación de cuenta
  'auth.verifySent': { es: 'Cuenta creada. Te enviamos un enlace de confirmación a tu correo: ábrelo para poder entrar.', en: 'Account created. We sent a confirmation link to your email — open it to sign in.', pt: 'Conta criada. Enviamos um link de confirmação para o seu e-mail: abra-o para entrar.', fr: 'Compte créé. Nous avons envoyé un lien de confirmation à votre adresse : ouvrez-le pour vous connecter.', it: 'Account creato. Ti abbiamo inviato un link di conferma via email: aprilo per accedere.' },
  'auth.verifyOpenLink': { es: 'Abrir el enlace de confirmación', en: 'Open the confirmation link', pt: 'Abrir o link de confirmação', fr: 'Ouvrir le lien de confirmation', it: 'Apri il link di conferma' },
  'auth.verifyResend': { es: 'Reenviar el correo de confirmación', en: 'Resend the confirmation email', pt: 'Reenviar o e-mail de confirmação', fr: 'Renvoyer le courriel de confirmation', it: 'Invia di nuovo l\'email di conferma' },
  'auth.verifyResent': { es: 'Enviado. Revisa tu bandeja y la carpeta de correo no deseado.', en: 'Sent. Check your inbox and your spam folder.', pt: 'Enviado. Confira a caixa de entrada e o spam.', fr: 'Envoyé. Vérifiez votre boîte de réception et vos indésirables.', it: 'Inviato. Controlla la posta in arrivo e lo spam.' },
  'auth.signupClosed': { es: 'El registro con correo y contraseña está cerrado en este portal. Entra con Google o con GitHub.', en: 'Email and password sign-up is closed on this portal. Sign in with Google or GitHub.', pt: 'O cadastro com e-mail e senha está fechado neste portal. Entre com Google ou GitHub.', fr: 'L\'inscription par courriel et mot de passe est fermée sur ce portail. Connectez-vous avec Google ou GitHub.', it: 'La registrazione con email e password è chiusa su questo portale. Accedi con Google o GitHub.' },

  // ------------------------------------------------- Software & Toolbox
  'toolbox.badge': { es: 'Ecosistema de Software', en: 'Software ecosystem', pt: 'Ecossistema de software', fr: 'Écosystème logiciel', it: 'Ecosistema software' },
  'toolbox.tagline': { es: 'Ahorra semanas de trabajo', en: 'Saves weeks of work', pt: 'Poupa semanas de trabalho', fr: 'Fait gagner des semaines de travail', it: 'Fa risparmiare settimane di lavoro' },
  'toolbox.title': { es: 'El "Toolbox" del Tesista: Software Recomendado 💻', en: 'The researcher\'s toolbox: recommended software 💻', pt: 'A caixa de ferramentas do pesquisador: software recomendado 💻', fr: 'La boîte à outils du chercheur : logiciels recommandés 💻', it: 'La cassetta degli attrezzi del tesista: software consigliato 💻' },
  'toolbox.subtitle': { es: 'Herramientas oficiales y probadas para recuperar literatura en Scopus, automatizar citas en APA 7 con Zotero y pulir tu redacción académica.', en: 'Official, proven tools to retrieve literature in Scopus, automate APA 7 citations with Zotero and polish your academic writing.', pt: 'Ferramentas oficiais e testadas para recuperar literatura no Scopus, automatizar citações em APA 7 com o Zotero e polir a sua escrita acadêmica.', fr: 'Des outils officiels et éprouvés pour trouver la littérature dans Scopus, automatiser les citations APA 7 avec Zotero et affiner votre écriture.', it: 'Strumenti ufficiali e collaudati per recuperare letteratura su Scopus, automatizzare le citazioni APA 7 con Zotero e rifinire la scrittura accademica.' },
  'toolbox.benefit': { es: 'Beneficio Directo para tu Tesis', en: 'Direct benefit for your thesis', pt: 'Benefício direto para a sua tese', fr: 'Bénéfice direct pour votre mémoire', it: 'Vantaggio diretto per la tua tesi' },
  'toolbox.openSite': { es: 'Abrir Web', en: 'Open site', pt: 'Abrir site', fr: 'Ouvrir le site', it: 'Apri il sito' },
  'toolbox.ethicsTitle': { es: 'Ética Académica & Protección Anti-Turnitin', en: 'Academic ethics & plagiarism protection', pt: 'Ética acadêmica & proteção antiplágio', fr: 'Éthique académique & protection antiplagiat', it: 'Etica accademica & protezione antiplagio' },
  'toolbox.ethicsIntro': { es: 'Usa este software para explorar literatura, estructurar ideas y organizar tus citas.', en: 'Use this software to explore the literature, structure ideas and organise your citations.', pt: 'Use este software para explorar literatura, estruturar ideias e organizar as suas citações.', fr: 'Utilisez ces logiciels pour explorer la littérature, structurer vos idées et organiser vos citations.', it: 'Usa questo software per esplorare la letteratura, strutturare le idee e organizzare le citazioni.' },
  'toolbox.ethicsWarning': { es: 'Nunca le pidas a una IA generativa que invente citas o redacte capítulos completos', en: 'Never ask a generative AI to invent citations or write entire chapters', pt: 'Nunca peça a uma IA generativa que invente citações ou escreva capítulos inteiros', fr: 'Ne demandez jamais à une IA générative d\'inventer des citations ou de rédiger des chapitres entiers', it: 'Non chiedere mai a un\'IA generativa di inventare citazioni o scrivere interi capitoli' },
  'toolbox.ethicsRest': { es: ': las IA alucinan DOIs inexistentes que los revisores detectan de inmediato. Toda afirmación debe estar anclada a un artículo real verificado en Scopus o Web of Science.', en: ': AI models hallucinate DOIs that do not exist, and reviewers spot them at once. Every claim must rest on a real article verified in Scopus or Web of Science.', pt: ': as IA alucinam DOIs inexistentes que os revisores detectam de imediato. Toda afirmação deve estar ancorada num artigo real verificado no Scopus ou Web of Science.', fr: ' : les IA hallucinent des DOI inexistants que les relecteurs repèrent aussitôt. Toute affirmation doit reposer sur un article réel vérifié dans Scopus ou Web of Science.', it: ': le IA allucinano DOI inesistenti che i revisori individuano subito. Ogni affermazione deve poggiare su un articolo reale verificato su Scopus o Web of Science.' },

  // -------------------------------------------------------- Videoteca
  'videos.badge': { es: 'Videoteca guiada', en: 'Guided video library', pt: 'Videoteca guiada', fr: 'Vidéothèque guidée', it: 'Videoteca guidata' },
  'videos.title': { es: 'Aprende viendo: rutas de video por etapa 🎬', en: 'Learn by watching: video tracks by stage 🎬', pt: 'Aprenda vendo: trilhas de vídeo por etapa 🎬', fr: 'Apprendre en regardant : parcours vidéo par étape 🎬', it: 'Impara guardando: percorsi video per fase 🎬' },
  'videos.watch': { es: 'Ver', en: 'Watch', pt: 'Ver', fr: 'Voir', it: 'Guarda' },
  'videos.transparency': { es: 'Cada tarjeta abre YouTube con los términos exactos del tema en lugar de un video fijo. Así el material que ves siempre está vigente y ningún enlace queda roto cuando un canal borra o privatiza un video.', en: 'Each card opens YouTube with the exact search terms for the topic instead of a fixed video. That way the material is always current and no link breaks when a channel deletes or hides a video.', pt: 'Cada cartão abre o YouTube com os termos exatos do tema em vez de um vídeo fixo. Assim o material está sempre atualizado e nenhum link quebra quando um canal apaga ou torna privado um vídeo.', fr: 'Chaque carte ouvre YouTube avec les termes exacts du sujet plutôt qu\'une vidéo figée. Le contenu reste à jour et aucun lien ne casse quand une chaîne supprime ou masque une vidéo.', it: 'Ogni scheda apre YouTube con i termini esatti dell\'argomento invece di un video fisso. Così il materiale è sempre aggiornato e nessun link si rompe quando un canale elimina o rende privato un video.' },

  // -------------------------------------------------- Los 5 capítulos
  'chapters.badge': { es: 'Estructura Metodológica', en: 'Methodological structure', pt: 'Estrutura metodológica', fr: 'Structure méthodologique', it: 'Struttura metodologica' },
  'chapters.tagline': { es: 'Sistematización Capitular', en: 'Chapter-by-chapter breakdown', pt: 'Sistematização por capítulos', fr: 'Systématisation par chapitre', it: 'Sistematizzazione per capitoli' },
  'chapters.title': { es: 'Estructura Canónica: Los 5 Capítulos de la Tesis 🏛️', en: 'Canonical structure: the five chapters of a thesis 🏛️', pt: 'Estrutura canônica: os 5 capítulos da tese 🏛️', fr: 'Structure canonique : les cinq chapitres du mémoire 🏛️', it: 'Struttura canonica: i cinque capitoli della tesi 🏛️' },
  'chapters.subtitle': { es: 'Cada sección responde a un objetivo epistemológico determinado. La concatenación lógica entre capítulos es lo que sostiene la consistencia del documento final.', en: 'Each section answers a specific epistemological purpose. The logical chain between chapters is what holds the final document together.', pt: 'Cada seção responde a um objetivo epistemológico determinado. O encadeamento lógico entre capítulos é o que sustenta a consistência do documento final.', fr: 'Chaque section répond à un objectif épistémologique précis. C\'est l\'enchaînement logique entre chapitres qui assure la cohérence du document.', it: 'Ogni sezione risponde a un obiettivo epistemologico preciso. È il concatenamento logico fra capitoli a sostenere la coerenza del documento finale.' },
  'chapters.step.0': { es: 'Planteamiento & Problema', en: 'Framing & problem', pt: 'Formulação & problema', fr: 'Problématique', it: 'Impostazione & problema' },
  'chapters.step.1': { es: 'Estado del Arte & Teoría', en: 'State of the art & theory', pt: 'Estado da arte & teoria', fr: 'État de l\'art & théorie', it: 'Stato dell\'arte & teoria' },
  'chapters.step.2': { es: 'Diseño & Metodología', en: 'Design & methodology', pt: 'Desenho & metodologia', fr: 'Design & méthodologie', it: 'Disegno & metodologia' },
  'chapters.step.3': { es: 'Análisis & Resultados', en: 'Analysis & results', pt: 'Análise & resultados', fr: 'Analyse & résultats', it: 'Analisi & risultati' },
  'chapters.step.4': { es: 'Discusión & Conclusiones', en: 'Discussion & conclusions', pt: 'Discussão & conclusões', fr: 'Discussion & conclusions', it: 'Discussione & conclusioni' },
  'chapters.guideLabel': { es: 'Guía Metodológica de Titulación', en: 'Methodological graduation guide', pt: 'Guia metodológico de titulação', fr: 'Guide méthodologique de diplomation', it: 'Guida metodologica alla laurea' },
  'chapters.keyQuestion': { es: 'Pregunta clave a responder', en: 'Key question to answer', pt: 'Pergunta-chave a responder', fr: 'Question clé à traiter', it: 'Domanda chiave a cui rispondere' },
  'chapters.copySummary': { es: 'Copiar Resumen', en: 'Copy summary', pt: 'Copiar resumo', fr: 'Copier le résumé', it: 'Copia il riassunto' },
  'chapters.purpose': { es: 'Propósito', en: 'Purpose', pt: 'Propósito', fr: 'Objet', it: 'Scopo' },
  'chapters.template': { es: 'Plantilla o Regla de Oro', en: 'Template or golden rule', pt: 'Modelo ou regra de ouro', fr: 'Modèle ou règle d\'or', it: 'Modello o regola d\'oro' },
  'chapters.mistake': { es: 'Error Fatal Más Frecuente', en: 'Most common fatal mistake', pt: 'Erro fatal mais frequente', fr: 'Erreur fatale la plus fréquente', it: 'Errore fatale più frequente' },
  'chapters.deliverables': { es: 'Entregables Obligatorios', en: 'Required deliverables', pt: 'Entregáveis obrigatórios', fr: 'Livrables obligatoires', it: 'Elaborati obbligatori' },
  'chapters.checklist': { es: 'Checklist de Aprobación', en: 'Approval checklist', pt: 'Checklist de aprovação', fr: 'Liste de contrôle', it: 'Lista di controllo' },

  // ------------------------------------------------------------ APA 7
  'apa.badge': { es: 'Normas APA 7ª Edición', en: 'APA 7th edition', pt: 'Normas APA 7ª edição', fr: 'Normes APA 7e édition', it: 'Norme APA 7ª edizione' },
  'apa.tagline': { es: 'Normalización Bibliográfica', en: 'Bibliographic standardisation', pt: 'Normalização bibliográfica', fr: 'Normalisation bibliographique', it: 'Normalizzazione bibliografica' },
  'apa.title': { es: 'Simulador de Citación en Texto & Referencias Bibliográficas APA 7 📑', en: 'In-text citation and reference-list simulator, APA 7 📑', pt: 'Simulador de citação no texto & referências APA 7 📑', fr: 'Simulateur de citation dans le texte & références APA 7 📑', it: 'Simulatore di citazione nel testo & riferimenti APA 7 📑' },
  'apa.subtitle': { es: 'Estandarización formal de citas parentéticas, narrativas y en bloque según APA 7, con la aplicación sistemática de la regla et al. y la integración con gestores bibliográficos como Zotero y Mendeley.', en: 'Formal standardisation of parenthetical, narrative and block citations under APA 7, with the et al. rule applied systematically and integration with reference managers such as Zotero and Mendeley.', pt: 'Padronização formal de citações parentéticas, narrativas e em bloco segundo a APA 7, com a regra do et al. aplicada sistematicamente e integração com gestores como Zotero e Mendeley.', fr: 'Normalisation formelle des citations parenthétiques, narratives et en bloc selon APA 7, avec application systématique de la règle et al. et intégration aux gestionnaires comme Zotero et Mendeley.', it: 'Standardizzazione formale delle citazioni parentetiche, narrative e in blocco secondo APA 7, con applicazione sistematica della regola et al. e integrazione con gestori come Zotero e Mendeley.' },
  'apa.settings': { es: 'Configuración de la Cita', en: 'Citation settings', pt: 'Configuração da citação', fr: 'Paramètres de la citation', it: 'Impostazioni della citazione' },
  'apa.authorCount': { es: 'Número de Autores de la Fuente:', en: 'Number of authors in the source:', pt: 'Número de autores da fonte:', fr: 'Nombre d\'auteurs de la source :', it: 'Numero di autori della fonte:' },
  'apa.authors.one': { es: '1 Autor', en: '1 author', pt: '1 autor', fr: '1 auteur', it: '1 autore' },
  'apa.authors.two': { es: '2 Autores', en: '2 authors', pt: '2 autores', fr: '2 auteurs', it: '2 autori' },
  'apa.authors.three': { es: '3+ (et al.)', en: '3+ (et al.)', pt: '3+ (et al.)', fr: '3+ (et al.)', it: '3+ (et al.)' },
  'apa.ruleLabel': { es: 'Regla APA 7:', en: 'APA 7 rule:', pt: 'Regra APA 7:', fr: 'Règle APA 7 :', it: 'Regola APA 7:' },
  'apa.rule.one': { es: 'Regla APA 7 (1 autor): Se cita el apellido principal del autor y el año de publicación en cada ocasión.', en: 'APA 7 rule (1 author): cite the author\'s surname and the year of publication every time.', pt: 'Regra APA 7 (1 autor): cita-se o sobrenome do autor e o ano de publicação em todas as ocasiões.', fr: 'Règle APA 7 (1 auteur) : on cite le nom de l\'auteur et l\'année de publication à chaque fois.', it: 'Regola APA 7 (1 autore): si cita il cognome dell\'autore e l\'anno di pubblicazione ogni volta.' },
  'apa.rule.two': { es: 'Regla APA 7 (2 autores): Se citan siempre ambos autores en todas las ocasiones usando la conjunción "y" en español (o "&" dentro de paréntesis en inglés).', en: 'APA 7 rule (2 authors): always cite both authors, joined by "and" in running text and "&" inside parentheses.', pt: 'Regra APA 7 (2 autores): citam-se sempre os dois autores, com "e" no texto corrido e "&" dentro de parênteses.', fr: 'Règle APA 7 (2 auteurs) : on cite toujours les deux auteurs, avec « et » dans le texte et « & » entre parenthèses.', it: 'Regola APA 7 (2 autori): si citano sempre entrambi gli autori, con "e" nel testo e "&" fra parentesi.' },
  'apa.rule.three': { es: 'Regla APA 7 (3+ autores): Desde la primera mención en el texto, se cita únicamente el apellido del primer autor seguido de "et al." y el año. En la lista de referencias final, se listan hasta 20 autores.', en: 'APA 7 rule (3+ authors): from the very first mention, cite only the first author\'s surname followed by "et al." and the year. The reference list holds up to 20 authors.', pt: 'Regra APA 7 (3+ autores): desde a primeira menção, cita-se apenas o sobrenome do primeiro autor seguido de "et al." e o ano. Na lista de referências listam-se até 20 autores.', fr: 'Règle APA 7 (3 auteurs ou plus) : dès la première mention, on cite uniquement le nom du premier auteur suivi de « et al. » et de l\'année. La liste de références en compte jusqu\'à 20.', it: 'Regola APA 7 (3+ autori): fin dalla prima menzione si cita solo il cognome del primo autore seguito da "et al." e dall\'anno. Nell\'elenco dei riferimenti si elencano fino a 20 autori.' },
  'apa.integrationMode': { es: 'Modalidad de Integración en el Texto:', en: 'How it is woven into the text:', pt: 'Modo de integração no texto:', fr: 'Mode d\'intégration dans le texte :', it: 'Modalità di integrazione nel testo:' },
  'apa.style.parenthetical': { es: 'Cita Parentética', en: 'Parenthetical citation', pt: 'Citação parentética', fr: 'Citation entre parenthèses', it: 'Citazione parentetica' },
  'apa.style.parenthetical.desc': { es: 'Énfasis en el contenido empírico (Autor, Año al final).', en: 'Emphasis on the finding (author and year at the end).', pt: 'Ênfase no conteúdo empírico (autor, ano no final).', fr: 'Accent sur le résultat (auteur, année à la fin).', it: 'Enfasi sul contenuto empirico (autore, anno alla fine).' },
  'apa.style.narrative': { es: 'Cita Narrativa', en: 'Narrative citation', pt: 'Citação narrativa', fr: 'Citation narrative', it: 'Citazione narrativa' },
  'apa.style.narrative.desc': { es: 'Énfasis en el autor como sujeto activo: Según Gómez (2024)…', en: 'Emphasis on the author as subject: According to Gómez (2024)…', pt: 'Ênfase no autor como sujeito ativo: Segundo Gómez (2024)…', fr: 'Accent sur l\'auteur comme sujet : Selon Gómez (2024)…', it: 'Enfasi sull\'autore come soggetto: Secondo Gómez (2024)…' },
  'apa.style.directShort': { es: 'Textual Corta (< 40 palabras)', en: 'Short quotation (< 40 words)', pt: 'Citação curta (< 40 palavras)', fr: 'Citation courte (< 40 mots)', it: 'Citazione breve (< 40 parole)' },
  'apa.style.directShort.desc': { es: 'Entre comillas en el párrafo con indicación de página exacta.', en: 'In quotation marks within the paragraph, with the exact page.', pt: 'Entre aspas no parágrafo, com a página exata.', fr: 'Entre guillemets dans le paragraphe, avec la page exacte.', it: 'Fra virgolette nel paragrafo, con la pagina esatta.' },
  'apa.style.directBlock': { es: 'Textual en Bloque (≥ 40 palabras)', en: 'Block quotation (≥ 40 words)', pt: 'Citação em bloco (≥ 40 palavras)', fr: 'Citation en bloc (≥ 40 mots)', it: 'Citazione in blocco (≥ 40 parole)' },
  'apa.style.directBlock.desc': { es: 'Sangría izquierda 1.27 cm, sin comillas, a doble espacio.', en: 'Indented 1.27 cm, no quotation marks, double spaced.', pt: 'Recuo esquerdo de 1,27 cm, sem aspas, espaço duplo.', fr: 'Retrait de 1,27 cm, sans guillemets, double interligne.', it: 'Rientro di 1,27 cm, senza virgolette, interlinea doppia.' },
  'apa.liveResult': { es: 'Resultado Generado en Vivo', en: 'Live generated result', pt: 'Resultado gerado ao vivo', fr: 'Résultat généré en direct', it: 'Risultato generato in tempo reale' },
  'apa.inTextLabel': { es: '1. Cómo citar dentro del párrafo (Capítulo 2):', en: '1. How to cite within the paragraph (Chapter 2):', pt: '1. Como citar dentro do parágrafo (Capítulo 2):', fr: '1. Comment citer dans le paragraphe (chapitre 2) :', it: '1. Come citare nel paragrafo (Capitolo 2):' },
  'apa.copyCitation': { es: 'Copiar Cita', en: 'Copy citation', pt: 'Copiar citação', fr: 'Copier la citation', it: 'Copia la citazione' },
  'apa.referenceLabel': { es: '2. Entrada en la Lista Final de Referencias:', en: '2. Entry in the final reference list:', pt: '2. Entrada na lista final de referências:', fr: '2. Entrée dans la liste finale de références :', it: '2. Voce nell\'elenco finale dei riferimenti:' },
  'apa.copyReference': { es: 'Copiar Referencia', en: 'Copy reference', pt: 'Copiar referência', fr: 'Copier la référence', it: 'Copia il riferimento' },
  'apa.zoteroTitle': { es: 'Integración con Zotero 7:', en: 'Zotero 7 integration:', pt: 'Integração com o Zotero 7:', fr: 'Intégration avec Zotero 7 :', it: 'Integrazione con Zotero 7:' },
  'apa.zoteroBody': { es: 'Exporta tus artículos desde Scopus en formato RIS o BibTeX e impórtalos a Zotero. Al redactar en Microsoft Word o Google Docs con el plugin oficial, la norma APA 7 se aplicará de manera automatizada.', en: 'Export your articles from Scopus as RIS or BibTeX and import them into Zotero. When you write in Microsoft Word or Google Docs with the official plugin, APA 7 is applied automatically.', pt: 'Exporte os seus artigos do Scopus em RIS ou BibTeX e importe-os no Zotero. Ao escrever no Microsoft Word ou Google Docs com o plugin oficial, a norma APA 7 é aplicada automaticamente.', fr: 'Exportez vos articles depuis Scopus en RIS ou BibTeX et importez-les dans Zotero. En rédigeant dans Word ou Google Docs avec le plugin officiel, la norme APA 7 s\'applique automatiquement.', it: 'Esporta i tuoi articoli da Scopus in RIS o BibTeX e importali in Zotero. Scrivendo in Word o Google Docs con il plugin ufficiale, la norma APA 7 si applica in automatico.' },

  // ------------------------------------------------ Scopus & booleanos
  'scopus.badge': { es: 'Herramienta Metodológica #2', en: 'Methodological tool #2', pt: 'Ferramenta metodológica #2', fr: 'Outil méthodologique n° 2', it: 'Strumento metodologico n. 2' },
  'scopus.tagline': { es: 'Recuperación Documental Indexada', en: 'Indexed document retrieval', pt: 'Recuperação documental indexada', fr: 'Recherche documentaire indexée', it: 'Recupero documentale indicizzato' },
  'scopus.title': { es: 'Sintetizador de Ecuaciones de Búsqueda Booleana para Scopus & WoS 🔍', en: 'Boolean search-query builder for Scopus & WoS 🔍', pt: 'Sintetizador de equações booleanas para Scopus & WoS 🔍', fr: 'Générateur d\'équations booléennes pour Scopus & WoS 🔍', it: 'Generatore di equazioni booleane per Scopus & WoS 🔍' },
  'scopus.subtitle': { es: 'Optimización para la discriminación de literatura irrelevante. La formulación booleana formal con operadores lógicos y descriptores estandarizados asegura una revisión del estado del arte rigurosa para el Capítulo 2.', en: 'Built to filter out irrelevant literature. A formal boolean expression with logical operators and standard descriptors makes the Chapter 2 state of the art rigorous.', pt: 'Feito para descartar literatura irrelevante. A formulação booleana formal com operadores lógicos e descritores padronizados garante um estado da arte rigoroso para o Capítulo 2.', fr: 'Conçu pour écarter la littérature non pertinente. Une expression booléenne formelle avec opérateurs logiques et descripteurs normalisés assure un état de l\'art rigoureux pour le chapitre 2.', it: 'Pensato per scartare la letteratura irrilevante. Un\'espressione booleana formale con operatori logici e descrittori standard rende rigoroso lo stato dell\'arte del Capitolo 2.' },
  'scopus.builders': { es: 'Constructores de Bloques Conceptuales', en: 'Concept block builders', pt: 'Construtores de blocos conceituais', fr: 'Constructeurs de blocs conceptuels', it: 'Costruttori di blocchi concettuali' },
  'scopus.block1': { es: 'Bloque Conceptual 1 (Variable Independiente / Descriptores):', en: 'Concept block 1 (independent variable / descriptors):', pt: 'Bloco conceitual 1 (variável independente / descritores):', fr: 'Bloc conceptuel 1 (variable indépendante / descripteurs) :', it: 'Blocco concettuale 1 (variabile indipendente / descrittori):' },
  'scopus.block2': { es: 'Bloque Conceptual 2 (Variable Dependiente / Descriptores):', en: 'Concept block 2 (dependent variable / descriptors):', pt: 'Bloco conceitual 2 (variável dependente / descritores):', fr: 'Bloc conceptuel 2 (variable dépendante / descripteurs) :', it: 'Blocco concettuale 2 (variabile dipendente / descrittori):' },
  'scopus.placeholder1': { es: '"Variable 1" OR "Sinónimo en inglés"', en: '"Variable 1" OR "synonym"', pt: '"Variável 1" OR "sinônimo em inglês"', fr: '« Variable 1 » OR « synonyme en anglais »', it: '"Variabile 1" OR "sinonimo in inglese"' },
  'scopus.placeholder2': { es: '"Variable 2" OR "Sinónimo en inglés"', en: '"Variable 2" OR "synonym"', pt: '"Variável 2" OR "sinônimo em inglês"', fr: '« Variable 2 » OR « synonyme en anglais »', it: '"Variabile 2" OR "sinonimo in inglese"' },
  'scopus.tip': { es: 'Tip: Utiliza comillas dobles para frases compuestas y operador OR para sinónimos.', en: 'Tip: use double quotes for phrases and OR for synonyms.', pt: 'Dica: use aspas duplas para frases compostas e OR para sinônimos.', fr: 'Astuce : guillemets doubles pour les expressions, OR pour les synonymes.', it: 'Suggerimento: virgolette doppie per le frasi e OR per i sinonimi.' },
  'scopus.context': { es: 'Contexto / Sector / Unidad de Análisis (Opcional):', en: 'Context / sector / unit of analysis (optional):', pt: 'Contexto / setor / unidade de análise (opcional):', fr: 'Contexte / secteur / unité d\'analyse (facultatif) :', it: 'Contesto / settore / unità di analisi (facoltativo):' },
  'scopus.limiters': { es: 'Limitadores Académicos Institucionales:', en: 'Academic limiters:', pt: 'Limitadores acadêmicos:', fr: 'Limiteurs académiques :', it: 'Limitatori accademici:' },
  'scopus.openAccess': { es: 'Acceso Abierto (OA)', en: 'Open access (OA)', pt: 'Acesso aberto (OA)', fr: 'Libre accès (OA)', it: 'Accesso aperto (OA)' },
  'scopus.last5': { es: 'Últimos 5 Años', en: 'Last 5 years', pt: 'Últimos 5 anos', fr: '5 dernières années', it: 'Ultimi 5 anni' },
  'scopus.onlyArticles': { es: 'Solo Artículos (Papers)', en: 'Articles only', pt: 'Apenas artigos', fr: 'Articles seulement', it: 'Solo articoli' },
  'scopus.output': { es: 'Ecuación Sintetizada para Scopus', en: 'Generated Scopus query', pt: 'Equação gerada para o Scopus', fr: 'Équation générée pour Scopus', it: 'Equazione generata per Scopus' },
  'scopus.syntax': { es: 'Sintaxis Oficial Scopus (Avanzada)', en: 'Official Scopus syntax (advanced)', pt: 'Sintaxe oficial do Scopus (avançada)', fr: 'Syntaxe officielle Scopus (avancée)', it: 'Sintassi ufficiale Scopus (avanzata)' },
  'scopus.copyEquation': { es: 'Copiar Ecuación', en: 'Copy query', pt: 'Copiar equação', fr: 'Copier l\'équation', it: 'Copia l\'equazione' },
  'scopus.tryNow': { es: 'Probar Búsqueda Inmediata:', en: 'Run the search now:', pt: 'Testar a busca agora:', fr: 'Lancer la recherche :', it: 'Prova subito la ricerca:' },
  'scopus.samples': { es: 'Ejemplos de Ecuaciones Reales Listas para Usar:', en: 'Ready-to-use example queries:', pt: 'Exemplos de equações prontas para usar:', fr: 'Exemples d\'équations prêtes à l\'emploi :', it: 'Esempi di equazioni pronte all\'uso:' },

  'scopus.synonymsPlaceholder': { es: 'Sinónimos / familia de palabras (opcional)', en: 'Synonyms / word family (optional)', pt: 'Sinônimos / família de palavras (opcional)', fr: 'Synonymes / famille de mots (facultatif)', it: 'Sinonimi / famiglia di parole (facoltativo)' },
  'scopus.synonymsHint': { es: 'Se unen con OR al bloque. Cuantos más sinónimos y variantes del tesauro incluyas, más literatura relevante recuperas.', en: 'Joined with OR into the block. The more synonyms and thesaurus variants you add, the more relevant literature you retrieve.', pt: 'São unidos com OR ao bloco. Quanto mais sinônimos e variantes do tesauro incluir, mais literatura relevante você recupera.', fr: 'Ajoutés au bloc avec OR. Plus vous ajoutez de synonymes et de variantes du thésaurus, plus vous récupérez de littérature pertinente.', it: 'Vengono uniti con OR al blocco. Più sinonimi e varianti del tesauro includi, più letteratura rilevante recuperi.' },
  'scopus.tips.title': { es: 'Tips avanzados: precisión de la búsqueda', en: 'Advanced tips: search precision', pt: 'Dicas avançadas: precisão da busca', fr: 'Astuces avancées : précision de la recherche', it: 'Consigli avanzati: precisione della ricerca' },
  'scopus.tips.thesaurus.title': { es: 'Usa familias de palabras, tesauros y sinónimos', en: 'Use word families, thesauri and synonyms', pt: 'Use famílias de palavras, tesauros e sinônimos', fr: 'Utilisez des familles de mots, des thésaurus et des synonymes', it: 'Usa famiglie di parole, tesauri e sinonimi' },
  'scopus.tips.thesaurus.body': { es: 'Una sola palabra clave deja fuera artículos que usan un término distinto para la misma idea. Antes de buscar, consulta el Tesauro de la UNESCO o el MeSH (en salud) y agrega al campo de sinónimos las variantes en inglés (singular/plural, sustantivo/adjetivo, siglas) y los términos relacionados que encuentres en los primeros 3-5 artículos que sí te sirvan.', en: 'A single keyword excludes articles that use a different term for the same idea. Before searching, check the UNESCO Thesaurus or MeSH (health) and add English variants (singular/plural, noun/adjective, acronyms) and related terms found in the first 3-5 relevant articles to the synonyms field.', pt: 'Uma única palavra-chave deixa de fora artigos que usam um termo diferente para a mesma ideia. Antes de buscar, consulte o Tesauro da UNESCO ou o MeSH (saúde) e adicione ao campo de sinônimos as variantes em inglês (singular/plural, substantivo/adjetivo, siglas) e os termos relacionados encontrados nos primeiros 3-5 artigos relevantes.', fr: 'Un seul mot-clé exclut les articles qui utilisent un terme différent pour la même idée. Avant de chercher, consultez le Thésaurus de l\'UNESCO ou le MeSH (santé) et ajoutez au champ des synonymes les variantes en anglais (singulier/pluriel, nom/adjectif, sigles) et les termes associés trouvés dans les 3 à 5 premiers articles pertinents.', it: 'Una sola parola chiave esclude articoli che usano un termine diverso per la stessa idea. Prima di cercare, consulta il Thesaurus UNESCO o il MeSH (salute) e aggiungi al campo dei sinonimi le varianti in inglese (singolare/plurale, sostantivo/aggettivo, sigle) e i termini correlati trovati nei primi 3-5 articoli rilevanti.' },
  'scopus.aiTip.title': { es: 'Usa una IA para filtrar los PDF que descargaste', en: 'Use an AI to filter the PDFs you downloaded', pt: 'Use uma IA para filtrar os PDFs que você baixou', fr: 'Utilisez une IA pour filtrer les PDF téléchargés', it: 'Usa un\'IA per filtrare i PDF scaricati' },
  'scopus.aiTip.body': { es: 'Cuando descargues decenas de artículos, súbelos a una IA (Claude, ChatGPT, NotebookLM) con un prompt avanzado para que te diga cuáles se relacionan de verdad con tu tema antes de leerlos todos.', en: 'When you download dozens of articles, upload them to an AI (Claude, ChatGPT, NotebookLM) with an advanced prompt so it tells you which ones truly relate to your topic before you read them all.', pt: 'Ao baixar dezenas de artigos, envie-os para uma IA (Claude, ChatGPT, NotebookLM) com um prompt avançado para que ela diga quais realmente se relacionam com seu tema antes de você ler todos.', fr: 'Lorsque vous téléchargez des dizaines d\'articles, envoyez-les à une IA (Claude, ChatGPT, NotebookLM) avec un prompt avancé pour qu\'elle vous dise lesquels sont vraiment liés à votre sujet avant de tous les lire.', it: 'Quando scarichi decine di articoli, caricali su un\'IA (Claude, ChatGPT, NotebookLM) con un prompt avanzato perché ti dica quali sono davvero legati al tuo tema prima di leggerli tutti.' },
  'scopus.aiTip.promptLabel': { es: 'Prompt listo para copiar', en: 'Ready-to-copy prompt', pt: 'Prompt pronto para copiar', fr: 'Prompt prêt à copier', it: 'Prompt pronto da copiare' },
  'scopus.aiTip.prompt': {
    es: 'Adjunto varios artículos académicos en PDF. Mi tema de titulación es: "[pega aquí tu título]". Para cada PDF: 1) resume la idea central en 2 líneas, 2) indica si aporta a mi marco teórico, mi metodología o mis antecedentes, 3) califica su relevancia para mi tema como Alta/Media/Baja con una razón concreta, 4) si es Baja, dime por qué lo descartarías. Al final dame una lista ordenada de más a menos relevante.',
    en: 'I am attaching several academic PDFs. My thesis topic is: "[paste your title here]". For each PDF: 1) summarize the core idea in 2 lines, 2) say whether it contributes to my theoretical framework, methodology or background, 3) rate its relevance to my topic as High/Medium/Low with a concrete reason, 4) if Low, tell me why you would discard it. At the end, give me a list ranked from most to least relevant.',
    pt: 'Estou anexando vários artigos acadêmicos em PDF. Meu tema de titulação é: "[cole seu título aqui]". Para cada PDF: 1) resuma a ideia central em 2 linhas, 2) diga se contribui para meu referencial teórico, minha metodologia ou meus antecedentes, 3) classifique sua relevância para meu tema como Alta/Média/Baixa com um motivo concreto, 4) se for Baixa, diga por que você descartaria. No final, me dê uma lista ordenada da mais para a menos relevante.',
    fr: 'Je joins plusieurs articles académiques en PDF. Mon sujet de thèse est : « [collez votre titre ici] ». Pour chaque PDF : 1) résumez l\'idée centrale en 2 lignes, 2) indiquez s\'il contribue à mon cadre théorique, ma méthodologie ou mon état de l\'art, 3) évaluez sa pertinence pour mon sujet comme Élevée/Moyenne/Faible avec une raison concrète, 4) si Faible, dites pourquoi vous l\'écarteriez. À la fin, donnez-moi une liste classée de la plus à la moins pertinente.',
    it: 'Allego diversi articoli accademici in PDF. Il mio argomento di tesi è: "[incolla qui il tuo titolo]". Per ogni PDF: 1) riassumi l\'idea centrale in 2 righe, 2) indica se contribuisce al mio quadro teorico, alla mia metodologia o ai miei antecedenti, 3) valuta la sua rilevanza per il mio argomento come Alta/Media/Bassa con una ragione concreta, 4) se Bassa, dimmi perché la scarteresti. Alla fine, dammi un elenco ordinato dal più al meno rilevante.',
  },
  // ----------------------------------------------------- Presentación
  'slides.keyRuleLabel': { es: 'Principio Metodológico Fundamental', en: 'Core methodological principle', pt: 'Princípio metodológico fundamental', fr: 'Principe méthodologique fondamental', it: 'Principio metodologico fondamentale' },
  'slides.proTipLabel': { es: 'Criterio Técnico:', en: 'Technical note:', pt: 'Critério técnico:', fr: 'Critère technique :', it: 'Criterio tecnico:' },
};
