/**
 * Catálogo de software académico, traducido.
 *
 * Las claves siguen el patrón `tool.<id>.<campo>`, donde `<id>` es el mismo
 * identificador que usa `ACADEMIC_TOOLS` en `src/data/thesisData.ts`. Los nombres
 * de producto no se traducen; sí lo hace todo lo que los describe.
 */

import type { ContentDict } from './types';

export const TOOL_TRANSLATIONS: ContentDict = {
  // ---------------------------------------------------------------- categorías
  'toolbox.category.all': { es: 'Todas', en: 'All', pt: 'Todas', fr: 'Toutes', it: 'Tutte' },
  'toolbox.category.search': { es: 'Búsqueda de Papers', en: 'Paper search', pt: 'Busca de artigos', fr: 'Recherche d\'articles', it: 'Ricerca di articoli' },
  'toolbox.category.citations': { es: 'Gestión de Citas APA', en: 'APA citation management', pt: 'Gestão de citações APA', fr: 'Gestion des citations APA', it: 'Gestione delle citazioni APA' },
  'toolbox.category.writing': { es: 'Redacción & Estilo', en: 'Writing & style', pt: 'Redação & estilo', fr: 'Rédaction & style', it: 'Scrittura & stile' },
  'toolbox.category.analysis': { es: 'Análisis & Síntesis IA', en: 'AI analysis & synthesis', pt: 'Análise & síntese com IA', fr: 'Analyse & synthèse par IA', it: 'Analisi & sintesi con IA' },

  // ------------------------------------------------------------- modelo de pago
  'toolbox.pricing.free': { es: 'Gratuito', en: 'Free', pt: 'Gratuito', fr: 'Gratuit', it: 'Gratuito' },
  'toolbox.pricing.freemium': { es: 'Freemium', en: 'Freemium', pt: 'Freemium', fr: 'Freemium', it: 'Freemium' },
  'toolbox.pricing.institutional': { es: 'Institucional', en: 'Institutional', pt: 'Institucional', fr: 'Institutionnel', it: 'Istituzionale' },

  // -------------------------------------------------------------------- Zotero
  'tool.zotero.name': { es: 'Zotero (Gestor Oficial APA 7)', en: 'Zotero (official APA 7 manager)', pt: 'Zotero (gestor oficial APA 7)', fr: 'Zotero (gestionnaire officiel APA 7)', it: 'Zotero (gestore ufficiale APA 7)' },
  'tool.zotero.badge': { es: '¡Imprescindible para tu Tesis!', en: 'Essential for your thesis', pt: 'Indispensável para a sua tese', fr: 'Indispensable pour votre mémoire', it: 'Indispensabile per la tua tesi' },
  'tool.zotero.description': { es: 'Software libre para organizar papers y generar citas automáticas. Se integra a Word y Google Docs con un solo clic. ¡Nunca más hagas referencias a mano!', en: 'Free software to organise papers and generate citations automatically. It plugs into Word and Google Docs with a single click. Never type a reference by hand again.', pt: 'Software livre para organizar artigos e gerar citações automáticas. Integra-se ao Word e ao Google Docs com um clique. Nunca mais escreva referências à mão.', fr: 'Logiciel libre pour organiser vos articles et générer les citations automatiquement. Il s\'intègre à Word et Google Docs en un clic. Fini les références saisies à la main.', it: 'Software libero per organizzare gli articoli e generare citazioni automatiche. Si integra con Word e Google Docs con un clic. Mai più riferimenti scritti a mano.' },
  'tool.zotero.keyBenefit': { es: 'Inserta citas en el texto y genera tu bibliografía en formato APA 7 con sangría francesa perfecta al instante.', en: 'Inserts in-text citations and builds your APA 7 bibliography with a perfect hanging indent, instantly.', pt: 'Insere citações no texto e gera a bibliografia em APA 7 com recuo francês perfeito, na hora.', fr: 'Insère les citations dans le texte et génère votre bibliographie APA 7 avec un retrait négatif parfait, instantanément.', it: 'Inserisce le citazioni nel testo e genera la bibliografia in APA 7 con rientro sporgente perfetto, all\'istante.' },
  'tool.zotero.proTip': { es: 'Arrastra cualquier PDF a Zotero y extraerá automáticamente el autor, año, revista y DOI sin que escribas nada.', en: 'Drag any PDF into Zotero and it pulls the author, year, journal and DOI on its own.', pt: 'Arraste qualquer PDF para o Zotero e ele extrai autor, ano, revista e DOI sozinho.', fr: 'Glissez n\'importe quel PDF dans Zotero : il en extrait seul l\'auteur, l\'année, la revue et le DOI.', it: 'Trascina un PDF in Zotero e ne estrae da solo autore, anno, rivista e DOI.' },

  // -------------------------------------------------------------------- Scopus
  'tool.scopus.name': { es: 'Scopus (Elsevier)', en: 'Scopus (Elsevier)', pt: 'Scopus (Elsevier)', fr: 'Scopus (Elsevier)', it: 'Scopus (Elsevier)' },
  'tool.scopus.badge': { es: 'La Joya de la Corona Q1/Q2', en: 'The Q1/Q2 crown jewel', pt: 'A joia da coroa Q1/Q2', fr: 'Le joyau Q1/Q2', it: 'Il gioiello Q1/Q2' },
  'tool.scopus.description': { es: 'La base de datos científica más prestigiosa del mundo. Aquí encuentras papers indexados con revisión por pares, el respaldo más sólido para tus antecedentes.', en: 'The most prestigious scientific database in the world. Peer-reviewed indexed papers: the strongest backing your literature review can have.', pt: 'A base de dados científica mais prestigiada do mundo. Artigos indexados com revisão por pares: o respaldo mais sólido para os seus antecedentes.', fr: 'La base de données scientifique la plus prestigieuse au monde. Des articles indexés et évalués par les pairs : le meilleur appui pour votre état de l\'art.', it: 'La banca dati scientifica più prestigiosa al mondo. Articoli indicizzati con revisione paritaria: il sostegno più solido per i tuoi antecedenti.' },
  'tool.scopus.keyBenefit': { es: 'Garantiza que tus antecedentes tengan el máximo peso académico para aprobar tu defensa con honores.', en: 'Gives your literature review the greatest possible academic weight when you defend.', pt: 'Dá aos seus antecedentes o maior peso acadêmico possível na defesa.', fr: 'Donne à votre état de l\'art le plus grand poids académique possible lors de la soutenance.', it: 'Dà ai tuoi antecedenti il massimo peso accademico in sede di discussione.' },
  'tool.scopus.proTip': { es: 'Usa el filtro "Open Access" para encontrar artículos completos y gratuitos listos para citar en tu Cap. 2.', en: 'Use the "Open Access" filter to find complete, free articles ready to cite in Chapter 2.', pt: 'Use o filtro "Open Access" para achar artigos completos e gratuitos prontos para citar no Cap. 2.', fr: 'Utilisez le filtre « Open Access » pour trouver des articles complets et gratuits, prêts à citer au chapitre 2.', it: 'Usa il filtro "Open Access" per trovare articoli completi e gratuiti pronti da citare nel Cap. 2.' },

  // --------------------------------------------------------- Connected Papers
  'tool.connected-papers.name': { es: 'Connected Papers', en: 'Connected Papers', pt: 'Connected Papers', fr: 'Connected Papers', it: 'Connected Papers' },
  'tool.connected-papers.badge': { es: 'Mapeo Visual de Papers', en: 'Visual paper mapping', pt: 'Mapeamento visual de artigos', fr: 'Cartographie visuelle des articles', it: 'Mappatura visiva degli articoli' },
  'tool.connected-papers.description': { es: 'Ingresa un solo artículo clave de tu tema y Connected Papers te dibuja un mapa visual con todos los autores y papers relacionados en el mundo.', en: 'Enter one key article on your topic and Connected Papers draws a visual map of every related author and paper worldwide.', pt: 'Informe um único artigo-chave do seu tema e o Connected Papers desenha um mapa visual com todos os autores e artigos relacionados no mundo.', fr: 'Saisissez un seul article clé de votre sujet et Connected Papers dessine une carte visuelle de tous les auteurs et articles liés dans le monde.', it: 'Inserisci un solo articolo chiave del tuo tema e Connected Papers disegna una mappa visiva di tutti gli autori e articoli correlati nel mondo.' },
  'tool.connected-papers.keyBenefit': { es: 'Descubre en 5 minutos quiénes son los autores principales y qué artículos no pueden faltar en tu estado del arte.', en: 'Find out in five minutes who the leading authors are and which papers your state of the art cannot omit.', pt: 'Descubra em 5 minutos quem são os autores principais e quais artigos não podem faltar no seu estado da arte.', fr: 'Découvrez en cinq minutes qui sont les auteurs majeurs et quels articles votre état de l\'art ne peut pas omettre.', it: 'Scopri in cinque minuti chi sono gli autori principali e quali articoli non possono mancare nel tuo stato dell\'arte.' },
  'tool.connected-papers.proTip': { es: 'Revisa la sección "Prior Works" para ver las teorías base y "Derivative Works" para los últimos avances del año actual.', en: 'Check "Prior Works" for the founding theories and "Derivative Works" for this year\'s latest advances.', pt: 'Veja "Prior Works" para as teorias de base e "Derivative Works" para os avanços mais recentes do ano.', fr: 'Consultez « Prior Works » pour les théories fondatrices et « Derivative Works » pour les avancées les plus récentes.', it: 'Guarda "Prior Works" per le teorie di base e "Derivative Works" per gli avanzamenti più recenti dell\'anno.' },

  // ------------------------------------------------------------- Consensus.app
  'tool.consensus-app.name': { es: 'Consensus.app', en: 'Consensus.app', pt: 'Consensus.app', fr: 'Consensus.app', it: 'Consensus.app' },
  'tool.consensus-app.badge': { es: 'Buscador IA con Evidencia Real', en: 'AI search with real evidence', pt: 'Busca com IA e evidência real', fr: 'Recherche IA fondée sur des preuves', it: 'Ricerca con IA basata su prove reali' },
  'tool.consensus-app.description': { es: 'Motor de búsqueda que responde tus preguntas de investigación sintetizando más de 200 millones de papers científicos reales (nada de alucinaciones).', en: 'A search engine that answers your research questions by synthesising more than 200 million real scientific papers — no hallucinations.', pt: 'Motor de busca que responde às suas perguntas de pesquisa sintetizando mais de 200 milhões de artigos científicos reais, sem alucinações.', fr: 'Un moteur de recherche qui répond à vos questions de recherche en synthétisant plus de 200 millions d\'articles scientifiques réels, sans hallucinations.', it: 'Un motore di ricerca che risponde alle tue domande di ricerca sintetizzando oltre 200 milioni di articoli scientifici reali, senza allucinazioni.' },
  'tool.consensus-app.keyBenefit': { es: 'Te muestra el porcentaje de consenso entre científicos para sustentar tu problema y justificación con datos duros.', en: 'Shows the percentage of scientific consensus, so your problem and rationale rest on hard data.', pt: 'Mostra a porcentagem de consenso entre cientistas para sustentar o problema e a justificativa com dados concretos.', fr: 'Affiche le pourcentage de consensus scientifique, pour appuyer votre problème et votre justification sur des données solides.', it: 'Mostra la percentuale di consenso scientifico, per fondare problema e giustificazione su dati concreti.' },
  'tool.consensus-app.proTip': { es: 'Hazle preguntas en inglés sobre la relación de tus variables (ej: "Does digital marketing improve sales in SMEs?").', en: 'Ask it in English about the relationship between your variables (e.g. "Does digital marketing improve sales in SMEs?").', pt: 'Pergunte em inglês sobre a relação entre as suas variáveis (ex.: "Does digital marketing improve sales in SMEs?").', fr: 'Interrogez-le en anglais sur la relation entre vos variables (ex. : « Does digital marketing improve sales in SMEs? »).', it: 'Interrogalo in inglese sulla relazione fra le tue variabili (es. "Does digital marketing improve sales in SMEs?").' },

  // ---------------------------------------------------------------- DeepL Write
  'tool.deepl-write.name': { es: 'DeepL Write', en: 'DeepL Write', pt: 'DeepL Write', fr: 'DeepL Write', it: 'DeepL Write' },
  'tool.deepl-write.badge': { es: 'Estilo Académico Impecable', en: 'Impeccable academic style', pt: 'Estilo acadêmico impecável', fr: 'Style académique impeccable', it: 'Stile accademico impeccabile' },
  'tool.deepl-write.description': { es: 'Asistente de redacción basado en IA que mejora tu vocabulario técnico, elimina repeticiones y te ayuda a sonar como un auténtico investigador.', en: 'An AI writing assistant that sharpens your technical vocabulary, removes repetition and helps you sound like a real researcher.', pt: 'Assistente de redação com IA que melhora o vocabulário técnico, elimina repetições e ajuda você a soar como um pesquisador de verdade.', fr: 'Assistant de rédaction par IA qui affine votre vocabulaire technique, supprime les répétitions et vous fait écrire comme un vrai chercheur.', it: 'Assistente di scrittura con IA che affina il lessico tecnico, elimina le ripetizioni e ti fa scrivere come un vero ricercatore.' },
  'tool.deepl-write.keyBenefit': { es: 'Pule la fluidez de tus párrafos para que tu tutor o revisor lea tu tesis con agrado y sin trabas gramaticales.', en: 'Smooths your paragraphs so your advisor or reviewer reads without stumbling over grammar.', pt: 'Melhora a fluidez dos parágrafos para que o tutor ou revisor leia sem tropeçar na gramática.', fr: 'Fluidifie vos paragraphes pour que votre directeur ou relecteur lise sans buter sur la grammaire.', it: 'Rende fluidi i paragrafi perché il relatore o il revisore legga senza inciampare nella grammatica.' },
  'tool.deepl-write.proTip': { es: 'Haz clic sobre cualquier palabra para ver sinónimos formales más elegantes para tu redacción científica.', en: 'Click any word to see more formal, elegant synonyms for scientific writing.', pt: 'Clique em qualquer palavra para ver sinônimos formais mais elegantes para a escrita científica.', fr: 'Cliquez sur un mot pour voir des synonymes plus formels et élégants pour l\'écriture scientifique.', it: 'Clicca su una parola per vedere sinonimi più formali ed eleganti per la scrittura scientifica.' },

  // ------------------------------------------------------------------- SciSpace
  'tool.scispace.name': { es: 'SciSpace (Typeset)', en: 'SciSpace (Typeset)', pt: 'SciSpace (Typeset)', fr: 'SciSpace (Typeset)', it: 'SciSpace (Typeset)' },
  'tool.scispace.badge': { es: 'Lector Inteligente de PDFs', en: 'Smart PDF reader', pt: 'Leitor inteligente de PDFs', fr: 'Lecteur PDF intelligent', it: 'Lettore PDF intelligente' },
  'tool.scispace.description': { es: 'Sube un paper en inglés o español y chatea con él: pregúntale cuál fue la muestra, qué metodología usaron y cuáles fueron sus conclusiones.', en: 'Upload a paper in English or Spanish and chat with it: ask about the sample, the methodology and the conclusions.', pt: 'Envie um artigo em inglês ou espanhol e converse com ele: pergunte qual foi a amostra, a metodologia e as conclusões.', fr: 'Téléversez un article en anglais ou en espagnol et dialoguez avec lui : interrogez-le sur l\'échantillon, la méthodologie et les conclusions.', it: 'Carica un articolo in inglese o spagnolo e dialoga con esso: chiedi qual era il campione, la metodologia e le conclusioni.' },
  'tool.scispace.keyBenefit': { es: 'Lee papers 5 veces más rápido y extrae la información exacta que necesitas para tu matriz de antecedentes. ⏱', en: 'Read papers five times faster and pull exactly what your literature matrix needs. ⏱', pt: 'Leia artigos cinco vezes mais rápido e extraia exatamente o que a sua matriz de antecedentes precisa. ⏱', fr: 'Lisez cinq fois plus vite et extrayez exactement ce dont votre matrice d\'antécédents a besoin. ⏱', it: 'Leggi gli articoli cinque volte più in fretta ed estrai esattamente ciò che serve alla tua matrice. ⏱' },
  'tool.scispace.proTip': { es: 'Pídele: "Resume la muestra, el diseño metodológico y el resultado principal en 3 viñetas" para copiarlo a tu matriz.', en: 'Ask it: "Summarise the sample, the design and the main result in three bullets" and paste that into your matrix.', pt: 'Peça: "Resuma a amostra, o desenho metodológico e o resultado principal em 3 tópicos" e cole na sua matriz.', fr: 'Demandez-lui : « Résume l\'échantillon, le design et le résultat principal en trois puces » et collez-le dans votre matrice.', it: 'Chiedigli: "Riassumi campione, disegno e risultato principale in tre punti" e incollalo nella tua matrice.' },
};
