/**
 * Videoteca guiada, traducida.
 *
 * Claves `video.<id>.<campo>` y `track.<id>.<campo>`, con los mismos
 * identificadores que `src/data/videoLibrary.ts`.
 *
 * La consulta de búsqueda (`query`) también se traduce, y no por adorno: una
 * búsqueda en español devuelve material en español. Un estudiante que lee el
 * portal en portugués necesita que YouTube le abra los términos en portugués, o
 * la tarjeta no le sirve de nada.
 */

import type { ContentDict } from './types';

export const VIDEO_TRANSLATIONS: ContentDict = {
  // ------------------------------------------------------------------- rutas
  'track.all': { es: 'Todas', en: 'All', pt: 'Todas', fr: 'Toutes', it: 'Tutte' },
  'track.Estructura': { es: 'Estructura', en: 'Structure', pt: 'Estrutura', fr: 'Structure', it: 'Struttura' },
  'track.Metodología': { es: 'Metodología', en: 'Methodology', pt: 'Metodologia', fr: 'Méthodologie', it: 'Metodologia' },
  'track.Literatura científica': { es: 'Literatura científica', en: 'Scientific literature', pt: 'Literatura científica', fr: 'Littérature scientifique', it: 'Letteratura scientifica' },
  'track.Herramientas': { es: 'Herramientas', en: 'Tools', pt: 'Ferramentas', fr: 'Outils', it: 'Strumenti' },
  'track.Sustentación': { es: 'Sustentación', en: 'Defence', pt: 'Defesa', fr: 'Soutenance', it: 'Discussione' },

  'track.Estructura.label': { es: 'Estructura del documento', en: 'Document structure', pt: 'Estrutura do documento', fr: 'Structure du document', it: 'Struttura del documento' },
  'track.Estructura.description': { es: 'Cómo se arma el documento y qué va en cada capítulo.', en: 'How the document is assembled and what belongs in each chapter.', pt: 'Como o documento é montado e o que vai em cada capítulo.', fr: 'Comment le document s\'assemble et ce qui va dans chaque chapitre.', it: 'Come si compone il documento e cosa va in ogni capitolo.' },
  'track.Metodología.label': { es: 'Metodología y diseño', en: 'Methodology and design', pt: 'Metodologia e desenho', fr: 'Méthodologie et design', it: 'Metodologia e disegno' },
  'track.Metodología.description': { es: 'Problema, objetivos, variables y marco metodológico.', en: 'Problem, objectives, variables and methodological framework.', pt: 'Problema, objetivos, variáveis e marco metodológico.', fr: 'Problème, objectifs, variables et cadre méthodologique.', it: 'Problema, obiettivi, variabili e quadro metodologico.' },
  'track.Literatura científica.label': { es: 'Revisión de literatura', en: 'Literature review', pt: 'Revisão de literatura', fr: 'Revue de littérature', it: 'Revisione della letteratura' },
  'track.Literatura científica.description': { es: 'Búsqueda, filtrado y organización de fuentes indexadas.', en: 'Searching, filtering and organising indexed sources.', pt: 'Busca, filtragem e organização de fontes indexadas.', fr: 'Recherche, filtrage et organisation des sources indexées.', it: 'Ricerca, filtraggio e organizzazione delle fonti indicizzate.' },
  'track.Herramientas.label': { es: 'Herramientas', en: 'Tools', pt: 'Ferramentas', fr: 'Outils', it: 'Strumenti' },
  'track.Herramientas.description': { es: 'Zotero, gestores, análisis estadístico y antiplagio.', en: 'Zotero, reference managers, statistics and plagiarism checking.', pt: 'Zotero, gestores, análise estatística e antiplágio.', fr: 'Zotero, gestionnaires, analyse statistique et antiplagiat.', it: 'Zotero, gestori bibliografici, analisi statistica e antiplagio.' },
  'track.Sustentación.label': { es: 'Sustentación', en: 'Defence', pt: 'Defesa', fr: 'Soutenance', it: 'Discussione' },
  'track.Sustentación.description': { es: 'Preparación de la defensa y manejo de observaciones.', en: 'Preparing the defence and handling reviewer comments.', pt: 'Preparação da defesa e tratamento das observações.', fr: 'Préparation de la soutenance et traitement des remarques.', it: 'Preparazione della discussione e gestione delle osservazioni.' },

  'videos.allDescription': { es: 'Rutas de aprendizaje ordenadas por el momento del proceso en el que conviene verlas.', en: 'Learning tracks ordered by the moment in the process when they help most.', pt: 'Trilhas de aprendizagem ordenadas pelo momento do processo em que convém vê-las.', fr: 'Parcours d\'apprentissage classés selon le moment du processus où ils sont utiles.', it: 'Percorsi di apprendimento ordinati secondo il momento del processo in cui servono.' },

  // ------------------------------------------------------------- Estructura
  'video.estructura-capitulos.title': { es: 'Los capítulos de una tesis explicados uno por uno', en: 'The chapters of a thesis, explained one by one', pt: 'Os capítulos de uma tese explicados um a um', fr: 'Les chapitres d\'un mémoire, expliqués un par un', it: 'I capitoli di una tesi spiegati uno per uno' },
  'video.estructura-capitulos.outcome': { es: 'Identificar qué contenido corresponde a cada capítulo y dejar de mezclar marco teórico con resultados.', en: 'Work out what belongs in each chapter and stop mixing the theoretical framework with the results.', pt: 'Identificar o que cabe em cada capítulo e parar de misturar marco teórico com resultados.', fr: 'Déterminer ce qui relève de chaque chapitre et cesser de mêler cadre théorique et résultats.', it: 'Capire cosa appartiene a ciascun capitolo e smettere di mescolare quadro teorico e risultati.' },
  'video.estructura-capitulos.moment': { es: 'Antes de escribir la primera página', en: 'Before writing the first page', pt: 'Antes de escrever a primeira página', fr: 'Avant d\'écrire la première page', it: 'Prima di scrivere la prima pagina' },
  'video.estructura-capitulos.query': { es: 'estructura de una tesis capitulo 1 2 3 4 5 explicacion completa', en: 'thesis structure chapter 1 2 3 4 5 full explanation', pt: 'estrutura de uma tese capitulo 1 2 3 4 5 explicacao completa', fr: 'structure d une these chapitre 1 2 3 4 5 explication complete', it: 'struttura di una tesi capitolo 1 2 3 4 5 spiegazione completa' },

  'video.estructura-estudio-caso.title': { es: 'Estudio de caso como modalidad de titulación', en: 'The case study as a graduation format', pt: 'Estudo de caso como modalidade de titulação', fr: 'L\'étude de cas comme modalité de diplomation', it: 'Lo studio di caso come modalità di laurea' },
  'video.estructura-estudio-caso.outcome': { es: 'Entender en qué se diferencia un estudio de caso de una tesis tradicional y qué evidencias exige.', en: 'Understand how a case study differs from a traditional thesis and what evidence it demands.', pt: 'Entender como um estudo de caso difere de uma tese tradicional e que evidências exige.', fr: 'Comprendre en quoi une étude de cas diffère d\'un mémoire classique et quelles preuves elle exige.', it: 'Capire in cosa uno studio di caso differisce da una tesi tradizionale e quali prove richiede.' },
  'video.estructura-estudio-caso.moment': { es: 'Al definir tu modalidad', en: 'When choosing your format', pt: 'Ao definir a sua modalidade', fr: 'Au moment de choisir votre modalité', it: 'Quando scegli la modalità' },
  'video.estructura-estudio-caso.query': { es: 'estudio de caso practico titulacion ingenieria como se estructura', en: 'practical case study thesis how to structure it', pt: 'estudo de caso pratico tcc como se estrutura', fr: 'etude de cas pratique memoire comment la structurer', it: 'studio di caso pratico tesi come si struttura' },

  'video.estructura-resumen.title': { es: 'Cómo redactar el resumen y el abstract', en: 'How to write the summary and the abstract', pt: 'Como redigir o resumo e o abstract', fr: 'Comment rédiger le résumé et l\'abstract', it: 'Come scrivere il riassunto e l\'abstract' },
  'video.estructura-resumen.outcome': { es: 'Escribir un resumen de 150 a 250 palabras que declare problema, método, resultado y conclusión.', en: 'Write a 150–250 word summary stating problem, method, result and conclusion.', pt: 'Escrever um resumo de 150 a 250 palavras que declare problema, método, resultado e conclusão.', fr: 'Rédiger un résumé de 150 à 250 mots énonçant problème, méthode, résultat et conclusion.', it: 'Scrivere un riassunto di 150-250 parole che dichiari problema, metodo, risultato e conclusione.' },
  'video.estructura-resumen.moment': { es: 'Al final, cuando el documento ya está escrito', en: 'At the end, once the document is written', pt: 'No final, quando o documento já está escrito', fr: 'À la fin, une fois le document rédigé', it: 'Alla fine, quando il documento è già scritto' },
  'video.estructura-resumen.query': { es: 'como redactar resumen y abstract de tesis 250 palabras', en: 'how to write thesis abstract 250 words', pt: 'como escrever resumo e abstract de tese 250 palavras', fr: 'comment rediger resume et abstract de memoire 250 mots', it: 'come scrivere riassunto e abstract di tesi 250 parole' },

  'video.estructura-conclusiones.title': { es: 'Conclusiones y recomendaciones que responden a los objetivos', en: 'Conclusions and recommendations that answer the objectives', pt: 'Conclusões e recomendações que respondem aos objetivos', fr: 'Conclusions et recommandations qui répondent aux objectifs', it: 'Conclusioni e raccomandazioni che rispondono agli obiettivi' },
  'video.estructura-conclusiones.outcome': { es: 'Redactar una conclusión por objetivo específico sin repetir el marco teórico.', en: 'Write one conclusion per specific objective without rehearsing the theoretical framework.', pt: 'Escrever uma conclusão por objetivo específico sem repetir o marco teórico.', fr: 'Rédiger une conclusion par objectif spécifique sans répéter le cadre théorique.', it: 'Scrivere una conclusione per ogni obiettivo specifico senza ripetere il quadro teorico.' },
  'video.estructura-conclusiones.moment': { es: 'Cierre del documento', en: 'Closing the document', pt: 'Fechamento do documento', fr: 'Clôture du document', it: 'Chiusura del documento' },
  'video.estructura-conclusiones.query': { es: 'como escribir conclusiones y recomendaciones de tesis segun objetivos', en: 'how to write thesis conclusions and recommendations from objectives', pt: 'como escrever conclusoes e recomendacoes de tese segundo objetivos', fr: 'comment ecrire conclusions et recommandations de memoire selon objectifs', it: 'come scrivere conclusioni e raccomandazioni di tesi secondo obiettivi' },

  // ------------------------------------------------------------- Metodología
  'video.metodo-problema.title': { es: 'Planteamiento del problema con la técnica del embudo', en: 'Framing the problem with the funnel technique', pt: 'Formulação do problema com a técnica do funil', fr: 'Poser le problème avec la technique de l\'entonnoir', it: 'Impostare il problema con la tecnica dell\'imbuto' },
  'video.metodo-problema.outcome': { es: 'Bajar del contexto internacional al caso concreto de tu institución sin perder el hilo.', en: 'Move from the international context down to your own institution without losing the thread.', pt: 'Descer do contexto internacional ao caso concreto da sua instituição sem perder o fio.', fr: 'Passer du contexte international au cas concret de votre établissement sans perdre le fil.', it: 'Scendere dal contesto internazionale al caso concreto del tuo ateneo senza perdere il filo.' },
  'video.metodo-problema.moment': { es: 'Capítulo 1', en: 'Chapter 1', pt: 'Capítulo 1', fr: 'Chapitre 1', it: 'Capitolo 1' },
  'video.metodo-problema.query': { es: 'planteamiento del problema tecnica del embudo macro meso micro tesis', en: 'problem statement funnel technique macro meso micro thesis', pt: 'formulacao do problema tecnica do funil macro meso micro tese', fr: 'problematique technique entonnoir macro meso micro memoire', it: 'formulazione del problema tecnica imbuto macro meso micro tesi' },

  'video.metodo-objetivos.title': { es: 'Objetivos de investigación con la taxonomía de Bloom', en: 'Research objectives using Bloom\'s taxonomy', pt: 'Objetivos de pesquisa com a taxonomia de Bloom', fr: 'Objectifs de recherche avec la taxonomie de Bloom', it: 'Obiettivi di ricerca con la tassonomia di Bloom' },
  'video.metodo-objetivos.outcome': { es: 'Formular un objetivo general y tres específicos con verbos en infinitivo y niveles distintos.', en: 'Write one general and three specific objectives with infinitive verbs at different levels.', pt: 'Formular um objetivo geral e três específicos com verbos no infinitivo e níveis distintos.', fr: 'Formuler un objectif général et trois spécifiques, verbes à l\'infinitif et niveaux distincts.', it: 'Formulare un obiettivo generale e tre specifici con verbi all\'infinito e livelli diversi.' },
  'video.metodo-objetivos.moment': { es: 'Capítulo 1', en: 'Chapter 1', pt: 'Capítulo 1', fr: 'Chapitre 1', it: 'Capitolo 1' },
  'video.metodo-objetivos.query': { es: 'como formular objetivos generales y especificos taxonomia de bloom tesis', en: 'how to write general and specific research objectives bloom taxonomy', pt: 'como formular objetivos geral e especificos taxonomia de bloom tese', fr: 'comment formuler objectifs general et specifiques taxonomie de bloom memoire', it: 'come formulare obiettivi generale e specifici tassonomia di bloom tesi' },

  'video.metodo-matriz.title': { es: 'Matriz de consistencia paso a paso', en: 'The consistency matrix, step by step', pt: 'Matriz de consistência passo a passo', fr: 'La matrice de cohérence, pas à pas', it: 'La matrice di coerenza, passo dopo passo' },
  'video.metodo-matriz.outcome': { es: 'Alinear problema, objetivos, hipótesis, variables e indicadores en una sola tabla.', en: 'Align problem, objectives, hypotheses, variables and indicators in a single table.', pt: 'Alinhar problema, objetivos, hipóteses, variáveis e indicadores numa única tabela.', fr: 'Aligner problème, objectifs, hypothèses, variables et indicateurs dans un seul tableau.', it: 'Allineare problema, obiettivi, ipotesi, variabili e indicatori in un\'unica tabella.' },
  'video.metodo-matriz.moment': { es: 'Antes de presentar el Avance 1', en: 'Before submitting Advance 1', pt: 'Antes de apresentar a primeira entrega', fr: 'Avant de rendre le premier jalon', it: 'Prima di consegnare il primo avanzamento' },
  'video.metodo-matriz.query': { es: 'matriz de consistencia tesis como se llena paso a paso ejemplo', en: 'research consistency matrix how to fill it step by step example', pt: 'matriz de consistencia tese como preencher passo a passo exemplo', fr: 'matrice de coherence memoire comment la remplir etape par etape exemple', it: 'matrice di coerenza tesi come compilarla passo passo esempio' },

  'video.metodo-variables.title': { es: 'Operacionalización de variables', en: 'Operationalising variables', pt: 'Operacionalização de variáveis', fr: 'Opérationnalisation des variables', it: 'Operazionalizzazione delle variabili' },
  'video.metodo-variables.outcome': { es: 'Descomponer cada variable en dimensiones, indicadores e ítems medibles.', en: 'Break each variable down into dimensions, indicators and measurable items.', pt: 'Decompor cada variável em dimensões, indicadores e itens mensuráveis.', fr: 'Décomposer chaque variable en dimensions, indicateurs et items mesurables.', it: 'Scomporre ogni variabile in dimensioni, indicatori e item misurabili.' },
  'video.metodo-variables.moment': { es: 'Capítulo 3', en: 'Chapter 3', pt: 'Capítulo 3', fr: 'Chapitre 3', it: 'Capitolo 3' },
  'video.metodo-variables.query': { es: 'operacionalizacion de variables dimensiones indicadores ejemplo tesis', en: 'operationalization of variables dimensions indicators example thesis', pt: 'operacionalizacao de variaveis dimensoes indicadores exemplo tese', fr: 'operationnalisation des variables dimensions indicateurs exemple memoire', it: 'operazionalizzazione delle variabili dimensioni indicatori esempio tesi' },

  'video.metodo-marco.title': { es: 'Marco teórico: cómo dialogar con los autores', en: 'Theoretical framework: how to make authors talk to each other', pt: 'Marco teórico: como dialogar com os autores', fr: 'Cadre théorique : faire dialoguer les auteurs', it: 'Quadro teorico: come far dialogare gli autori' },
  'video.metodo-marco.outcome': { es: 'Pasar de una lista de definiciones a una discusión crítica entre autores.', en: 'Move from a list of definitions to a critical discussion between authors.', pt: 'Passar de uma lista de definições a uma discussão crítica entre autores.', fr: 'Passer d\'une liste de définitions à une discussion critique entre auteurs.', it: 'Passare da un elenco di definizioni a una discussione critica fra autori.' },
  'video.metodo-marco.moment': { es: 'Capítulo 2', en: 'Chapter 2', pt: 'Capítulo 2', fr: 'Chapitre 2', it: 'Capitolo 2' },
  'video.metodo-marco.query': { es: 'como redactar marco teorico tesis dialogo entre autores no copiar definiciones', en: 'how to write theoretical framework thesis critical discussion between authors', pt: 'como redigir marco teorico tese dialogo entre autores nao copiar definicoes', fr: 'comment rediger cadre theorique memoire dialogue entre auteurs', it: 'come scrivere quadro teorico tesi dialogo fra autori' },

  'video.metodo-requerimientos.title': { es: 'Requerimientos funcionales y no funcionales (IEEE 830)', en: 'Functional and non-functional requirements (IEEE 830)', pt: 'Requisitos funcionais e não funcionais (IEEE 830)', fr: 'Exigences fonctionnelles et non fonctionnelles (IEEE 830)', it: 'Requisiti funzionali e non funzionali (IEEE 830)' },
  'video.metodo-requerimientos.outcome': { es: 'Documentar la matriz de requerimientos con código, descripción, prioridad y métrica verificable.', en: 'Document the requirements matrix with ID, description, priority and a verifiable metric.', pt: 'Documentar a matriz de requisitos com código, descrição, prioridade e métrica verificável.', fr: 'Documenter la matrice d\'exigences avec code, description, priorité et métrique vérifiable.', it: 'Documentare la matrice dei requisiti con codice, descrizione, priorità e metrica verificabile.' },
  'video.metodo-requerimientos.moment': { es: 'Análisis del caso', en: 'Case analysis', pt: 'Análise do caso', fr: 'Analyse du cas', it: 'Analisi del caso' },
  'video.metodo-requerimientos.query': { es: 'requerimientos funcionales y no funcionales IEEE 830 ejemplo software', en: 'functional and non functional requirements IEEE 830 software example', pt: 'requisitos funcionais e nao funcionais IEEE 830 exemplo software', fr: 'exigences fonctionnelles et non fonctionnelles IEEE 830 exemple logiciel', it: 'requisiti funzionali e non funzionali IEEE 830 esempio software' },

  // --------------------------------------------------- Literatura científica
  'video.lit-scopus.title': { es: 'Buscar en Scopus y filtrar por cuartiles', en: 'Searching Scopus and filtering by quartile', pt: 'Buscar no Scopus e filtrar por quartis', fr: 'Chercher dans Scopus et filtrer par quartile', it: 'Cercare in Scopus e filtrare per quartili' },
  'video.lit-scopus.outcome': { es: 'Recuperar artículos Q1 y Q2 de los últimos cinco años y descartar el resto desde el filtro.', en: 'Pull Q1 and Q2 articles from the last five years and drop the rest at the filter stage.', pt: 'Recuperar artigos Q1 e Q2 dos últimos cinco anos e descartar o resto no filtro.', fr: 'Récupérer les articles Q1 et Q2 des cinq dernières années et écarter le reste dès le filtre.', it: 'Recuperare articoli Q1 e Q2 degli ultimi cinque anni e scartare il resto già dal filtro.' },
  'video.lit-scopus.moment': { es: 'Antes de escribir el marco teórico', en: 'Before writing the theoretical framework', pt: 'Antes de escrever o marco teórico', fr: 'Avant de rédiger le cadre théorique', it: 'Prima di scrivere il quadro teorico' },
  'video.lit-scopus.query': { es: 'como buscar articulos en Scopus filtros cuartiles Q1 Q2 tutorial', en: 'how to search Scopus filter quartiles Q1 Q2 tutorial', pt: 'como buscar artigos no Scopus filtros quartis Q1 Q2 tutorial', fr: 'comment chercher articles Scopus filtres quartiles Q1 Q2 tutoriel', it: 'come cercare articoli su Scopus filtri quartili Q1 Q2 tutorial' },

  'video.lit-booleanos.title': { es: 'Ecuaciones booleanas: AND, OR, NOT y truncamiento', en: 'Boolean queries: AND, OR, NOT and truncation', pt: 'Equações booleanas: AND, OR, NOT e truncamento', fr: 'Équations booléennes : AND, OR, NOT et troncature', it: 'Equazioni booleane: AND, OR, NOT e troncamento' },
  'video.lit-booleanos.outcome': { es: 'Construir ecuaciones con TITLE-ABS-KEY que devuelvan resultados manejables y pertinentes.', en: 'Build TITLE-ABS-KEY queries that return a manageable, relevant result set.', pt: 'Construir equações com TITLE-ABS-KEY que retornem resultados gerenciáveis e pertinentes.', fr: 'Construire des équations TITLE-ABS-KEY qui renvoient des résultats gérables et pertinents.', it: 'Costruire equazioni TITLE-ABS-KEY che restituiscano risultati gestibili e pertinenti.' },
  'video.lit-booleanos.moment': { es: 'Al iniciar la revisión de literatura', en: 'When starting the literature review', pt: 'Ao iniciar a revisão de literatura', fr: 'Au début de la revue de littérature', it: 'All\'inizio della revisione della letteratura' },
  'video.lit-booleanos.query': { es: 'operadores booleanos AND OR NOT busqueda bases de datos cientificas tutorial', en: 'boolean operators AND OR NOT scientific database search tutorial', pt: 'operadores booleanos AND OR NOT busca bases de dados cientificas tutorial', fr: 'operateurs booleens AND OR NOT recherche bases de donnees scientifiques tutoriel', it: 'operatori booleani AND OR NOT ricerca banche dati scientifiche tutorial' },

  'video.lit-scielo.title': { es: 'SciELO, Latindex y Redalyc para fuentes en español', en: 'SciELO, Latindex and Redalyc for Spanish-language sources', pt: 'SciELO, Latindex e Redalyc para fontes em espanhol e português', fr: 'SciELO, Latindex et Redalyc pour les sources hispanophones', it: 'SciELO, Latindex e Redalyc per fonti in spagnolo' },
  'video.lit-scielo.outcome': { es: 'Encontrar antecedentes nacionales y regionales cuando el tema tiene poca literatura en inglés.', en: 'Find national and regional prior work when the topic has little English-language literature.', pt: 'Encontrar antecedentes nacionais e regionais quando o tema tem pouca literatura em inglês.', fr: 'Trouver des antécédents nationaux et régionaux quand le sujet est peu traité en anglais.', it: 'Trovare antecedenti nazionali e regionali quando il tema ha poca letteratura in inglese.' },
  'video.lit-scielo.moment': { es: 'Antecedentes nacionales', en: 'National prior work', pt: 'Antecedentes nacionais', fr: 'Antécédents nationaux', it: 'Antecedenti nazionali' },
  'video.lit-scielo.query': { es: 'como buscar articulos cientificos SciELO Redalyc Latindex tutorial', en: 'how to search SciELO Redalyc Latindex scientific articles tutorial', pt: 'como buscar artigos cientificos SciELO Redalyc Latindex tutorial', fr: 'comment chercher articles scientifiques SciELO Redalyc Latindex tutoriel', it: 'come cercare articoli scientifici SciELO Redalyc Latindex tutorial' },

  'video.lit-mapas.title': { es: 'Connected Papers y VOSviewer para el estado del arte', en: 'Connected Papers and VOSviewer for the state of the art', pt: 'Connected Papers e VOSviewer para o estado da arte', fr: 'Connected Papers et VOSviewer pour l\'état de l\'art', it: 'Connected Papers e VOSviewer per lo stato dell\'arte' },
  'video.lit-mapas.outcome': { es: 'Detectar los artículos seminales de tu tema y visualizar las redes de coautoría.', en: 'Spot the seminal papers on your topic and visualise co-authorship networks.', pt: 'Detectar os artigos seminais do seu tema e visualizar as redes de coautoria.', fr: 'Repérer les articles fondateurs de votre sujet et visualiser les réseaux de coauteurs.', it: 'Individuare gli articoli seminali del tuo tema e visualizzare le reti di coautoria.' },
  'video.lit-mapas.moment': { es: 'Cuando no encuentras suficientes antecedentes', en: 'When you cannot find enough prior work', pt: 'Quando você não encontra antecedentes suficientes', fr: 'Quand vous manquez d\'antécédents', it: 'Quando non trovi abbastanza antecedenti' },
  'video.lit-mapas.query': { es: 'Connected Papers VOSviewer tutorial estado del arte revision bibliometrica', en: 'Connected Papers VOSviewer tutorial state of the art bibliometric review', pt: 'Connected Papers VOSviewer tutorial estado da arte revisao bibliometrica', fr: 'Connected Papers VOSviewer tutoriel etat de l art revue bibliometrique', it: 'Connected Papers VOSviewer tutorial stato dell arte revisione bibliometrica' },

  'video.lit-sistematica.title': { es: 'Revisión sistemática y PRISMA', en: 'Systematic review and PRISMA', pt: 'Revisão sistemática e PRISMA', fr: 'Revue systématique et PRISMA', it: 'Revisione sistematica e PRISMA' },
  'video.lit-sistematica.outcome': { es: 'Aplicar criterios de inclusión y exclusión y documentar cuántas fuentes se descartaron y por qué.', en: 'Apply inclusion and exclusion criteria and document how many sources were dropped and why.', pt: 'Aplicar critérios de inclusão e exclusão e documentar quantas fontes foram descartadas e por quê.', fr: 'Appliquer des critères d\'inclusion et d\'exclusion et documenter les sources écartées et pourquoi.', it: 'Applicare criteri di inclusione ed esclusione e documentare quante fonti sono state scartate e perché.' },
  'video.lit-sistematica.moment': { es: 'Si tu trabajo exige mapeo sistemático', en: 'If your work requires systematic mapping', pt: 'Se o seu trabalho exige mapeamento sistemático', fr: 'Si votre travail exige une cartographie systématique', it: 'Se il tuo lavoro richiede una mappatura sistematica' },
  'video.lit-sistematica.query': { es: 'revision sistematica de literatura PRISMA criterios inclusion exclusion tutorial', en: 'systematic literature review PRISMA inclusion exclusion criteria tutorial', pt: 'revisao sistematica de literatura PRISMA criterios inclusao exclusao tutorial', fr: 'revue systematique de litterature PRISMA criteres inclusion exclusion tutoriel', it: 'revisione sistematica della letteratura PRISMA criteri inclusione esclusione tutorial' },

  // ------------------------------------------------------------ Herramientas
  'video.tool-zotero.title': { es: 'Zotero 7 desde cero e integración con Word', en: 'Zotero 7 from scratch, with Word integration', pt: 'Zotero 7 do zero e integração com o Word', fr: 'Zotero 7 de zéro et intégration à Word', it: 'Zotero 7 da zero e integrazione con Word' },
  'video.tool-zotero.outcome': { es: 'Insertar citas con un atajo y generar la bibliografía en APA 7 sin corregir comas a mano.', en: 'Insert citations with a shortcut and build the APA 7 bibliography without fixing commas by hand.', pt: 'Inserir citações com um atalho e gerar a bibliografia em APA 7 sem corrigir vírgulas à mão.', fr: 'Insérer les citations par raccourci et générer la bibliographie APA 7 sans corriger les virgules.', it: 'Inserire citazioni con una scorciatoia e generare la bibliografia APA 7 senza correggere virgole a mano.' },
  'video.tool-zotero.moment': { es: 'Antes de escribir la primera cita', en: 'Before writing your first citation', pt: 'Antes de escrever a primeira citação', fr: 'Avant d\'écrire votre première citation', it: 'Prima di scrivere la prima citazione' },
  'video.tool-zotero.query': { es: 'Zotero 7 tutorial completo español integracion Word citas APA', en: 'Zotero 7 full tutorial Word integration APA citations', pt: 'Zotero 7 tutorial completo portugues integracao Word citacoes APA', fr: 'Zotero 7 tutoriel complet francais integration Word citations APA', it: 'Zotero 7 tutorial completo italiano integrazione Word citazioni APA' },

  'video.tool-apa.title': { es: 'Normas APA 7: citas, referencias y sangría francesa', en: 'APA 7: citations, references and hanging indent', pt: 'Normas APA 7: citações, referências e recuo francês', fr: 'Normes APA 7 : citations, références et retrait négatif', it: 'Norme APA 7: citazioni, riferimenti e rientro sporgente' },
  'video.tool-apa.outcome': { es: 'Aplicar la regla del et al., las citas en bloque y el formato exacto de referencias.', en: 'Apply the et al. rule, block quotations and the exact reference format.', pt: 'Aplicar a regra do et al., as citações em bloco e o formato exato das referências.', fr: 'Appliquer la règle du et al., les citations en bloc et le format exact des références.', it: 'Applicare la regola dell\'et al., le citazioni in blocco e il formato esatto dei riferimenti.' },
  'video.tool-apa.moment': { es: 'Durante toda la redacción', en: 'Throughout the writing', pt: 'Durante toda a redação', fr: 'Tout au long de la rédaction', it: 'Durante tutta la stesura' },
  'video.tool-apa.query': { es: 'normas APA 7 edicion citas y referencias tutorial completo español', en: 'APA 7th edition citations and references full tutorial', pt: 'normas APA 7 edicao citacoes e referencias tutorial completo', fr: 'normes APA 7e edition citations et references tutoriel complet', it: 'norme APA 7 edizione citazioni e riferimenti tutorial completo' },

  'video.tool-word.title': { es: 'Word académico: índice automático, estilos y numeración', en: 'Academic Word: automatic table of contents, styles and numbering', pt: 'Word acadêmico: sumário automático, estilos e numeração', fr: 'Word académique : sommaire automatique, styles et numérotation', it: 'Word accademico: indice automatico, stili e numerazione' },
  'video.tool-word.outcome': { es: 'Generar la tabla de contenido automática y numerar tablas y figuras con títulos vinculados.', en: 'Generate an automatic table of contents and number tables and figures with linked captions.', pt: 'Gerar o sumário automático e numerar tabelas e figuras com legendas vinculadas.', fr: 'Générer le sommaire automatique et numéroter tableaux et figures avec légendes liées.', it: 'Generare l\'indice automatico e numerare tabelle e figure con didascalie collegate.' },
  'video.tool-word.moment': { es: 'Al armar el documento final', en: 'When assembling the final document', pt: 'Ao montar o documento final', fr: 'Au moment de monter le document final', it: 'Quando componi il documento finale' },
  'video.tool-word.query': { es: 'Word tesis indice automatico estilos titulos numeracion tablas figuras tutorial', en: 'Word thesis automatic table of contents styles heading numbering tables figures tutorial', pt: 'Word tese sumario automatico estilos titulos numeracao tabelas figuras tutorial', fr: 'Word memoire sommaire automatique styles titres numerotation tableaux figures tutoriel', it: 'Word tesi indice automatico stili titoli numerazione tabelle figure tutorial' },

  'video.tool-turnitin.title': { es: 'Parafraseo correcto y control de similitud', en: 'Proper paraphrasing and similarity control', pt: 'Paráfrase correta e controle de similaridade', fr: 'Paraphrase correcte et contrôle de similarité', it: 'Parafrasi corretta e controllo della similarità' },
  'video.tool-turnitin.outcome': { es: 'Reducir el porcentaje de coincidencia sin caer en el reemplazo mecánico de sinónimos.', en: 'Lower the similarity score without resorting to mechanical synonym swapping.', pt: 'Reduzir a porcentagem de coincidência sem recorrer à troca mecânica de sinônimos.', fr: 'Réduire le taux de similarité sans recourir au remplacement mécanique de synonymes.', it: 'Ridurre la percentuale di somiglianza senza ricorrere alla sostituzione meccanica di sinonimi.' },
  'video.tool-turnitin.moment': { es: 'Antes de subir al sistema antiplagio', en: 'Before uploading to the plagiarism system', pt: 'Antes de enviar ao sistema antiplágio', fr: 'Avant l\'envoi au système antiplagiat', it: 'Prima di caricare sul sistema antiplagio' },
  'video.tool-turnitin.query': { es: 'como parafrasear correctamente tesis reducir similitud Turnitin sin plagio', en: 'how to paraphrase correctly thesis reduce Turnitin similarity without plagiarism', pt: 'como parafrasear corretamente tese reduzir similaridade Turnitin sem plagio', fr: 'comment paraphraser correctement memoire reduire similarite Turnitin sans plagiat', it: 'come parafrasare correttamente tesi ridurre similarita Turnitin senza plagio' },

  'video.tool-estadistica.title': { es: 'Jamovi y SPSS para el análisis de resultados', en: 'Jamovi and SPSS for analysing results', pt: 'Jamovi e SPSS para a análise de resultados', fr: 'Jamovi et SPSS pour l\'analyse des résultats', it: 'Jamovi e SPSS per l\'analisi dei risultati' },
  'video.tool-estadistica.outcome': { es: 'Ejecutar pruebas de normalidad, correlaciones y alfa de Cronbach e interpretar las salidas.', en: 'Run normality tests, correlations and Cronbach\'s alpha, and read the output.', pt: 'Executar testes de normalidade, correlações e alfa de Cronbach e interpretar as saídas.', fr: 'Lancer tests de normalité, corrélations et alpha de Cronbach, et interpréter les sorties.', it: 'Eseguire test di normalità, correlazioni e alfa di Cronbach e interpretare gli output.' },
  'video.tool-estadistica.moment': { es: 'Capítulo 4', en: 'Chapter 4', pt: 'Capítulo 4', fr: 'Chapitre 4', it: 'Capitolo 4' },
  'video.tool-estadistica.query': { es: 'Jamovi SPSS tutorial español normalidad correlacion alfa de Cronbach tesis', en: 'Jamovi SPSS tutorial normality correlation Cronbach alpha thesis', pt: 'Jamovi SPSS tutorial portugues normalidade correlacao alfa de Cronbach tese', fr: 'Jamovi SPSS tutoriel francais normalite correlation alpha de Cronbach memoire', it: 'Jamovi SPSS tutorial italiano normalita correlazione alfa di Cronbach tesi' },

  'video.tool-ia-etica.title': { es: 'Uso ético de IA en trabajos académicos', en: 'Ethical use of AI in academic work', pt: 'Uso ético de IA em trabalhos acadêmicos', fr: 'Usage éthique de l\'IA dans les travaux universitaires', it: 'Uso etico dell\'IA nei lavori accademici' },
  'video.tool-ia-etica.outcome': { es: 'Saber en qué puedes apoyarte y qué constituye una falta académica al usar IA generativa.', en: 'Know what you may lean on and what counts as academic misconduct when using generative AI.', pt: 'Saber em que você pode se apoiar e o que constitui falta acadêmica ao usar IA generativa.', fr: 'Savoir sur quoi s\'appuyer et ce qui constitue une faute académique avec l\'IA générative.', it: 'Sapere su cosa puoi appoggiarti e cosa costituisce illecito accademico usando l\'IA generativa.' },
  'video.tool-ia-etica.moment': { es: 'Antes de usar cualquier IA', en: 'Before using any AI', pt: 'Antes de usar qualquer IA', fr: 'Avant d\'utiliser une IA', it: 'Prima di usare qualsiasi IA' },
  'video.tool-ia-etica.query': { es: 'uso etico de inteligencia artificial en tesis que si y que no citar IA', en: 'ethical use of artificial intelligence in thesis what is allowed how to cite AI', pt: 'uso etico de inteligencia artificial em tese o que pode e como citar IA', fr: 'usage ethique intelligence artificielle memoire ce qui est permis citer une IA', it: 'uso etico intelligenza artificiale tesi cosa e permesso citare una IA' },

  // ----------------------------------------------------------- Sustentación
  'video.defensa-presentacion.title': { es: 'Diapositivas de sustentación en 10 minutos', en: 'Defence slides for a ten-minute talk', pt: 'Slides de defesa em 10 minutos', fr: 'Diapositives de soutenance en dix minutes', it: 'Diapositive di discussione in dieci minuti' },
  'video.defensa-presentacion.outcome': { es: 'Distribuir el tiempo entre problema, método, resultados y conclusiones sin saturar las diapositivas.', en: 'Budget your time across problem, method, results and conclusions without cramming the slides.', pt: 'Distribuir o tempo entre problema, método, resultados e conclusões sem saturar os slides.', fr: 'Répartir le temps entre problème, méthode, résultats et conclusions sans surcharger les diapositives.', it: 'Distribuire il tempo fra problema, metodo, risultati e conclusioni senza saturare le slide.' },
  'video.defensa-presentacion.moment': { es: 'Dos semanas antes de la defensa', en: 'Two weeks before the defence', pt: 'Duas semanas antes da defesa', fr: 'Deux semaines avant la soutenance', it: 'Due settimane prima della discussione' },
  'video.defensa-presentacion.query': { es: 'como preparar diapositivas sustentacion de tesis 10 minutos estructura', en: 'how to prepare thesis defence slides 10 minutes structure', pt: 'como preparar slides defesa de tese 10 minutos estrutura', fr: 'comment preparer diapositives soutenance memoire 10 minutes structure', it: 'come preparare diapositive discussione tesi 10 minuti struttura' },

  'video.defensa-preguntas.title': { es: 'Preguntas frecuentes en la defensa y cómo responderlas', en: 'Common defence questions and how to answer them', pt: 'Perguntas frequentes na defesa e como respondê-las', fr: 'Questions fréquentes en soutenance et comment y répondre', it: 'Domande frequenti in discussione e come rispondere' },
  'video.defensa-preguntas.outcome': { es: 'Anticipar las preguntas sobre muestra, metodología y limitaciones con respuestas preparadas.', en: 'Anticipate questions on sample, methodology and limitations with answers ready.', pt: 'Antecipar as perguntas sobre amostra, metodologia e limitações com respostas prontas.', fr: 'Anticiper les questions sur l\'échantillon, la méthodologie et les limites avec des réponses prêtes.', it: 'Anticipare le domande su campione, metodologia e limiti con risposte pronte.' },
  'video.defensa-preguntas.moment': { es: 'Antes de la defensa', en: 'Before the defence', pt: 'Antes da defesa', fr: 'Avant la soutenance', it: 'Prima della discussione' },
  'video.defensa-preguntas.query': { es: 'preguntas frecuentes defensa de tesis como responder sustentacion', en: 'common thesis defence questions how to answer them', pt: 'perguntas frequentes defesa de tese como responder', fr: 'questions frequentes soutenance memoire comment repondre', it: 'domande frequenti discussione tesi come rispondere' },

  'video.defensa-observaciones.title': { es: 'Cómo atender observaciones sin rehacer todo', en: 'Handling reviewer comments without redoing everything', pt: 'Como atender observações sem refazer tudo', fr: 'Traiter les remarques sans tout refaire', it: 'Gestire le osservazioni senza rifare tutto' },
  'video.defensa-observaciones.outcome': { es: 'Interpretar el comentario de fondo detrás de cada observación y priorizar las correcciones.', en: 'Read the underlying point behind each comment and prioritise the corrections.', pt: 'Interpretar o comentário de fundo por trás de cada observação e priorizar as correções.', fr: 'Saisir le fond derrière chaque remarque et hiérarchiser les corrections.', it: 'Cogliere il punto di fondo dietro ogni osservazione e dare priorità alle correzioni.' },
  'video.defensa-observaciones.moment': { es: 'Después de cada revisión', en: 'After each review round', pt: 'Depois de cada revisão', fr: 'Après chaque relecture', it: 'Dopo ogni revisione' },
  'video.defensa-observaciones.query': { es: 'como corregir observaciones de tesis del tutor priorizar correcciones', en: 'how to address thesis advisor comments prioritise corrections', pt: 'como corrigir observacoes de tese do orientador priorizar correcoes', fr: 'comment corriger remarques du directeur de memoire prioriser corrections', it: 'come correggere osservazioni del relatore di tesi dare priorita' },
};
